### ISSUE TITLE
luarocks install fails when user doesn't have write permissions to /usr despite /usr/local being target tree

### ISSUE THREAD

**Issue by Toenex** [keplerproject/luarocks#100]
## Issue

Trying to install rocks fails and produces the result

`Error: Your user does not have write permissions in /usr/
-- you may want to run as a privileged user or use your local tree with --local.`

Luarocks was installed using the default configuration and should be installing rocks into the `/usr/local` tree.  However, it appears to incorrectly check permissions in the `/usr` tree.  The user does have write permission for `/usr/local` but **does not** have write permissions for `/usr/`.
## Steps to reproduce

`luarocks install luafilesystem`
## Setup
- Linux Ubuntu 12.04 3.2.0-24-generic x64
- Lua 5.1.5 source build to `/usr/local`
- Luarocks 2.0.11 built from git repository on 27.09.12 with default configuration
## Other details

This is the installed `config.lua` taken from  `/usr/local/etc/luarocks`

`rocks_trees = {
          home..[[/.luarocks]],
          [[/usr/local]]
      }`

I also think issues #87 & #80 may be related.

**Comment by bunster** [comment]
I'm having the same issue here.

**Comment by huihuangz** [comment]
I'm having the same issue here.

**Comment by mpeterv** [comment]
@huihuangz @bunster which Luarocks version do you use? This was supposedly fixed long ago...

**Comment by MuraliGK** [comment]
@mpeterv  I'm also facing the same issue

**Comment by mpeterv** [comment]
@MuraliGK which Luarocks version do you have?

**Comment by adam-erickson** [comment]
Same issue here with a fresh install of Torch7 with luarocks v2.3.0 on OS X 10.11

**Comment by mpeterv** [comment]
@adam-erickson the first issue you've linked is not the same as this one, and is caused by incorrectly installing Torch with `sudo`. Did you have permission issues with `/usr` or your local torch installation?

**Comment by pauldelmusica** [comment]
I have the same problem. Removing /usr/local/bin and /usr/local/sbin from your system path did not solve the problem.

**Comment by RichardHuan** [comment]
@mpeterv my luarocks version is 2.0.8 and i have the same issue. What can I do?

**Comment by mpeterv** [comment]
@RichardHuan upgrade to a later version of luarocks. Current version is 2.4.2.

**Comment by pallaviroyal** [comment]
Faced same problem.
I followed instructions mentioned [here](http://torch.ch/docs/getting-started.html#_) 
Solved ::
My system is Ubuntu14.04 
After installation. I checked ~/.bashrc file.
In .bashrc file, removed 2nd  path (You can see bellow). Now working fine. Able to install required packages using luarocks

.bashrc
```
. /home/pallavi/torch/install/bin/torch-activate
. /torch/install/bin/torch-activate
```

**Comment by datthanhvu98** [comment]
sudo luarocks install *

**Comment by khaulahzia** [comment]
I have installed torch7 and dependencies but unable to install luarocks images,, i am again and again gettting permission denied problems. tried sudo chown. it says some operand missing. tried --local flag, it says no matching query found

**Comment by lukad** [comment]
What dirs under `/usr/local` does luarocks actually need write access to? And shouldn't it check those explicitly instead of checking `/usr/local` only?
My `/usr/local` is only writable by root but several sub directories are writable by my non root user.

```
~/c/sOS (master|✔) $ ls -la /usr/local/
total 0
drwxr-xr-x   18 root  wheel    612 Sep  5 15:12 .
drwxr-xr-x@  10 root  wheel    340 Jul 24 17:49 ..
drwxrwxr-x   32 luka  admin   1088 Sep  5 15:12 Caskroom
drwxrwxr-x  170 luka  admin   5780 Sep  5 17:01 Cellar
drwxrwxr-x    3 luka  admin    102 Jul 27 09:16 Frameworks
drwxrwxr-x   17 luka  admin    578 Aug  9 09:50 Homebrew
drwxr-xr-x    6 root  wheel    204 Oct 14  2016 MacGPG2
drwxrwxr-x  877 luka  admin  29818 Sep  5 17:01 bin
drwxrwxr-x   19 luka  admin    646 Sep  5 17:01 etc
drwxrwxr-x  202 luka  staff   6868 Sep  5 17:01 include
drwxrwxr-x  642 luka  staff  21828 Sep  5 17:01 lib
drwxr-xr-x    3 root  wheel    102 Aug 16 17:25 man
drwxr-xr-x    3 root  wheel    102 Aug 24 18:58 microsoft
drwxrwxr-x  215 luka  admin   7310 Sep  5 17:01 opt
drwxr-xr-x    3 luka  wheel    102 Feb 14  2017 remotedesktop
drwxrwxr-x    8 luka  admin    272 Aug  2 09:29 sbin
drwxrwxr-x   70 luka  admin   2380 Sep  5 17:01 share
drwxrwxr-x    9 luka  admin    306 Aug 14 14:54 var
```

**Comment by zqplus** [comment]
I have met same problem. I tried above solutions but can not work.
Then I read the official file carefully, and tried this command:
The script adds torch to your PATH variable. You just have to source it once to refresh your env variables. The installation script will detect what is your current shell and modify the path in the correct configuration file.

# On Linux with bash
source ~/.bashrc
# On Linux with zsh
source ~/.zshrc
# On OSX or in Linux with none of the above.
source ~/.profile

Then it could work well !!!

**Comment by mikeytag** [comment]
I had this issue on Ubuntu 18.04 and the following command fixed it for me. For some reason the ~/.cache/luarocks directory was owned by root:root on my system

`sudo chown -R yourusername:yourusername ~/.cache/luarocks`

**Comment by Natfan** [comment]
I was able to resolve this on `Ubuntu 20.04.6 LTS` with the following command, which grants other users (such as yourself) access to read and execute the shared luarocks libraries:

    sudo chmod o+rx /usr/local/share/lua/ -R

**Comment by alerque** [comment]
@Natfan That will give *any and all* users write access to a location that gets automatically read and executed by many apps. That is a huge security hole you just opened in your own system. Of course you can do whatever you want with your own systems, but that's not a good thing to recommend as a general purpose solution, especially not without a warning about the consequences.

Users wishing wishing to install to the system should have system admin privs and just use sudo to do the install, not leave a system directory writable to anybody. Or just use user-space installs.

**Comment by BecauseTheWorldIsRound** [comment]
> @Natfan That will give _any and all_ users write access 

Why adding Read and Exec to the files would grand Write access?
