### ISSUE TITLE
Forced rock removal is too slow if too many rocks depend on it

### ISSUE THREAD

**Issue by agladysh** [keplerproject/luarocks#144]
<pre>
$ sudo luarocks remove --force lua-aplicado
Removing lua-aplicado scm-1...
Missing dependency for [private rock 1] scm-1: lua-aplicado >= 0.0.1
...
Missing dependency for [private rock 100] scm-1: lua-aplicado >= 0.0.1
</pre>

Each of missing dependency lines takes a noticeable part of a second on my machine for some reason.

Can we have a --quiet option to remove these checks and waste of time? Altogether with no-so-fast stability check:

<pre>
Checking stability of dependencies on the absence of
lua-aplicado scm-1...

The following packages may be broken by this forced removal:
pk-engine scm-1
pk-questengine-lib scm-1
pk-logiceditor-com-sys_msg_broker scm-1
pk-tools.pk-rotate-wsapi-log scm-1
pk-core scm-1
pk-logiceditor-com.api scm-1
pk-project-tools.pk-project-create scm-1
pk-logiceditor-com.lib scm-1
pk-test scm-1
</pre>

It is good to see when one removes rock manually, but totally useless in an automated script.

**Comment by mpeterv** [comment]
`Error: Invalid argument: flag --force does not take an parameter. See --help.`

oops

Is this supposed to work?

**Comment by hishamhm** [comment]
Oh, this was a regression. The flag "type checker" does not support, err, "polymorphic" flags, and --force is marked as a boolean flag. Since this was not noticed for a long time I think it's not a problem to change usage to something like `--force --fast` (or `--force-fast`) and keep the logic of flag types simple.

**Comment by mpeterv** [comment]
Changed to `--force-fast` in @8915604
