### ISSUE TITLE
No support for ssh-based source protocols (like git+ssh)

### ISSUE THREAD

**Issue by agladysh** [keplerproject/luarocks#18]
since LR is to be run with sudo, and root does not see my keys

**Comment by hishamhm** [comment]
> However allowing a sudo session to use your personal SSH credentials is still an open question.

I guess `sudo -H` would do that?

**Comment by daurnimator** [comment]
> I guess sudo -H would do that?

There's much more to it. e.g. XDG env vars, or your ssh auth sock, and it gets complicated due to requirements for registering the current TTY with e.g. your `askpass` helper.
