### ISSUE TITLE
Failed unpacking rock file

### ISSUE THREAD

**Issue by tarruda** [keplerproject/luarocks#238]
``` sh
$ luarocks install --server=http://rocks.moonscript.org moonrocks
Warning: Failed searching manifest: Failed loading manifest: Failed extracting manifest file
Installing http://rocks.moonscript.org/moonrocks-0.0.1-1.src.rock...
Using http://rocks.moonscript.org/moonrocks-0.0.1-1.src.rock... switching to 'build' mode

Error: Failed unpacking rock file: /tmp/luarocks_luarocks-rock-moonrocks-0.0.1-1-3429/moonrocks-0.0.1-1.src.rock
```

I have two VMs, both are ubuntu 12.04, one is 32-bit and another is 64-bit(freshly created). The command works on the 32-bit VM but on the 64-bit VM it fails with the error reported above. How can I debug what's wrong?

**Comment by andrewstarks** [comment]
i didn't see --verbose when i typed `luarockt help install` as an option. I ran into this when installing luarocks on my Lego EV3 brick. It includes... very very little. :)

**Comment by TamaMcGlinn** [comment]
I really need that descriptive error message. @tarruda how did you debug this?

```
$ sudo luarocks build mpack

Error: Error fetching file: Failed downloading https://github.com/libmpack/libmpack-lua/releases/download/1.0.8/libmpack-lua-1.0.8.tar.gz - libmpack-lua-1.0.8.tar.gz
```

And the file exists and `unzip` also exists on my system.

**Comment by FrazAli** [comment]
> I really need that descriptive error message. @tarruda how did you debug this?
> 
> ```
> $ sudo luarocks build mpack
> 
> Error: Error fetching file: Failed downloading https://github.com/libmpack/libmpack-lua/releases/download/1.0.8/libmpack-lua-1.0.8.tar.gz - libmpack-lua-1.0.8.tar.gz
> ```
> 
> And the file exists and `unzip` also exists on my system.

Same here! 
Any solution to this or ways to debug this ?

**Comment by hishamhm** [comment]
@FrazAli I could not reproduce the issue here, `sudo luarocks build mpack` installed correctly.

Try running the command `sudo luarocks config fs_use_modules false` (this will tell LuaRocks to not try to use LuaSocket/LuaSec to download the file and instead try to use curl or wget) and then try `sudo luarocks build mpack --verbose` again. Does it make any difference?

Also, make sure you're running the latest version of LuaRocks, if possible!
