### ISSUE TITLE
Fail install module after install luasocket

### ISSUE THREAD

**Issue by moteus** [keplerproject/luarocks#270]
This is [travis job](https://travis-ci.org/moteus/lua-pop3/jobs/26745874) with LR 2.2.0beta1.
This works with [LR 2.1.0](https://travis-ci.org/moteus/lua-pop3/jobs/26746331)

**Comment by hishamhm** [comment]
>    Maybe... LR can check the protocol. If it has luasocket installed but not luasec,
>    it should fall back to wget.

We do this, by now. I just forgot to close the issue.
