### ISSUE TITLE
Problem Installing luarocks on mingw-w64

### ISSUE THREAD

**Issue by Sharadhonavar** [keplerproject/luarocks#275]
Am new to this git, forum and Lua/Luarocks. Pardon me if this is not the correct venue or protocol to post individual issues. Am wondering if mingw is not a supported platform for luarocks.

I have mingw64 and msys env on Windows 7, The Lua  install went normally and the lua executabes/libs/includes got installed in /usr/local/bin,  /usr/local/lib , /usr/local/include, and ran some lua scripts successfully.  (the /usr is mounted on E:\Applications\msys, and Windows System32 is on C:)

Then ran the Luarocks install for Unix from a bash shell in msys. the install seems to have gone well. But then running luarocks from the command line gives the follwing errors 

$ luarocks
E:\Applications\msys\local\bin\lua.exe: E:/Applications/msys/local/bin/luarocks:
4: module 'luarocks.loader' not found:
        no field package.preload['luarocks.loader']
        no file '/usr/local/share/lua/5.2/luarocks\loader.lua'
        no file 'E:/Applications/msys/local/bin'
        no file 'E:\Applications\msys\local\bin\luarocks\loader.dll'
        no file 'E:\Applications\msys\local\bin\loadall.dll'
        no file '.\luarocks\loader.dll'
        no file 'E:\Applications\msys\local\bin\luarocks.dll'
        no file 'E:\Applications\msys\local\bin\loadall.dll'
        no file '.\luarocks.dll'
stack traceback:
        [C]: in function 'require'
        E:/Applications/msys/local/bin/luarocks:4: in main chunk
        [C]: in ?

**Comment by hishamhm** [comment]
To be clear, the mingw compiler is supported, but the msys Unix-emulation environment isn't (we just never tested this combination).

Try following the [Installation instructions for Windows](https://github.com/keplerproject/luarocks/wiki/Installation-instructions-for-Windows) for installing via Windows CMD.

If you'd like to add support for msys, patches are welcome!

**Comment by RickLeaf** [comment]
I have made some modification for this.

https://github.com/RickLeaf/mingw-w64-lua-luarocks
