### ISSUE TITLE
Fails to pack some large rocks when lzlib is installed

### ISSUE THREAD

**Issue by ignacio** [keplerproject/luarocks#28]
Hi. I found that some of my rocks fails to install because its .rock file is corrupt. This is happening, for instance, with a rock I have that contains a large .so (about 4mb).

``` sh
ignacio@ignacio-VirtualBox:~/devel/sources$ unzip -t lua_cassandra-git-1.linux-x86.rock
Archive:  lua_cassandra-git-1.linux-x86.rock
    testing: rock_manifest            OK
    testing: lua_cassandra-git-1.rockspec   OK
    testing: lib/lua_cassandra.so     bad CRC 1f0cb24a  (should be a65c8220)
    testing: doc/keyspace-agent.1.ronn   OK
    testing: doc/column-family-contacts.1.ronn   OK
    testing: doc/keyspace-interactions.1.ronn   OK
    testing: doc/keyspace-repository.1.ronn   OK
    testing: doc/keyspace-contacts.1.ronn   OK
    testing: doc/column-family-users.1.ronn   OK
    testing: doc/column-family-files.1.ronn   OK
At least one error was detected in lua_cassandra-git-1.linux-x86.rock.
```

That only happens because I have lzlib installed. If I remove it, then the rock above packs and installs just fine.

I looked into `tools/zlib.lua` and found out that if I change:

``` lua
local size_buf = 65535
```

to

``` lua
local size_buf = 65535 * 500
```

then it packs correctly. But that's quite an ugly hack :D

Anyway, I looked for a proper fix, and I found that lzlib has a non documented method called `compressobj`, that returns an object that lets you pass chunks of data to be compressed. So I changed `zipwriter_write_file_in_zip` to use it, and it packs fine now.

The thing is, that method is not present in lzlib-0.4 (work3) that was released last year. 
I could send a pull request with my fix, but it will break if lzlib-0.4 gets released (or you managed to install anything other than lzlib-0.3).
I also could polish my fix a bit, and contemplate both cases (lzlib 0.3 and 0.4)

Let me know what you think.

Regards!

**Comment by daurnimator** [comment]
Relevant: https://github.com/brimworks/lua-zlib/issues/24

lzlib isn't the only lua library that claims 'zlib' for it's require string.
Can we feature detect which zlib library gets loaded?
