### ISSUE TITLE
Command to install dependencies

### ISSUE THREAD

**Issue by tbastos** [keplerproject/luarocks#287]
I would like to use LuaRocks to install the dependencies listed in a rockspec without starting a full build/install. This is handy in build scripts that must integrate LuaRocks with other build tools.

For example, I need to:
1. Install project dependencies.
2. Build and run tests using other tools (not LuaRocks).
3. Only then use LuaRocks to create a rock.

I want to avoid repeating my dependencies both in the rockspec and in the build script (where I'd have to write many "sudo luarocks install x" lines).

In Ruby I may have a "Gemfile" within a project and run the command `bundle` to install dependencies and prepare the environment to build the project. Is there anything similar in luarocks?

Thanks

**Comment by ignacio** [comment]
A new flag (--only-deps ?) should be added in order to do that. It should be forwarded to the build command as well and it should stop after fulfilling the dependencies.

@hishamhm is that correct?

**Comment by ignacio** [comment]
Also, you may give [Moonbox](https://github.com/kernelp4nic/moonbox) a go.

**Comment by hishamhm** [comment]
Yes, this could be possibly added as a flag to `build` without adding a lot of code.

**Comment by ignacio** [comment]
Fixed by #349
