### ISSUE TITLE
Deps check fails even though build will succeed (LuaSec)

### ISSUE THREAD

**Issue by lightpriest** [keplerproject/luarocks#289]
When building LuaSec on FC20 (Fedora Core 20), luarocks fails prior to the installation claiming to not find libssl.so:

```
# luarocks install LuaSec
Installing http://www.luarocks.org/repositories/rocks/luasec-0.5-2.src.rock...
Using http://www.luarocks.org/repositories/rocks/luasec-0.5-2.src.rock... switching to 'build' mode

Error: Could not find expected file libssl.a, or libssl.so, or libssl.so.* for OPENSSL -- you may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_LIBDIR to the luarocks command. Example: luarocks install luasec OPENSSL_DIR=/usr/local
```

Even though the linker will find it at build time (libssl.so):

```
$ ldconfig -p | grep libssl.so
    libssl.so.10 (libc6,x86-64) => /lib64/libssl.so.10
    libssl.so (libc6,x86-64) => /lib64/libssl.so
```

I guess the problem lies in `luarocks/cfg.lua` which sets `/usr/lib` instead of `/usr/lib64` (on FC20), but since I don't know the project's structure too well I wasn't sure how to address it. As a side note, instead of looking directly for the files, I would recommend using `ld`: `ld -l<lib>` would have an exit code of 0 if available and 1 if not.

As a workaround, this should work: `luarocks install LuaSec OPENSSL_LIBDIR=/usr/lib64`

---

From luasec-0.5-2.rockspec:

```
external_dependencies = {
   platforms = {
      unix = {
         OPENSSL = {
            header = "openssl/ssl.h",
            library = "ssl"
         }
      }
   }
}
```

**Comment by kgrvamsi** [comment]
Infact this solved the problem

OPENSSL_DIR refers to a "prefix" directory. Use OPENSSL_LIBDIR to pass

 sudo luarocks install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu/

**Comment by xpol** [comment]
This solved my problem on Mac 10.11 with Xcode 7:

1. `brew install openssl`
2. `luarocks install luasec OPENSSL_LIBDIR=/usr/local/Cellar/openssl/1.0.2e/lib/ OPENSSL_DIR=/usr/local/Cellar/openssl/1.0.2e`

**Comment by VADemon** [comment]
Luarocks v2.2.0, Debian on ARM-hf:
```
$ ldconfig -p | grep libssl.so
   libssl.so.1.0.0 (libc6,hard-float) =>/usr/lib/arm-linux-gnueabihf/libssl.so.1.0.0
   libssl.so (libc6,hard-float) =>/usr/lib/arm-linux-gnueabihf/libssl.so
```
```
apt-get -y install libssl-dev
luarocks install luasec OPENSSL_LIBDIR=/usr/lib/arm-linux-gnueabihf/
```
So neither did it find automatically for me, I had to fix it manually.

**Comment by lav45** [comment]
> Infact this solved the problem
> 
> OPENSSL_DIR refers to a "prefix" directory. Use OPENSSL_LIBDIR to pass
> 
> sudo luarocks install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu/

```
~$ sudo luarocks install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu/ --only-server=http://rocks.moonscript.org
```

**Comment by nodecentral** [comment]
Hi, on my pi

````
Installing https://luarocks.org/luasec-0.9-1.src.rock

Error: Could not find library file for OPENSSL
  No file libssl.a in /usr/lib/x86_64-linux-gnu/
  No file libssl.so in /usr/lib/x86_64-linux-gnu/
  No file matching libssl.so.* in /usr/lib/x86_64-linux-gnu/
````
The following **did not** work, does anyone have any other suggestions?
````
sudo luarocks install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu/
sudo luarocks install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu/ --only-server=http://rocks.moonscript.org

**Comment by daurnimator** [comment]
> Hi, on my pi

> /usr/lib/x86_64-linux-gnu/

You've somehow configured your raspberry pi (an arm device) to look in x86_64 locations.

I vaguely recall seeing this before, and it might be an issue with debian packaging?
