### ISSUE TITLE
unable to execute /usr/local/bin/luarocks during install on Ubuntu 14.04

### ISSUE THREAD

**Issue by gunchleoc** [keplerproject/luarocks#293]
Since the version in the Ubuntu repository is too old for my needs, I tried compiling luarocks from source. Since the config didn't manage to find Lua on its own, I ran the luarocks config with:

> ./configure --with-lua=/usr

and installed with:

> sudo luarocks install luacheck

 Then I got:

> sudo: unable to execute /usr/local/bin/luarocks: No such file or directory

I do have a symlink /usr/local/bin/luarocks that points to `/usr/local/bin/luarocks-5.1`

**Comment by ignacio** [comment]
Can we close this or does this comment https://github.com/keplerproject/luarocks/issues/293#issuecomment-61143471 still stand?

**Comment by gunchleoc** [comment]
I managed to get it running, so I think we can close this, unless you wish to add some documentation somewhere.

**Comment by faustinoaq** [comment]
I did `sudo apt-get install liblua5.2-dev` and my problem is solved.

**Comment by davincif** [comment]
I have downloaded lua5.3.5, compiled and installed it.
Then doenloaded luarocks3.1.3 and `./configure` give me something very similar: `lua.h not found (tried /usr/include/lua/5.1/lua.h /usr/include/lua5.1/lua.h /usr/include/lua51/lua.h /usr/include/lua.h /usr/include/luajit-2.1/lua.h)`

**Comment by daurnimator** [comment]
@davincif where is your lua.h then?

**Comment by davincif** [comment]
> @davincif where is your lua.h then?

Just found it using `whereis lua`, it returned me exactly: `lua: /usr/local/bin/lua /usr/local/lib/lua`.
Then a did `./configure --with-lua=/usr/local/` and it worked :)
My system is **Linux Mint 19 Cinnamon** by the way.

**Comment by The-night-elves** [comment]
Error: lua.h for Lua 5.1 not found
Install: sudo aptitude install liblua5.1-0-dev
