### ISSUE TITLE
Fail install rockspec from specific server

### ISSUE THREAD

**Issue by moteus** [keplerproject/luarocks#297]
I just add [lbase64](https://rocks.moonscript.org/modules/moteus/lbase64) to my manifest.
When I try install it like
`sudo luarocks install lbase64 --server=https://rocks.moonscript.org/manifests/moteus`
I got
```Bash
Installing https://rocks.moonscript.org/lbase64-20120820-1.src.rock...
Using https://rocks.moonscript.org/lbase64-20120820-1.src.rock... switching to 'build' mode
Do not use 'module' as a build type. Use 'builtin' instead.
gcc -O2 -fPIC -I/usr/local/include -c lbase64.c -o lbase64.o
gcc -shared -o base64.so -L/usr/local/lib lbase64.o
Updating manifest for /usr/local/lib/luarocks/rocks
lbase64 20120820-1 is now built and installed in /usr/local (license: Public domain)
```
Same result on my Wndows system with current master.

Update.
When I test my manifest contains only `scm` version.
Also `sudo luarocks install lunitx --server=https://rocks.moonscript.org/manifests/moteus` works fine and install my scm version.

**Comment by ignacio** [comment]
That is correct. The --server flag tells LuaRocks to look for rocks in this server, but also uses the servers specified in the config file. So LR finds a better match for lbase64 in a different server and installs that.

You need to use --only-server, as in:
~~~~
luarocks install lbase64 --only-server=https://rocks.moonscript.org/manifests/moteus

Installing https://rocks.moonscript.org/manifests/moteus/lbase64-20100323-1.src.rock...
Using https://rocks.moonscript.org/manifests/moteus/lbase64-20100323-1.src.rock... switching to 'build' mode
~~~~
