### ISSUE TITLE
configure problem with unusual Lua directory layout

### ISSUE THREAD

**Issue by siffiejoe** [keplerproject/luarocks#301]
The following `./configure` incantation yields an unwanted `LUA_SUFFIX=5.3` in `config.unix` (the binary is called `lua`):

    ./configure --prefix=/home/siffiejoe/.self/programs/luarocks-2.2.0/ --lua-version=5.3 --versioned-rocks-dir --force-config --with-lua=/home/siffiejoe/.self/programs/lua5.3 --with-lua-include=/home/siffiejoe/.self/programs/lua5.3 --with-lua-bin=/home/siffiejoe/.self/programs/lua5.3 --with-lua-lib=/home/siffiejoe/.self/programs/lua5.3

and I can't specify an explicitly empty `--lua-suffix`, so I had to edit `config.unix` by hand. The reason seems to be that the `search_interpreter` function refers to an outside loop variable `suffix`.

**Comment by hishamhm** [comment]
Does changing all instances inside `search_interpreter` from `$suffix` to `$LUA_SUFFIX` fix this?

**Comment by siffiejoe** [comment]
@hishamhm: No, but it sounds like a reasonable change anyway. Changing `if [ -n "$find_lua" ]` to

if [ -n "$find_lua" -a -x "$find_lua/bin$LUA_SUFFIX" ]

seems to fix it.

**Comment by hishamhm** [comment]
Got it. This should fix it. (I'm fixing the testsuite for 5.3 in the meantime :) )

**Comment by hishamhm** [comment]
Thanks for the cprint fix while I was having dinner! :)
