### ISSUE TITLE
Upgrading a rock with bin scripts deletes them (Windows only)

### ISSUE THREAD

**Issue by ignacio** [keplerproject/luarocks#302]
For instance, luacheck installs a bin script (luacheck.bat). I had version 0.7.3 installed. When I upgraded to version 0.8.0, the script got deleted.

The script was located in `C:\luarocks\systree\bin\luacheck.bat`

~~~~
D:\>luarocks install luacheck
Installing https://rocks.moonscript.org/luacheck-0.8.0-1.src.rock...
Using https://rocks.moonscript.org/luacheck-0.8.0-1.src.rock... switching to 'build' mode
Updating manifest for c:\luarocks\systree/lib/luarocks/rocks
luacheck 0.8.0-1 is now built and installed in c:\luarocks\systree (license: MIT/X11)

Checking stability of dependencies on the absence of
luacheck 0.7.3-1...

Removing luacheck 0.7.3-1...
c:\luarocks\2.2\tools\cp: cannot stat `c:\\luarocks\\systree\\bin\\luacheck_0_7_3_1-luacheck.bat': No such file or directory
c:\luarocks\2.2\tools\cp: cannot stat `c:\\luarocks\\systree\\share\\lua\\5.1\\luacheck_0_7_3_1-luacheck.lua': No such file or directory
Removal successful.
~~~~

I uploaded the result of `luarocks install luacheck --verbose` here:
https://www.dropbox.com/s/rpyl02lbwk3wqw3/luarocks_issue.zip?dl=0

**Comment by mpeterv** [comment]
luacheck 0.7.3 doesn't contain luacheck.bat script. luacheck 0.8.0 does, but it's not in the rockspec.

On Linux I only got the second error message when upgrading from 0.7.3 to 0.10.0 (`cannot stat /usr/local/share/lua/5.3/luacheck_0_7_3_1-luacheck.lua`). Conversely, downgrading from 0.10.0 to 0.7.3 produces `cannot stat /usr/local/share/lua/5.3/luacheck_0_7_3_1-luacheck/init.lua`.

It seems that the cause of the error is that `repos.delete_version` assumes that modules are provided by same files in the new, installed rock and the old one being removed. The error is produced here: https://github.com/keplerproject/luarocks/blob/ae51a3c726366c635bda06f2efa0cab47f9ceeaf/src/luarocks/repos.lua#L295  - (note that `fs.move` doesn't verify that source file exists). In luacheck 0.7.3 `luacheck` module was provided by `luacheck.lua`, in 0.10.0 by `luacheck/init.lua`.

I'm not familiar with LuaRocks internals enough to fix this or to say if the bin script error shares the cause.

**Comment by mpeterv** [comment]
This may be related to #268

**Comment by ignacio** [comment]
I get the same error going from 0.8.0. to 0.9.0:

~~~~
C:\Users\Ignacio>luarocks install luacheck 0.8.0
Installing https://rocks.moonscript.org/luacheck-0.8.0-1.src.rock...
Using https://rocks.moonscript.org/luacheck-0.8.0-1.src.rock... switching to 'build' mode
Updating manifest for c:\luarocks\systree/lib/luarocks/rocks
luacheck 0.8.0-1 is now built and installed in c:\luarocks\systree (license: MIT/X11)

C:\Users\Ignacio>luarocks install luacheck 0.9.0
Installing https://rocks.moonscript.org/luacheck-0.9.0-1.src.rock...
Using https://rocks.moonscript.org/luacheck-0.9.0-1.src.rock... switching to 'build' mode
Updating manifest for c:\luarocks\systree/lib/luarocks/rocks
luacheck 0.9.0-1 is now built and installed in c:\luarocks\systree (license: MIT <http://opensource.org/licenses/MIT>)

Checking stability of dependencies on the absence of
luacheck 0.8.0-1...

Removing luacheck 0.8.0-1...
c:\luarocks\2.2\tools\cp: cannot stat `c:\\luarocks\\systree\\bin\\luacheck_0_8_0_1-luacheck.bat': No such file or directory
Removal successful.
~~~~

**Comment by mpeterv** [comment]
This happens still, and it seems there are several distinct issues. The problem that causes script deletion is that when deploying files for a new version LuaRocks doesn't use `.bat` suffix when checking if a script is already deployed, and so it always overwrites it instead of moving either versioned to a versioned location. Then when removing older versions it deletes the script thinking it belongs to an old version.
