### ISSUE TITLE
LuaRocks.org down (TTL exceeded)

### ISSUE THREAD

**Issue by KateAdams** [keplerproject/luarocks#306]

**Comment by hishamhm** [comment]
we're aware of it and we're trying to fix it with the hosting provider — will report back here as soon as it's back up. Thanks!

**Comment by KateAdams** [comment]
Ah, I see; thanks for responding so quickly!

**Comment by tupton** [comment]
Is there a way to build or otherwise install luarocks while the site is down?

**Comment by siffiejoe** [comment]
Hisham has added [a gh-pages branch][1] to this repository a few hours ago. And of course you can install from a cloned github repository ...

  [1]: http://keplerproject.github.io/luarocks/

**Comment by tupton** [comment]
Cool, I figured as much, but there are no instructions in the README.

From a quick look at the `Makefile`, it's just `make build` and `make install`, right? Any caveats or special instructions for OS X?

**Comment by hishamhm** [comment]
./configure; make build; sudo make install

or

./configure; sudo make bootstrap

**Comment by hishamhm** [comment]
luarocks.org is back up, merged with the MoonRocks site. :)
