### ISSUE TITLE
problem with library installation

### ISSUE THREAD

**Issue by EvandroLG** [keplerproject/luarocks#311]
I added the following module in luarocks: https://rocks.moonscript.org/modules/evandrolg/pegasus
But when I execute this command:
```shell
  luarocks install pegasus
```
I receive this error message:
```shell
  stat: pegasus/response.lua: stat: No such file or directory
  Error: Build error: Failed installing pegasus/response.lua in /usr/local/lib/luarocks/rocks/pegasus/0.0.1-1/lua/pegasus/response.lua
```

**Comment by hishamhm** [comment]
Hi, I could not reproduce the problem here. The package installed correctly.

But let's diagnose your problem. Can you run the command with the `--verbose` flag and post the full output here? (If it's too long you may paste to http://gist.github.com and post a link here)

**Comment by EvandroLG** [comment]
Hm. I run the command now and the package was installed correctly for me too.
I didn't change anything.

Thanks, man!

**Comment by hishamhm** [comment]
No problem! Let us know if it happens again.
