### ISSUE TITLE
dkjson dependency issue

### ISSUE THREAD

**Issue by egoeran** [keplerproject/luarocks#312]
I installed lua 5.3 from the .sh file provided on the lua website. Then I installed luarocks, like it was written on the wiki. I entered the zip, typed ./configure and also specified --lua-version=5.3 because it was using 5.1 for some reason (I also installed it withouth the flag, the error remains the same). Now I try installing busted: sudo luarocks install busted Everything works until:

```
Using https://rocks.moonscript.org/dkjson-2.5-1.src.rock... switching to 'build' mode

Missing dependencies for dkjson:
lua >= 5.1, < 5.3

Error: Failed installing dependency: https://rocks.moonscript.org/dkjson-2.5-1.src.rock - Could not satisfy dependency: lua >= 5.1, < 5.3
```

busted is compatible with 5.3 (as far as I know), so why would this not work. Anyone able to maybe tell me a mistake in my installation process? 

This is the current configuration:

```
CONFIGURATION
	Lua version: 5.3
	Configuration files:
		System: /usr/local/etc/luarocks/config-5.3.lua (ok)
		User  : /root/.luarocks/config-5.3.lua (failed)

	Rocks trees in use: 
		/root/.luarocks ("user")
		/usr/local ("system")
```

Why does it say failed ? I'm confused :octocat:

**Comment by ignacio** [comment]
One of Busted dependencies does not support Lua 5.3. That's what this message is saying:

~~~~
Error: Failed installing dependency: https://rocks.moonscript.org/dkjson-2.5-1.src.rock - Could not satisfy dependency: lua >= 5.1, < 5.3
~~~~

You might want to open an issue here:

https://github.com/Olivine-Labs/busted

**Comment by mpeterv** [comment]
@egoeran dkjson, the failing dependency, is only used for the JSON output formatter in busted. So, even if it does not work under Lua 5.3, you probably won't notice. You can install it forcefully by running `sudo luarocks install dkjson --deps-mode=none`.

**Comment by daurnimator** [comment]
> You can install it forcefully by running sudo luarocks install dkjson --deps-mode=none.

It would be better to forcefully install busted without the dkjson dependancy, than forcefully install dkjson wiith the wrong lua dependancy.

**Comment by mpeterv** [comment]
> It would be better to forcefully install busted without the dkjson dependancy, than forcefully install dkjson wiith the wrong lua dependancy.

Right. I agree, having possibly broken libraries around is a bad idea.

**Comment by hishamhm** [comment]
Closing this since, as @ignacio said, it's a matter of dependency config in Busted.
