### ISSUE TITLE
404 Not Found when download dependency that exists in the LuaRocks repo

### ISSUE THREAD

**Issue by thefosk** [keplerproject/luarocks#313]
I'm trying to download `busted ~> 2.0.rc6-0` that exists in the repo at https://rocks.moonscript.org/modules/olivine-labs/busted

But when trying to install it, LuaRocks tells me that:

```
Warning: Failed searching manifest: Failed loading manifest: Failed fetching manifest for http://www.luarocks.org/repositories/rocks - Failed downloading http://www.luarocks.org/repositories/rocks/manifest - HTTP/1.1 404 Not Found

Error: Could not satisfy dependency: busted ~> 2.0.rc6-0
```

**Comment by ignacio** [comment]
I just tried and installed it succesfully:
`luarocks install busted 2.0.rc6-0`

If this problem is still going on for you, can you try to install it again, but this time pass the  --verbose flag and post the result.

**Comment by siffiejoe** [comment]
Maybe the LuaRocks version is just too old (before Moonrocks became the default rocks repository), and since the old luarocks.org site is gone now, the old download URL just doesn't work anymore ...

**Comment by daurnimator** [comment]
>  the old download URL just doesn't work anymore ...

It should. There is a redirect in place for old urls.

**Comment by siffiejoe** [comment]
```
siffiejoe@Merkur:~ :) wget http://www.luarocks.org/repositories/rocks
--2015-02-18 18:43:03--  http://www.luarocks.org/repositories/rocks
Auflösen des Hostnamen »www.luarocks.org (www.luarocks.org)«... 54.204.57.69
Verbindungsaufbau zu www.luarocks.org (www.luarocks.org)|54.204.57.69|:80... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 404 Not Found
2015-02-18 18:43:04 FEHLER 404: Not Found.
```

**Comment by daurnimator** [comment]
@siffiejoe try `luarocks.org/manifest`. The url you tried was just the UI.

**Comment by siffiejoe** [comment]
```
siffiejoe@Merkur:~ :) LANGUAGE=en_US.UTF-8 wget http://www.luarocks.org/repositories/rocks/manifest
--2015-02-18 18:55:09--  http://www.luarocks.org/repositories/rocks/manifest
Resolving www.luarocks.org (www.luarocks.org)... 54.204.57.69
Connecting to www.luarocks.org (www.luarocks.org)|54.204.57.69|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-02-18 18:55:10 ERROR 404: Not Found.
```

**Comment by ignacio** [comment]
It seems the redirect is working, but for http://luarocks.org/repositories/rocks/manifest  (without www).

**Comment by siffiejoe** [comment]
@ignacio Yep, that URL is working for me too.

**Comment by thefosk** [comment]
I'm using LuaRocks `2.1.2`.

**Comment by hishamhm** [comment]
Pinging @leafo — could you enable redirects of repository paths for both luarocks.org and www.luarocks.org in the website? Thanks!!

**Comment by hishamhm** [comment]
Submitted a pull request to support "www" explicitly in the server config.
