### ISSUE TITLE
"chmod: invalid mode" error when installing rocks

### ISSUE THREAD

**Issue by thefosk** [keplerproject/luarocks#314]
I'm experiencing the following error when installing rocks using luarocks `2.2.0`, Lua `5.1` on MacOSX.

```
Using https://rocks.moonscript.org/ansicolors-1.0.2-3.src.rock... switching to 'build' mode
stat: cannot read file system information for ‘%A’: No such file or directory
chmod: invalid mode: ‘  File: "ansicolors.lua"’
Try 'chmod --help' for more information.
stat: cannot read file system information for ‘%A’: No such file or directory
chmod: invalid mode: ‘  File: "COPYING"’
Try 'chmod --help' for more information.
stat: cannot read file system information for ‘%A’: No such file or directory
chmod: invalid mode: ‘  File: "README.textile"’
Try 'chmod --help' for more information.
stat: cannot read file system information for ‘%A’: No such file or directory
chmod: invalid mode: ‘  File: "/private/tmp/luarocks_ansicolors-1.0.2-3-3259/ansicolors-1.0.2-3.rockspec"’
Try 'chmod --help' for more information.
stat: cannot read file system information for ‘%A’: No such file or directory
chmod: invalid mode: ‘  File: "/usr/local/lib/luarocks/rocks/ansicolors/1.0.2-3/lua/ansicolors.lua"’
Try 'chmod --help' for more information.
Updating manifest for /usr/local/lib/luarocks/rocks
ansicolors 1.0.2-3 is now built and installed in /usr/local (license: MIT <http://opensource.org/licenses/MIT>)
```

**Comment by thefosk** [comment]
My co-workers are experiencing the same warnings - @hishamhm did you have any chance to take a look at this?

**Comment by hishamhm** [comment]
`stat` seems to be called with the wrong arguments... that's adjusted at `./configure` time, as these arguments vary according to the OS. How did you install LuaRocks, and what's the contents of your `luarocks/site_config.lua`?

**Comment by thefosk** [comment]
I've installed it by downloading the `luarocks-2.2.0.tar.gz` archive and executing:

```bash
./configure
make build
sudo make install
```

Regarding the conf, executing:

```bash
cat /usr/local/share/lua/5.1/luarocks/site_config.lua
```
returns
```lua
local site_config = {}
site_config.LUAROCKS_PREFIX=[[/usr/local]]
site_config.LUA_INCDIR=[[/usr/local/include]]
site_config.LUA_LIBDIR=[[/usr/local/lib]]
site_config.LUA_BINDIR=[[/usr/local/bin]]
site_config.LUAROCKS_SYSCONFDIR=[[/usr/local/etc/luarocks]]
site_config.LUAROCKS_ROCKS_TREE=[[/usr/local]]
site_config.LUAROCKS_ROCKS_SUBDIR=[[/lib/luarocks/rocks]]
site_config.LUAROCKS_UNAME_S=[[Darwin]]
site_config.LUAROCKS_UNAME_M=[[x86_64]]
site_config.LUAROCKS_DOWNLOADER=[[curl]]
site_config.LUAROCKS_MD5CHECKER=[[md5sum]]
return site_config
```

**Comment by hishamhm** [comment]
If you can reproduce the problem, please run luarocks with the `--verbose` flag and link the full output here, please (it'll probably be long, you might want to post a gist.github.com link)

**Comment by thefosk** [comment]
Here it is: https://gist.github.com/thefosk/f9426523c4bfca1ea49f

**Comment by hishamhm** [comment]
It's odd that lines like this:
```
stat -f '%A' 'README.textile'
```
are failing. What version of OSX are you using? Which version of `stat` is in your PATH? (what's the output of `which stat` — perhaps something else you installed clobbered the factory-default `stat` in the PATH?). If you take a look at `luarocks/cfg.lua` you'll see that we have different values of `defaults.variables.STATFLAG` for different OSes. `-f '%A'` is supposed to be the right incantation for OSX as far as I know...

**Comment by thefosk** [comment]
I'm using OS X Yosemite v10.10.2.

```shell
$ which stat
/usr/local/bin/stat
```

**Comment by daurnimator** [comment]
On 11 March 2015 at 20:57, Marco Palladino <notifications@github.com> wrote:

> I'm using OS X Yosemite v10.10.2.
>
> $ which stat
> /usr/local/bin/stat
>
>
The `local` suggests that you installed this yourself.
You should have a /usr/bin/stat ?

**Comment by thefosk** [comment]
Yes I do have `/usr/bin/stat`

**Comment by hishamhm** [comment]
Yes, all versions of `stat` seem to be incompatible with each other... 

The easy workaround for you is to put this in your `~/.luarocks/config.lua`:

```
variables = {
   STAT = "/usr/bin/stat"
}
```

Given that OSX is a somewhat predictable environment, I think we could set the defaults for these variables in OSX with their full paths. @daurnimator, what do you think? Do you have OSX handy to check what these paths should be?

**Comment by daurnimator** [comment]
> Yes I do have /usr/bin/stat - the problem may be some incompatibility with GNU coreutils on OS X.

Add `site_config.STAT=/usr/bin/stat` to your site config. Things should work for you then :)

**Comment by daurnimator** [comment]
> The easy workaround for you is to put this in your ~/.luarocks/config.lua:
> 
> variables = {
>    STAT = "/usr/bin/stat"
> }

I would suggest editing site_config rather than the local user's config. The extra `stat` is a computer-wide issue.


> Given that OSX is a somewhat predictable environment, I think we could set the defaults for these variables in OSX with their full paths.

Why do we use relative paths in the first place?



> @daurnimator, what do you think? Do you have OSX handy to check what these paths should be?

Not until tomorrow.

**Comment by daurnimator** [comment]
@hishamhm this isn't going to be an isolated case, I'm not sure why *everything* isn't a full path?

**Comment by hishamhm** [comment]
> Why do we use relative paths in the first place?

Because I assume the underlying system works and things are in all sorts of different places in UNIX. Relying on the $PATH has worked well so far, instead of building a huge database of every utility location in every Linux distro ever (and yes, they do vary more than one would think! /bin, /usr/bin, /sbin, /usr/sbin...).

I just committed a change to store the full path only on stat (which is known to have flag incompatibilities) and only on OSX (which is a single OS and not a family of distros, and thus a stable target).

**Comment by hishamhm** [comment]
We may make everything full paths on OSX.

**Comment by daurnimator** [comment]
> instead of building a huge database of every utility location in every Linux distro ever (and yes, they do vary more than one would think! /bin, /usr/bin, /sbin, /usr/sbin...).

At ./configure time we could `which stat` and check it is the correct one?

**Comment by hishamhm** [comment]
That's overengineering — this path leads to autotools "checking for <every single thing imaginable>...". Every OSX machine has BSD stat at /usr/bin/stat and every Linux stat is the one from GNU CoreUtils.
