### ISSUE TITLE
Patches failing doesn't result in luarocks failure

### ISSUE THREAD

**Issue by daurnimator** [keplerproject/luarocks#316]
if applying patches in luarocks fails, it is ignored and the build continues.
Please ensure you exit with a non-zero exit code.

**Comment by mpeterv** [comment]
Can't reproduce, for me when using `install` or `build` command patches are applied and when a patch fails, an error message is printed and exit code is not 0. However, it seems that patches are not applied by design when using `make` command (https://github.com/keplerproject/luarocks/blob/53e0c654af685b46a38548cca6d5df7bad30a7dc/src/luarocks/build.lua#L230-L235). Perhaps that could be changed?

**Comment by hishamhm** [comment]
> However, it seems that patches are not applied by design when using make command

This is by design. Patches are applied once when you run `luarocks unpack`. The idea of `luarocks make` is to assist in development, so you don't want it to apply patches over and over again when you're hacking at the code.

**Comment by daurnimator** [comment]
Hmmm, I may have been using `luarocks install http://mydomain/myfile-scm-0.rockspec`
Would that trigger it?

I remember seeing in the output that applying the patch failed; but luarocks just kept going.

**Comment by hishamhm** [comment]
`luarocks install`, when given a rockspec, redirects into `luarocks build`.

If you can reproduce it consistenly, please re-run with `--verbose` and send us the full output. Thanks!

**Comment by daurnimator** [comment]
> If you can reproduce it consistenly, please re-run with --verbose and send us the full output. Thanks!

I was configuring a new server when I ran into this issue; I ended up working around it.
However, while debugging, I did run with --verbose, and there was no interesting output around the patching. as patching happens in process I don't think there's much there?

**Comment by hishamhm** [comment]
I just wanted to know for sure that it was using the internal implementation of patch.

Turns out I just looked at the code and we're _always_ using the internal implementation, the apply_patch function in unix/tools.lua is dead code. I'm ripping it out now.

**Comment by hishamhm** [comment]
I found that the result wasn't being tested, but only in `unpack` (which explains @mpeterv not catching it in his tests). @daurnimator, maybe that's how you triggered it?

**Comment by daurnimator** [comment]
Maybe :p

I'll reopen if it occurs again.
