### ISSUE TITLE
My luarocks is (incorrectly?) diagnosed as out of date

### ISSUE THREAD

**Issue by rrthomas** [keplerproject/luarocks#317]
When I upload a rock, I get:

    $ luarocks-5.2 upload --force lrexlib-pcre-2.8.0-1.rockspec 
    /home/rrt/.local/etc/luarocks/upload_config.lua
    Sending lrexlib-pcre-2.8.0-1.rockspec ...
    Warning: Your LuaRocks is out of date, consider upgrading.

I am using luarocks 2.2.0, installed from source (not as a rock itself).

**Comment by rrthomas** [comment]
The server reports a version of `1.0.0` whereas luarocks 2.2.0's `tool_version` is `0.0.1` (and the same in current git), so the error is definitely OK, but there's nothing I can do!

**Comment by hishamhm** [comment]
Yes, please ignore this message for now. It's was a dissonance between the old `moonrocks` upload tool and its port into LuaRocks as the `luarocks upload` command. The version I ported identified itself as `0.0.1` but afterwards @leafo bumped it up to `1.0.0` and I missed that. We ended up not deciding then if we'll use this version to identify the actual LuaRocks version or the upload API version... I think I should at least bump the `tool_version` in Git to `1.0.0`.

**Comment by hishamhm** [comment]
No, wait, `tool_version` in git _is_ `1.0.0` already!
https://github.com/keplerproject/luarocks/commit/a35dd43752f0ee10d65c27200299176b29db45ef

**Comment by rrthomas** [comment]
Apologies, I was looking at the wrong source.
