### ISSUE TITLE
luarocks built with Lua 5.3 can't upload rocks

### ISSUE THREAD

**Issue by rrthomas** [keplerproject/luarocks#318]
My attempts to upload end:

    Sending /home/rrt/.local/var/repo/lrexlib/lrexlib-pcre-2.8.0-1.src.rock ...
    
    Error: API Failed: version_id must be an integer

This is with luarocks 2.2.0. Running an otherwise identical build but with lua 5.2, the upload works.

**Comment by hishamhm** [comment]
I believe this is fixed in the latest code from Git. Could you please verify? Thanks!

**Comment by rrthomas** [comment]
Installing git luarocks to use my setup is a bit complicated; I'm happy to take your word for it and/or leave this bug open until the next time I upgrade!

**Comment by hishamhm** [comment]
Closing this since the latest code was released. If the issue comes up again, please reopen! Thanks!

**Comment by rrthomas** [comment]
Thanks, just uploaded my first rock with Lua 5.3!
