### ISSUE TITLE
Allow version suffix on luarocks installed as a rock

### ISSUE THREAD

**Issue by rrthomas** [keplerproject/luarocks#323]
At present I have three parallel installations of LuaRocks, for Lua 5.[123], and configure it with --lua-suffix. This means I can install all three versions in the same tree, and more importantly, access them all with the same `PATH`.

I would like to install luarocks as a rock, but then it just installed "luarocks", and I could only install it like that for one Lua version.

(The same problem will apply to any other rock that installs things in `bin/`, but that's harder to fix without breaking dependencies when a program relies on the (unversioned) name of another.)

**Comment by hishamhm** [comment]
Question: did you end up with a file called `luarocks-` in your `bin/`?

**Comment by hishamhm** [comment]
Please try installing this:

```
luarocks install https://rocks.moonscript.org/manifests/hisham/luarocks-scm-2.rockspec
```

It should fix the issue. Let me know the results.

**Comment by rrthomas** [comment]
Looks good. Of course, if I want a particular version of Lua running the unversioned binaries, I have to remember to install it last, but that would require some explicit support for not installing unsuffixed executables.

Thanks very much!

**Comment by hishamhm** [comment]
Great, thanks!
