### ISSUE TITLE
Improve luarocks.org front page

### ISSUE THREAD

**Issue by rrthomas** [keplerproject/luarocks#324]
First, explain what it is in BIG LETTERS near the top of the page, like http://npmjs.org/

Secondly, change the "Download" link (download what? one may ask). Putting "Install" might be better; but "Install LuaRocks" is perhaps ambiguous. npmjs.org has a link with some explanation "beneath the fold". I suspect given their popularity they're a good model to follow if you don't have a better idea.

**Comment by hishamhm** [comment]
First of all, thanks for the feedback. 

The repository for the luarocks.org website is actually
https://github.com/leafo/moonrocks-site/
so perhaps it would be better to post this issue there.

**Comment by rrthomas** [comment]
Sorry, I had a vague feeling I wasn't doing the right thing when I posted.
