### ISSUE TITLE
more portable cmake build type support.

### ISSUE THREAD

**Issue by xpol** [keplerproject/luarocks#325]
Currently we use 

```Lua
fs.execute_string(rockspec.variables.CMAKE.." . " ..args
fs.execute_string(rockspec.variables.MAKE.." -fMakefile")
fs.execute_string(rockspec.variables.MAKE.." -fMakefile install")
```

Which use make to build the module.

But cmake have more portable way to build project:

```Bash
cmake -Bbuild -H.
cmake --build build --target install --config Release
```
This will let cmake to choose best generator and build it in a portable way.

This solution have follow advantages:

1. One command to build all platform (with cmake installed).
2. Better for windows, we don't need to run under MSVC command prompt

**Comment by xpol** [comment]
The cmake_generator = "MinGW Makefiles" for windows is not always work.

For me I have a luajit compiled with msvc.

I think when can pass it from command line like:

```
luarocks cmake -G "Visual Studio 12"
```

**Comment by xpol** [comment]
Tested the follow code almost work expect I don't know how to get the path where sould I install dlls and lua files:

```
   if not fs.execute_string(rockspec.variables.CMAKE.." -H. -Bluarocks.build") then
      return nil, "Failed cmake."
   end

   if not fs.execute_string(rockspec.variables.CMAKE.." --build luarocks.build --config Release") then
      return nil, "Failed building."
   end

   if not fs.execute_string(rockspec.variables.CMAKE.." --build luarocks.build --target install --config Release") then
      return nil, "Failed installing."
   end
   return true

```

**Comment by ignacio** [comment]
Do `variables.LUADIR` and `variables.LIBDIR` do what you want?

**Comment by ignacio** [comment]
Also, I think there are a few rocks that currently use the cmake build backend. Does this change affect that rocks? (Although I can't find them. @hishamhm how do you grep over the entire main repository?)

**Comment by siffiejoe** [comment]
@ignacio: Currently only

*  lua-http-parser-1.0-1.rockspec
*  lua-sdl2-2.0.3.3.1-1.rockspec
*  lua-sdl2-2.0.3.3-1.rockspec

from the main repository use the cmake backend. (I wrote a small Lua script that downloads all rockspecs referenced in a given manifest file.)

**Comment by hishamhm** [comment]
@xpol Passing the path where to install .dll and .lua files is up for the rockspec. I believe it depends on how the CMakefile is set up. See for example:

https://rocks.moonscript.org/manifests/tangent128/lua-sdl2-2.0.3.3.1-1.rockspec

Note that it uses `"$(PREFIX)"` and `"$(LUADIR)"` (the variables mentioned by @ignacio)

**Comment by hishamhm** [comment]
Just tested @xpol's patch on Linux with lua-sdl2; it worked well. Merged, thanks!

**Comment by ignacio** [comment]
@xpol I'm wondering about the -H flag. Is it necessary? It seems from [the docs](http://www.cmake.org/cmake/help/v3.1/manual/cmake.1.html) that it is shorthand for --help.

**Comment by xpol** [comment]
@hishamhm Thanks. I have read the doc [Creating-a-Makefile-that-plays-nice-with-LuaRocks](/keplerproject/luarocks/wiki/Creating-a-Makefile-that-plays-nice-with-LuaRocks) to find the answer.

I think it is necessary to create a wiki page *Creating-a-CMakeList-that-plays-nice-with-LuaRocks* .

@ignacio `-H` and `-B` are undocumented command line options. `-H` specify source directory and `-B` specify build directory. see [here](http://stackoverflow.com/questions/20610255/how-to-tell-cmake-where-to-put-build-files).

For luarocks it is not actually needed to have a separated build tree.
But it is necessary for lua module developers. (Say you may need to test your rocks via `luarocks make` without separated build tree you will have a lot of generated in your source tree root).

**Comment by ignacio** [comment]
Ok, I hope those options don't change in the near future :) It is strange that even in the latest CMake release they remain undocumented.

http://www.cmake.org/cmake/help/v3.2/manual/cmake.1.html
