### ISSUE TITLE
luars232 does not build

### ISSUE THREAD

**Issue by comotion** [keplerproject/luarocks#328]
Hello, 
the luars232 does not have a correct rockspec. I am reporting it here since "luarocks" is the owner for that rockspec. Upstream author doesn't know anything about the rock: https://github.com/ynezz/librs232/issues/21

sudo luarocks-5.1 install luars232
Installing https://rocks.moonscript.org/luars232-1.0.3-1.src.rock...
Using https://rocks.moonscript.org/luars232-1.0.3-1.src.rock... switching to 'build' mode
gcc -O2 -fPIC -I/usr/include/lua5.1 -c src/rs232.c -o src/rs232.o -DLUAROCKS_HACK -std=gnu99 -Iinclude
gcc -O2 -fPIC -I/usr/include/lua5.1 -c src/rs232_posix.c -o src/rs232_posix.o -DLUAROCKS_HACK -std=gnu99 -Iinclude
gcc -O2 -fPIC -I/usr/include/lua5.1 -c bindings/lua/luars232.c -o bindings/lua/luars232.o -DLUAROCKS_HACK -std=gnu99 -Iinclude
gcc -shared -o luars232.so -L/usr/lib src/rs232.o src/rs232_posix.o bindings/lua/luars232.o

Error: Directory 'invalid' not found

**Comment by ignacio** [comment]
Ok, will try to push an updated rockspec.

**Comment by ignacio** [comment]
Please try this one:

`luarocks install luars232 --server=https://rocks.moonscript.org/manifests/ignacio`

If it works, @leafo, can [this rockspec](http://rocks.moonscript.org/modules/ignacio/luars232/1.0.3-3) be added to the root manifest? I wouldn't want to claim ownership, since I've never used it.

**Comment by comotion** [comment]
yes @ignacio, that works. note the software is 5.1 only at the moment

**Comment by ignacio** [comment]
Thanks. I guessed so and set a dependency on Lua 5.1 in the rockspec.

**Comment by leafo** [comment]
Alright, updated it: http://rocks.moonscript.org/modules/luarocks/luars232

**Comment by ignacio** [comment]
Thanks!

**Comment by comotion** [comment]
this has gotta be by far the fastest I have seen an issue fixed ever :dart:
