### ISSUE TITLE
Git porject with submodules not supported by luarocks.

### ISSUE THREAD

**Issue by xpol** [keplerproject/luarocks#334]
I'm trying to add luarocks support for [luvit/luv](/luvit/luv) porject.

But luv currently use git submodules which not supported by luarocks.

I know it can be fixed by switching submodules to subtree or just fixe it via the build command in rockspec. But it would be nice to have git submodules support in luarocks server.

**Comment by creationix** [comment]
I tried to manually create a .src.rock file containing the required files (including the one submodule needed) and deleted and re-uploaded my rockspec along with it.  But when I tested the install it did a non-recursive clone and ignored the zip I uploaded.

**Comment by hishamhm** [comment]
@creationix Did you upload via the web interface or via `luarocks upload`? Do you still have the .src.rock file you crafted? Could you send it to me for testing? Thanks!

**Comment by creationix** [comment]
I used the web interface.  I did get a report a day later showing that my new upload did eventually take effect, so I think the server was just caching the old version even though I deleted it and re-uploaded a modified version.

I don't have the same .src.rock file, sorry.  But it would look like a zip version of https://github.com/luvit/luv/releases/download/1.4.2-2/luv-1.4.2-2.tar.gz more or less.

**Comment by vsergeev** [comment]
:+1: for submodule support.

This has come up [twice](https://github.com/keplerproject/luarocks/issues/169), [before](https://github.com/keplerproject/luarocks/issues/106). I've had to resort to crazy things like [cloning the submodule in the build command](https://github.com/vsergeev/lua-periphery/blob/ecbdef132e88aba30b5e26d6dfea04b188cd418a/lua-periphery-1.0.2-1.rockspec#L21), or [cloning it in the Makefile](https://github.com/vsergeev/lua-periphery/blob/9f1b3a526bf849eddeded6853b3f8e1af4c06f69/Makefile#L46) to work around LuaRock's lack of support for git recursive clone. And then this can break other things [downstream](https://github.com/vsergeev/lua-periphery/issues/5).

If someone could add a `git_recursive` fetch back-end to LuaRocks, that in turn could be specified as a rockspec dependency (for backwards compatibility) -- as originally suggested [here](https://github.com/keplerproject/luarocks/issues/169#issuecomment-27023620) -- we could solve this issue without any harm to LuaRocks. Not sure if it would have to be differentiated further for HTTP and HTTPS support.

**Comment by siffiejoe** [comment]
[Here you go][1]. I haven't tested with older LuaRocks versions (although it seems that at least LuaRocks 2.0.2 already has all required API functions -- that's as far as the GitHub history goes). I haven't put the module in the LuaRocks repository yet, so you'll have to download the rockspec manually and install from there. To use it you put a "gitrec://" `source.url` in your rockspec. Tell me how it goes. If it works for you as well, I'll upload it to LuaRocks.org.

  [1]: https://github.com/siffiejoe/luarocks-fetch-gitrec

**Comment by vsergeev** [comment]
@siffiejoe: the `gitrec` fetcher works great with LuaRocks 2.2.0. Please do package it and add it to LuaRocks. I will switch to it immediately.

**Comment by siffiejoe** [comment]
I have uploaded it to the LuaRocks repository. The latest version now also supports some additional pseudo URL schemes like `gitrec+http://...`, `gitrec+https://...`, `gitrec+file://...`, and `gitrec+ssh://...`.

**Comment by vsergeev** [comment]
Thanks siffiejoe! @ChangeTip, please pass @siffiejoe a donut.

This works for me and probably for most under regular usage (e.g. `luarocks install ...`), but I've noticed that `luarocks pack` will not fetch dependencies ahead of time, which in this case, it may need to actually fetch the package you'd like to pack. That may be somewhat of a corner case, depending on what you think the role of pack should be.

**Comment by changetip** [comment]
Hi @siffiejoe, @vsergeev sent you a Bitcoin tip worth a donut (1,517 bits/$0.35), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/849481)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by mpeterv** [comment]
Git submodule support was added on luarocks-3 branch in #396.
