### ISSUE TITLE
Support for configuring proxy via environment variable

### ISSUE THREAD

**Issue by hallison** [keplerproject/luarocks#337]
After install luarocks, the command `luarocks search lustache` not work. There is a proxy configuration in the network and the variables `http_proxy`, `ftp_proxy`, `socks_proxy`, `all_proxy` and `no_proxy` are configured in my environment.

I read the source code and I saw that the source `src/luarocks/fs/lua.lua` do not refer to any thing about the environment variables.

**Comment by ignacio** [comment]
Ok, so... in 'tools.use_downloader' I can add the required parameters for wget and curl.
Should I test for those variables or should the user specify the proxy in its config.lua file?

btw, the flags needed for wget seems to be:
-e "use_proxy=on" -e "https_proxy=https://127.0.0.1:8888"

**Comment by hallison** [comment]
When I set `proxy = "http://myproxy.local:3128"` in `~/.luarocks/config.lua`, everything works. But not works using environment variables. So, I think would be better run tests using variables.

**Comment by ignacio** [comment]
Unless that I'm mistaken, LuaSec does not support proxies.

So, should I give preference to those variables over cfg.proxy?

**Comment by hishamhm** [comment]
@ignacio _if_ we are to support env vars for this, we need to assess what's the situation wrt these variables and standards. I don't want the code to contain a mess trying every possible env var under the sun.

If there's no support in LuaSec, then a user needing it should use `fs_use_modules = false` in the config.lua file to force usage of wget or curl (which support proxies and (probably) env vars)

**Comment by ignacio** [comment]
Sure. Let's wait for that twitter survey result :) In the meantime, here is a wip branch, so you can assess if things are getting messy or not.

https://github.com/ignacio/luarocks/commit/308db7de56ead85ff58ccd5407dcff415ac0ce92

**Comment by hishamhm** [comment]
@ignacio I thought the environment var would be used only when using LuaSocket directly to handle network operations. `man wget` and `man curl` tell me that both of them already recognize these environment vars by themselves, there's no need to add code on our side to forward them explicitly as flags.

**Comment by ignacio** [comment]
Erm... yes, you're right. But @hallison did have these env vars defined and they weren't being picked up. Now that I think of it, it setting "proxy" in config.lua fixed things for him, it surely had LuaSocket installed, and LR was using it, right?

**Comment by hishamhm** [comment]
yes.

**Comment by ignacio** [comment]
Ok, so the use case is this:
- User is in an evironment were proxy is required. Has environment variables properly configured.
- User installs LuaRocks
- Installs some modules ok, they go through the proxy.
- Then installs luasocket and luasec
- After that, everything breaks.

At this point, adding `proxy` in _config.lua_ is needed. But, adding it would only make LuaSec fail, until a mirror like luafr.org or logiceditor.com is used. In these cases, LuaSocket is used, so it picks up the _proxy_ setting and everything works again, except you're inadvertently using an insecure repository (maybe "insecure" is not the correct word, I mean it is a repo server over http).
A possible improvement right there is to make `fs_lua.download` not even attempt to use LuaSec when a proxy is configured, so we fallback to either wget or curl.

So, what is left is to make LuaSocket use the `http_proxy` env var.

Implementing `no_proxy` is more work. In this case, I would go straight to wget or curl and don't bother of implementing that logic in Lua.

I would drop the use of 'proxy' in _config.lua_

See current status at: https://github.com/ignacio/luarocks/commit/f022fe08167e67ae854120d472d273bed47ff3ff

**Comment by hishamhm** [comment]
Excellent assessment of the situation!

> See current status at: ignacio@f022fe0

If I'm reading correctly, you basically did everything that has to be done to fix the proxy situation in four lines? Fantastic!

**Comment by ignacio** [comment]
Well, thank you :)

Now I tested forcing all traffic through the proxy and everything I tested is working.
And _no_proxy_ is handled by delegating directly to the configured downloader, just a couple more lines...

Current status at: https://github.com/ignacio/luarocks/commit/2c536b4bdd07b6f8983876a01296a1e8c752d2be

Do you want to add some sort of message when downloading stating that a proxy is being used?

**Comment by hallison** [comment]
I thought apply the same solution, but I don't understand how the tests work to simulate the problem. :D

**Comment by ignacio** [comment]
Currently, I think they don't, because I don't know how to set a proxy on Linux, route some requests through it and *assert* that effectively the requests went through the proxy.

**Comment by hallison** [comment]
To set proxy variable, just add the follow instructions in `/etc/environment` to use PAM.

```
http_proxy=http://proxy.server:3128
https_proxy=http://proxy.server:3128
ftp_proxy=http://proxy.server:3128
all_proxy=http://proxy.server:3128
no_proxy=localhost,127.0.0.1
```

Personaly, I set configurations in `/etc/profile.d/proxy.sh`

**Comment by ignacio** [comment]
@hishamhm do you want me to submit a PR with this?

**Comment by hishamhm** [comment]
oh, I completely forgot about that. I thought you solution was merged already :)

**Comment by earonesty** [comment]
i had to use this method (insteadOf, gitconfig) to get it to work: otherwise luarocks woudl use the git:// method and fail: https://github.com/neovim/neovim/issues/1830
