### ISSUE TITLE
Automatically setup VS command line tools.

### ISSUE THREAD

**Issue by xpol** [keplerproject/luarocks#344]
I wan't add feature that automatically setup VS command line tools when build modules.

Currently I can find that `variables.MSVCRT` in `config.lua` which contains VS version information. But it does not provide ARCH (32/64 bit) information.

If both `MSVCRT` and `ARCH` are available, It is possible to automatically setup VS command line tools. So we can build rocks without VS  Command Prompt.

**Comment by xpol** [comment]
I was naive.

I find that `os.execute("call ...\\VC\\vcvarsall.bat")` will run in another process.
Which can't affect current Command Prompt.

Is there any solutions?

**Comment by Tieske** [comment]
Win7 SDK comes with a `setenv.cmd` file that is used to setup the environment, but I've never been able to use that file outside of the SDK commandshell. It just keeps giving me all sorts of errors. So I gave up on it. (I found that batchfile too complex to debug).

**Comment by ignacio** [comment]
@xpol the only way I know of doing what you want is to use `io.popen` instead of execute, adding a call to "set", like this: `foo.bat && set` and parse the output, which is ugly and error prone.

**Comment by xpol** [comment]
I have got a new idea:

1. Detect `vcvarsall.bat` path during install (as we already have `vars.LUA_RUNTIME` we can  get version MSVCR120=>12.0 and [search windows Registry](https://stackoverflow.com/questions/30504/programmatically-retrieve-visual-studio-install-directory) .).
2. add a new line  `call "C:\path\to\vcvarsall.bat" x86` in `luarocks.bat` right after line 2 `SETLOCAL`.

I just tested this works. as there is a `SETLOCAL` after `luarocks` command, the vc path will not affect the latter commands.

**Comment by ignacio** [comment]
It would be a matter of adding this to the install scripts and test with different Visual Studio versions. That can be done with our tests in appveyor.

**Comment by xpol** [comment]
I have worked on a pull request, hold on.

**Comment by ignacio** [comment]
Closed by #462
