### ISSUE TITLE
Bug: attempt to index local 'typetbl'

### ISSUE THREAD

**Issue by thefosk** [keplerproject/luarocks#347]
Executing:
```lua
local search = require "luarocks.search"
search.manifest_search({}, "/usr/local/lib/luarocks/rocks", { constraints = {}, name = "something"})
```
throws:
```shell
lua: /usr/local/share/lua/5.1/luarocks/type_check.lua:173: attempt to index local 'typetbl' (a number value)
stack traceback:
	/usr/local/share/lua/5.1/luarocks/type_check.lua:173: in function 'check_version'
	/usr/local/share/lua/5.1/luarocks/type_check.lua:201: in function 'type_check_item'
	/usr/local/share/lua/5.1/luarocks/type_check.lua:276: in function </usr/local/share/lua/5.1/luarocks/type_check.lua:263>
	(tail call): ?
	/usr/local/share/lua/5.1/luarocks/type_check.lua:276: in function </usr/local/share/lua/5.1/luarocks/type_check.lua:263>
	(tail call): ?
	/usr/local/share/lua/5.1/luarocks/type_check.lua:276: in function </usr/local/share/lua/5.1/luarocks/type_check.lua:263>
	(tail call): ?
	/usr/local/share/lua/5.1/luarocks/type_check.lua:276: in function </usr/local/share/lua/5.1/luarocks/type_check.lua:263>
	(tail call): ?
	...
	/usr/local/share/lua/5.1/luarocks/manif_core.lua:28: in function </usr/local/share/lua/5.1/luarocks/manif_core.lua:21>
	(tail call): ?
	/usr/local/share/lua/5.1/luarocks/search.lua:175: in function 'manifest_search'
```

Luarocks 2.2.1, Lua 5.1.5, OS X 10.10.3

**Comment by ignacio** [comment]
manifest_search only works on repositories and not on local trees.

The docs of that function states: `--- Perform search on a rocks server.

**Comment by hishamhm** [comment]
LuaRocks does not have a public API. All modules are for its internal use; the supported interface is the command-line. Crashes due to misusing LuaRocks internals are expected and are not considered bugs.

**Comment by thefosk** [comment]
Although I understand you didn't plan the modules for external use, the fact that an unexpected value can make his way through the system makes the system itself fragile and could possibly lead to bugs, so I think it's worth considering fixing it.

In this line for example: https://github.com/keplerproject/luarocks/blob/master/src/luarocks/type_check.lua#L276

the `v` value has the following values:

```
table: 0x7fe7924626b0
table: 0x7fe79246c380
table: 0x7fe79246c3f0
table: 0x7fe792472560
lua
table: 0x7fe7924725f0
table: 0x7fe792472630
table: 0x7fe7924726c0
5
```
Sometimes it represent a table, sometimes a string and sometimes a number. The `v` value is being passed in the `type_check_item` function as a `typetbl` argument that expects a `table` instead https://github.com/keplerproject/luarocks/blob/master/src/luarocks/type_check.lua#L173

In another comment you explicitly mention that `typetbl` should be a `table`: https://github.com/keplerproject/luarocks/blob/master/src/luarocks/type_check.lua#L192

which is not always the case and could lead to bugs.

**Comment by ignacio** [comment]
I found [a message](http://sourceforge.net/p/luarocks/mailman/message/33622299/) on the mailing list reporting an error (a while ago) and it seems that there is a real bug here, triggered from the command line.

I reduced the test case to:
~~~~
tar xf luarocks-2.2.1.tar.gz
cd luarocks-2.2.1/
./configure --prefix=/tmp/luarocks
make build
make install
luarocks --tree=/tmp/rocktree install luafilesystem
luarocks --tree=/tmp/rocktree list
~~~~

I don't understand why `list.run` is using `search.manifest_search`, which the docs say it is used to work with remote repositories. Here we're dealing with local repositories and afaik the manifest format is different.

**Comment by hishamhm** [comment]
@ignacio, thanks for spotting it and isolating the test case!

**Comment by ignacio** [comment]
Great. Shouldn't the docs of search.manifest-search be updated too?

**Comment by ignacio** [comment]
Thanks

**Comment by thefosk** [comment]
@ignacio it works now, thanks
