### ISSUE TITLE
FreeBSD and io.popen

### ISSUE THREAD

**Issue by GorgonzolaPasta** [keplerproject/luarocks#348]
Hi, I use FreeBSD and io.popen() is not supported. What can I do?
I installed a new Version of luarocks for lua53 and now:
```
[pasta@x230][pts/1]~: luarocks-5.3 --version
Your version of Lua does not support io.popen,
which is required by LuaRocks. Please check your Lua installation.
```
```
[pasta@x230][pts/1]~: lua53 -v
Lua 5.3.0  Copyright (C) 1994-2015 Lua.org, PUC-Rio
```
```
[pasta@x230][pts/1]~: uname -a
FreeBSD x230 10.1-RELEASE-p6 FreeBSD 10.1-RELEASE-p6 #0: Tue Feb 24 19:00:21 UTC 2015     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

**Comment by siffiejoe** [comment]
You only get a working `io.popen` if you compile Lua with `-DLUA_USE_POSIX`. The `make` target for FreeBSD (`make freebsd`) includes this define (or rather `LUA_USE_LINUX` which implies `LUA_USE_POSIX`), so I guess you (or someone else) picked the `generic` (or `c89`) target instead, which only uses ISO C features.

**Comment by hishamhm** [comment]
As this is a local configuration issue, closing it.
