### ISSUE TITLE
Rename main program from luarocks to only rock

### ISSUE THREAD

**Issue by hallison** [keplerproject/luarocks#353]
I know that is a not significant feature. But in the Python community there is the Python Package Index and the command line is `pip`; in the Ruby community there is the Rubygems and the command line is `gem`. It is possible that our command line it may be simply `rock`?

Thanks.
---

Meu inglês não é muito bom... `:)`

Eu sei que não é uma funcionalidade significante. Mas na comunidade Python, há o _Python Package Index_ e a linha de comando é `pip`; na comunidade Ruby, há o _Rubygems_ e a linha de comando é `gem`. É possível que a nossa linha de comando seja apenas `rock`?

Obrigado.

**Comment by mpeterv** [comment]
I doubt luarocks is going to change cli name like that. That would break a lot of scripts. Using an alias works just as well (I think I used "lrx" at some point, even shorter than "rock" :smile:)
