### ISSUE TITLE
Asking the --rocks-tree flag to set the user, and not system, rocks tree.

### ISSUE THREAD

**Issue by alexbw** [keplerproject/luarocks#356]
Is it possible to have the `--rocks-tree` flag set the user, and not the system, rocks tree? 

I am building a local-only distribution of lua for scientific computing. In scientific computing clusters, the user never has superuser permissions. I'm not sure if it really matters, as long as the rocks tree is in a user-accessible directory, but it seems "nicer" if we call a non-root folder location a "user" rocks tree, as opposed to a "system" rocks tree.

**Comment by hishamhm** [comment]
You mean `--local`?

You can also put `local_by_default=true` in the ~/.luarocks/config.lua file and this flag will be assumed by default.

**Comment by alexbw** [comment]
./configure --local doesn't work, not a supported flag.

I'm a newbie to this project, so is there somewhere where I can read up on
this? I've been crawling the wiki for now.

**Comment by siffiejoe** [comment]
The `--local` flag is for *running* LuaRocks. If you need a fancy `./configure` incantation for *installing* LuaRocks, here is what I use (on Ubuntu Linux):

```
./configure --prefix=/home/siffiejoe/.self/programs/luarocks-2.2.1/ --lua-version=5.1 --lua-suffix=5.1 --versioned-rocks-dir --force-config
make bootstrap
```

**Comment by Tieske** [comment]
@alexbw did @siffiejoe answer your question? can we close this?

**Comment by alexbw** [comment]
Yes, thanks.
