### ISSUE TITLE
`luarocks upload` command is broken after domain change

### ISSUE THREAD

**Issue by ignacio** [keplerproject/luarocks#357]
I've just created [this issue](https://github.com/leafo/luarocks-site/issues/50) in _luarocks-site_ repo but I think that the upload api should deal with redirects, which at present it does not.

It uses LuaSec unconditionally (if installed) which does not support redirects (although there is a fix by @Tieske in the pipeline).
Disabling luasec makes it fallback to curl, but it fails at a different stage of the upload (with `Error: API Failed: Missing file`)

**Comment by hishamhm** [comment]
This is fixed by now, right?

**Comment by ignacio** [comment]
Well, yes and no.
rocks.moonscript.org isn't redirecting anymore, so the upload issue went away. But if for any circumstance, the redirect needs to be applied, this issue will still bite us.

**Comment by leafo** [comment]
This can be closed now

**Comment by peterbillam** [comment]
Well it, or something apparently identical, came back and bit me:    
luarocks upload http://www.pjb.com.au/comp/lua/ao-1.2.0-0.rockspec    
. . . all the files get added fine . . .   
     adding: lao/Makefile (deflated 33%)    
Error: API failure: /upload    
    
luarocks --version
/usr/local/bin/luarocks 2.4.3

Am I doing something wrong ?

**Comment by daurnimator** [comment]
@peterbillam I don't think your issue is related to this one.
When creating a new issue, please post the output with `--verbose`.
