### ISSUE TITLE
api key is not redacted when using --verbose flag

### ISSUE THREAD

**Issue by ignacio** [keplerproject/luarocks#358]
Since the advise upon reporting problems usually is to provide a log of the failing command with --verbose, people could inadvertently hand out their keys. 

This could be implemented in https://github.com/keplerproject/luarocks/blob/master/src/luarocks/fs.lua#L34 by pattern matching `cmd` against `/api/{version}/{key}/blablabla` or something.

**Comment by hishamhm** [comment]
That would work. I'd simply match "/api/[^/]+/[^/]+/"

**Comment by ignacio** [comment]
Now it outputs: 
~~~~
os.execute:     D: & cd "D:\trunk_git\sources\nozzle" & "curl" -f -k -L --silent --user-agent "LuaRocks/scm win32-x86 via curl" --form "rockspec_file=@rockspecs
\nozzle-git-1.rockspec" --connect-timeout 30 "https://luarocks.org/api/1/<redacted>/upload" -o "C:\Users\Ignacio\AppData\Local\Temp\savg.2"     1
Results: 1
  1 (number): 0
~~~~

So I think I'll just merge this in a couple hours.

**Comment by hishamhm** [comment]
cool!

**Comment by Tieske** [comment]
Good catch!
