### ISSUE TITLE
Unable to install LuaRocks using brew on OSX

### ISSUE THREAD

**Issue by britzl** [keplerproject/luarocks#363]
The instructions (https://github.com/keplerproject/luarocks/wiki/Installation-instructions-for-Mac-OS-X) clearly state that it should be possible to install LuaRocks using brew, but I get "Error: No available formula for luarocks":

$ brew update
Already up-to-date.

$ brew install luarocks
Error: No available formula for luarocks 
Searching formulae...
Searching taps...

Is the documentation outdated or is this an issue that needs to be solved?

**Comment by daurnimator** [comment]
brew now installs luarocks along with lua.

**Comment by bobrik** [comment]
It is `luarocks-5.2` or `luarocks-5.1` depending on what version of lua you have installed.

**Comment by Xalior** [comment]
At this moment in time, by default, ```brew install lua``` gets you ```lua-3.2``` and ```luarocks-5.2```

**Comment by rrthomas** [comment]
This issue can be closed: it's working fine now. (I had cause recently to try it!)
