### ISSUE TITLE
build.build_command is executed 17 times

### ISSUE THREAD

**Issue by deathbeam** [keplerproject/luarocks#364]
When I try to run custom `build.build_command` or `build.install_command`, LuaRocks will execute my script 17 times. I tested this on both 32 bit Windows 8 and 32bit latest Ubuntu version. Here is my RockSpec:

```lua
package = "non"
version = "dev-1"

source = {
  url = "git://github.com/non2d/non.git",
}

dependencies = {
  "lua >= 5.1",
  "moonscript"
}

build = {
  type = "command",
  
  modules = {
    ["non"] = "bin/non.lua"
  },
  
  install = {
    bin = { "bin/non.jar", "bin/non" }
  },
  
  platforms = {
    unix = {
      build_command = "sh install"
    },
    windows = {
      build_command = "call install"
    }
  }
}
```

As my last attempt I changed `luarocks/fs/win32/tools.lua` function execute_string to this to show debug output:
```lua
local i = 1
function tools.execute_string(cmd)
   cmd = command_at(fs.current_dir(), cmd)
   local code = os.execute(cmd)
   print(i)
   i = i + 1
   if code == 0 or code == true then
      return true
   else
      return false
   end
end
```

And here is result from console on Windows:
```batch
executing: luarocks make "C:\Users\Tomas\Documents\GitHub\non\non-dev-1.rockspec"
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
call install
```

**Comment by mpeterv** [comment]
Can you run luarocks with --verbose option to see which 17 commands are executed? I can't reproduce this on my 32-bit Ubuntu, a few auxiliary commands are run but the build_command is only used once.

**Comment by deathbeam** [comment]
I resolved this after some try and fails. I simply called another "luarocks make" from install script and that created endless loop. Closing this issue.
