### ISSUE TITLE
Luarocks.bat does not propagate error level

### ISSUE THREAD

**Issue by stepelu** [keplerproject/luarocks#365]
As per title, `luarocks.bat` always has an exit code of `0`.
To fix, just append `exit /b %ERRORLEVEL%` at the end of the batch file.

**Comment by siffiejoe** [comment]
Also applies to `fs.wrap_script` ...

**Comment by Tieske** [comment]
Note: if UAC is enabled, then the luarocks command will try to auto-elevate priviledges and request admin access. In that case, even if it is executed successful (in the new prompt with admin rights) the main command (unpriviledged) will get an errorcode of `2`. (I don't think this can be resolved)

Workaround would be to execute the luarocks command with admin rights, so the auto-elevation is skipped, and the correct exitcode is returned
