### ISSUE TITLE
Checks in fetch.load_local_rockspec

### ISSUE THREAD

**Issue by kosklain** [keplerproject/luarocks#369]
Even though the `source` field in the rockspecs is mandatory, there are some packages like http://luarocks.org/modules/creationix/luv/1.4.2-1 that do not include such field. 

At the same time, `fetch.load_local_rockspec` just parses the local rockspec, so I do not see why it should crash because of this reason. Adding a check there for the existence or `rockspec.source` would be useful for creating manifests of repositories that contain these rockspecs.

**Comment by hishamhm** [comment]
> Even though the source field in the rockspecs is mandatory, there are some packages like http://luarocks.org/modules/creationix/luv/1.4.2-1 that do not include such field. 

In this case, it's a bug in the rockspec, not in LuaRocks.

> At the same time, fetch.load_local_rockspec just parses the local rockspec, so I do not see why it should crash because of this reason.

Do you have a test case reproducing the crash?

**Comment by kosklain** [comment]
I agree that it is a bug in the rockspec (and what I propose is what I think a little useful detail to add, not something mandatory/urgent). However, `fetch.load_local_rockspec` does include some rockspec format checks, such as checking that the rockspec's filename is of the form 'name-version-revision.rockspec', or checking the format version of the rockspec. What I believe is that checking that it contains the mandatory fields is another reasonable check.

As a test case it would just be running `fetch.load_local_rockspec(filename)` where `filename` corresponds to the name of the rockspec that doesn't contain a 'source' field, such as the one I mentioned before. That fails just because on line 226 of fetch.lua (`local protocol, pathname = dir.split_url(rockspec.source.url)`) attempts to index 'rockspec.source', which is nil.

What I expected from `fetch.load_local_rockspec` is to return the parsed rockspec with 'whatever information it was able to find', that's why I think it should not crash due to a missing field.

**Comment by mpeterv** [comment]
This is long not true, load_local_rockspec typechecks the rockspecs and returns `nil, "Mandatory field source is missing."`.
