### ISSUE TITLE
I upload the rockspec and rock file, but can not install it with luarocks :(

### ISSUE THREAD

**Issue by starwing** [keplerproject/luarocks#370]
I have a module on luarocks.org, here: https://luarocks.org/modules/xavier-wang/lua-protobuf

I just found I cannot install it using luarocks install lua-protobuf

first I think it's the issue of "-", but I tried luarocks install lua-cjson and it success!
then I upload a src.rock file, but still can not find package.

**Comment by daurnimator** [comment]
Your rockspec is a 'dev' rockspec. (this is autodetected from the name of
'scm')
They are not placed into the main manifest.

To have your package appear, you need to make a release!

**Comment by starwing** [comment]
Sorry about that :(

After make a release, my rocks can be downloaded!

I need make many release about my modules T-T So sad

**Comment by daurnimator** [comment]
> I need make many release about my modules T-T So sad

When you make a release, make sure you update the `source` to point at something stable (e.g. a git tag). Your rockspec at https://luarocks.org/manifests/xavier-wang/lua-protobuf-0.1.0-1.rockspec is still following git HEAD.

**Comment by starwing** [comment]
Then, how can I make a release to make others always get the latest version of code? i.e. directly download from github head.

(I just hear about this after I uploaded a couples of modules :(

**Comment by daurnimator** [comment]
> Then, how can I make a release to make others always get the latest version of code? i.e. directly download from github head.

you're not meant to. (alternatively: this is what a development rock is for)

When a user installs a particular version of your module, or writes software that uses it as a lib, they do not expect it to change out from underneath them.

**Comment by starwing** [comment]
Okay, I know it, I will make tags and upload new modules later, Thank you :)
