### ISSUE TITLE
upload api-key lost after upgrade

### ISSUE THREAD

**Issue by Tieske** [keplerproject/luarocks#374]
Just updated LR to the latest master, but when uploading the api-key was requested again.

Where is the api key located, and is this expected? or does it need a fix?

**Comment by ignacio** [comment]
Look for a file called `upload_config.lua` in your home.

**Comment by ignacio** [comment]
Mmm, seems to me that it is indeed broken.

[This commit](https://github.com/keplerproject/luarocks/commit/4462ca51ee10363916c29c071942c15f424913e6) changed the return value of `which_config`

So this line always fail:
https://github.com/keplerproject/luarocks/blob/master/src/luarocks/upload/api.lua#L13

Seems easy to fix, though.

**Comment by hishamhm** [comment]
Sorry, I thought I had pushed this!
