### ISSUE TITLE
'.' in repository names confuses builtin build backend

### ISSUE THREAD

**Issue by siffiejoe** [keplerproject/luarocks#375]
If I modify the compat52 rockspec to use the URL `git+file:///home/siffiejoe/src/github/lua-compat-5.2/`, the build step fails:

> cp: cannot stat ‘compat52/mstrict.lua’: No such file or directory
> 
> Error: Build error: Failed installing compat52/mstrict.lua in /home/siffiejoe/.self/programs/luarocks/lib/luarocks/rocks-5.1/compat52/scm-6/lua/compat52/mstrict.lua

If however I create a symbolic link (`ln -s lua-compat-5.2 lua-compat-52`) and use the URL `git+file:///home/siffiejoe/src/github/lua-compat-52`, the installation is successful.

This also happens with the `git://...` protocol when using the URL `git://github.com/hishamhm/lua-compat-5.2`, but `git://github.com/hishamhm/lua-compat-5.2.git` works fine. Repositories without dots in them work both ways. (This workaround doesn't work for the file URLs though.)

I've not yet figured out where exactly the problem is, but it seems that the pseudo-cwd is wrong:
It's `/tmp/luarocks_compat52-scm-6-9032` when it should be `/tmp/luarocks_compat52-scm-6-9032/lua-compat-5.2`.

I'll keep investigating ...

**Comment by siffiejoe** [comment]
Apparently `rockspec.source.dir` contains `lua-compat-5` (without the trailing `.2`), which does not exist.

**Comment by siffiejoe** [comment]
Found it: The function `fetch.url_to_base_dir` is a bit too aggressive when removing file name suffixes. The issue can be avoided by explicitly setting `source.dir` in the rockspec.

**Comment by ignacio** [comment]
@siffiejoe Do you think that `fetch.url_to_base_dir` can be fixed?

**Comment by siffiejoe** [comment]
I think you could add some heuristics (e.g. ".zip" is a file name extension and should be stripped, ".git" is not), but this is fragile. I'd make the `fetch.url_to_base_dir` function return an array of possible candidates with various amounts of suffixes stripped, which can be tried in order if no explicit `source.dir` is given.

**Comment by ignacio** [comment]
Thanks.

**Comment by mpeterv** [comment]
Is source.dir ever used when an unpacked archive is not available already?

**Comment by hishamhm** [comment]
> I think you could add some heuristics (e.g. ".zip" is a file name extension and should be stripped, ".git" is not), but this is fragile. 

".git" should be stripped, too. 

> I'd make the fetch.url_to_base_dir function return an array of possible candidates with various amounts of suffixes stripped, which can be tried in order if no explicit source.dir is given.

I agree the above is not bulletproof, but complicating the code with an array of candidates due to a fringe case is not worth it IMO. There is a limited set of filename extensions that we support unpacking (`.tar.gz`, `.tgz`, `.tar.bz2`, `.zip`), plus git-cloning something with `.git` results in a directory with that extension stripped. Let's just strip those 5 extensions, then.

**Comment by ignacio** [comment]
Do mercurial repositories need a trick similar to git ones (stripping .git from url in some cases) ?
I read about the `hg://` protocol but couldn't find any url to try.

**Comment by ignacio** [comment]
PR #404 should address this issue. Still know nothing about that hg:// thing.

**Comment by ignacio** [comment]
fixed by commit 634ff0af63a250859863cee25b8ab21e2404a267
