### ISSUE TITLE
install a rock in developer mode

### ISSUE THREAD

**Issue by Djabbz** [keplerproject/luarocks#378]
Hi Folks,

Is it possible to install a rock in "dev mode", ie., only linking to the source files so that changes are immediately reflected in the installed library?

Cheers,

**Comment by ignacio** [comment]
Yes, look at `luarocks make` command.

**Comment by Djabbz** [comment]
That's in fact what I'm doing but it's apparently putting the .rockspec in the lib/ folder without linking anything.

**Comment by ignacio** [comment]
Ah, now I see what you really want. No, sorry, you can't do that.
When I'm developing and need to test changes in the code, I just prepend my code location to either `package.path` or `package.cpath`, so when I call _require_, the version of the rock I'm working on takes precedence.

**Comment by Djabbz** [comment]
OK, thanks!
