### ISSUE TITLE
What's the version of rockspec mean??

### ISSUE THREAD

**Issue by starwing** [keplerproject/luarocks#380]
I just make a new release for my luautf8 module, but I'm confusing with the version definition of luarocks.

the previous version was 0.1.0-1, when I use luarock new_version, it generate a 0.1.0-2 version for me. and I edit this rockspec, and make a release on github, and upload it to luarocks.org, so what? I just can not find this version!

I noticed moonscript always use 0.x.y-1 version, but why luarock new_version do not increment patch number, but +1 to "-1" componment? what's the -1 mean??

then I tried luautf8-0.1.1.rockspec, but it failed! luarocks tell me the version must have a -%d componment, but why?

**Comment by Tieske** [comment]
in case `0.1.0-1` then `0.1.0` is your module version, and `1` is the rockspec version.

So you make changes to your code, and name it release `0.2.0` then you get rockspec `0.2.0-1`. Now for some reason, there is an error with the rockspec, a missing dependency that makes it fail when building. Then you update the rockspec and name is `0.2.0-2`. So same code version, but new rockspec version.

hth

**Comment by hishamhm** [comment]
To further clarify, to avoid confusion we call 0.1.0 the module _version_
and -1 the rockspec _revision_.

If you release new code, always change the module version.

If you changed the rockspec but did not change the code, increment the
revision number.

**Comment by starwing** [comment]
Okay, I see. Thank you very much for detailed explain :)
