### ISSUE TITLE
How to determine the current version?

### ISSUE THREAD

**Issue by ignacio** [keplerproject/luarocks#386]
I'm adding support for [lua-appveyor-example](https://github.com/ignacio/lua-appveyor-example) to be able to install the current HEAD of master.
The user would be able to test her modules with the latest LR version just by setting `LUAROCKS_VER = HEAD`.

The thing is that I don't know which LuaRocks version I'm installing, so I can't know beforehand where it is going to be installed. It could be 2.2.2 (right now) or 2.3.0 (?), so I thought if it would be worthwile to have something like a VERSION file at the root, which holds the current version, in its long form (i.e 2.2.2).

Tools could just read that file. It could be used in `install.bat` instead of hardcoding the version. It could be used on luarocks.org site to update the installation instructions automatically.

What do you think?

**Comment by siffiejoe** [comment]
Does `git describe --tags --abbrev=0` help you in the meantime?

**Comment by ignacio** [comment]
Thanks @siffiejoe . Didn't know about that command. Although it seems that in the case of being in the middle of a transition (code belongs to 2.3.x, latest tag is 2.2.x) it will not work for me.
(I just hardcoded 2.2 for the time being).

**Comment by hishamhm** [comment]
Can you access the LuaRocks sources and run a Lua interpreter at that point? If so, this could do the trick:

```lua
cfg = require("luarocks.cfg")
print(cfg.program_series)
```

**Comment by ignacio** [comment]
Nope. This is before LR has been installed, so there is no `luarocks.site_config` file:

~~~~
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> require "luarocks.cfg"
Site-local luarocks/site_config.lua file not found. Incomplete installation?
.\luarocks\cfg.lua:313: attempt to concatenate field 'LUAROCKS_PREFIX' (a nil value)
~~~~

**Comment by hishamhm** [comment]
I just noted that this is inside `if detected.windows`... on Unix, luarocks.cfg doesn't crash if `site_config.lua` is missing (and in fact I often use it that way, when running LuaRocks directly off the development tree — that's why the "Incomplete installation?" is a warning and not a fatal error).

If you tweaked line 313 above to avoid crashing could you then use the two-liner above to obtain the program series?

**Comment by ignacio** [comment]
Does this sound right? 
~~~lua
-- Mimic `install.bat` behaviour 
local full_prefix = (site_config.LUAROCKS_PREFIX or (os.getenv("PROGRAMFILES")..[[\LuaRocks]])).."\\"..cfg.major_version
~~~~

**Comment by ignacio** [comment]
If people have no complains, I'd like to commit that change.

**Comment by hishamhm** [comment]
Fine for me, but I'm not the go-to person for Windows env vars :)

**Comment by ignacio** [comment]
Ok, I'll put that in, since it just mimics what the bat file is doing on Windows.
