### ISSUE TITLE
processor is incorrectly identified on Windows

### ISSUE THREAD

**Issue by Tieske** [keplerproject/luarocks#390]
See https://github.com/keplerproject/luarocks/pull/385#issuecomment-113232548 

A 64bit processor is not properly identified, but listed as x86 (meaning 32bit). See [this link](http://blogs.msdn.com/b/david.wang/archive/2006/03/26/howto-detect-process-bitness.aspx) for some info.

I suspect it has to to with the `uname` utility used by LR, being 32 bit. Hence Windows runs it in wow, which then reports 32bit (as a compatibility measure).

**Comment by Tieske** [comment]
So the `processor` variable available to the config file is supposed to be given the wrong output. But question is what was intended for that variable, and what is needed.

1. We cannot assume that the engine running LuaRocks is the same as the target engine (so bitness and runtimes used might differ)
1. detecting at runtime will deliver the wrong results for the actual processor, if 32bit is being ran on 64bit architecture. Due to the compatibility provided by the os.

So what is the `processor` variable supposed to tell us? to be worthwhile it should be either the actual processor type (independent of 32/64 bit compatibility layers), or the target binary format imo.

**Comment by Tieske** [comment]
Looked into it some more and found the following;

* the Windows installer detects target platform as well as target architecture, and writes those to the `site_config.lua` file.
* the `cfg` module loads the `site_config.lua` file and uses those values (fallback if not provided is `uname`)

So the `processor` value provided to the config files contains the target architecture; either `x86` or `x86_64`. In the `cfg` module it is only available as `cfg.site_config.LUAROCKS_UNAME_M`.

So; 'processor' actually means 'target architecture'

Questions;
* Should we also provide a `processor` field to the `cfg` module? to line up with the config file?
* Should we rename `processor` to `target_architecture` or something else more descriptive?

**Comment by Tieske** [comment]
This pretty much says the same as @ignacio in https://github.com/keplerproject/luarocks/pull/385#issuecomment-113673651

**Comment by Tieske** [comment]
one more;
* if it is available only in `cfg.site_config.LUAROCKS_UNAME_M` than we cannot override it in `config.lua`. Can we? So @ignacio scenario of manually configuring a different compile target cannot be configured through `config.lua`

or am I missing something?

(same applies for `cfg.site_config.LUAROCKS_UNAME_S` which determines the use of MS or MinGW compilers)

**Comment by ignacio** [comment]
I agree with everything @Tieske said.

It seems that the primary assumption is that by default you're targeting your default architecture.
If you are on Linux x86_64, you'll target that.
If you install binary rocks, you'll want those that matches Linux-x86_64.

However that assumption breaks when the user specifies a custom Lua runtime (and by custom it can mean just the vanilla Lua sources compiled for a different arch). Also that assumption is broken out of the box on Windows. By using the provided binaries, when you install on Windows x64, you get 32 bit binaries on a x64 host.

I propose we:
- rename "processor" to "target_architecture" as @Tieske proposed.
- stop using `uname -m` to get that info by default. Extract it from the specified Lua runtime and only fallback to it if the detection fails.

Now, should the user be able to override the target_architecture? Yes, at his own risk. Also whenever we fail to determine it automatically.

Do we need to report the host cpu? I'm not sure, I don't see a use for that.

Do we need to make the bitness of the interpreter available? I certainly need that for the cmake backend.

**Comment by hishamhm** [comment]
> Should we also provide a processor field to the cfg module? to line up with the config file?

The cfg module is internal, and with quite different contents from the config file environment (or at least it does now, as it should have always been). I don't see the need for lining it up; might actually get more confusing.

> Should we rename processor to target_architecture or something else more descriptive?

Not sure if it's worth the compatibility breakage in the config file format. Maybe deprecate `processor` and add `target_arch` as an alias? Internally LuaRocks calls `arch` the "system-processor" tuple, so using "arch" there might be confusing. Maybe `target_cpu`?

> if it is available only in cfg.site_config.LUAROCKS_UNAME_M than we cannot override it in config.lua. Can we? So @ignacio scenario of manually configuring a different compile target cannot be configured through config.lua

Basically, one can override all variables through config.lua. So it is technically possible to reconfigure LuaRocks to use a different architecture; it's just cumbersome. For example, to force mingw in a platform that was auto-configured as msvc, one would need a config.lua file like this:

```lua
platforms = { "win32", "mingw32", "windows" }
obj_extension = "o"
cmake_generator = "MinGW Makefiles"
variables.MAKE = "mingw32-make"
variables.CC = "mingw32-gcc"
variables.RC = "windres"
variables.LD = "mingw32-gcc"
variables.CFLAGS = "-O2"
variables.LIBFLAG = "-shared"
external_deps_patterns = {
   bin = { "?.exe", "?.bat" },
   lib = { "lib?.dll.a", "?.dll.a", "lib?.a", "cyg?.dll", "lib?.dll", "?.dll", "?.lib" },
   include = { "?.h" }
}
runtime_external_deps_patterns = {
   bin = { "?.exe", "?.bat" },
   lib = { "cyg?.dll", "?.dll", "lib?.dll" },
   include = { "?.h" }
}
```

(ie, basically do what `if detected.mingw32` does in the code of luarocks/cfg.lua)

**Comment by hishamhm** [comment]
> stop using uname -m to get that info by default. Extract it from the specified Lua runtime and only fallback to it if the detection fails.

That makes sense. The current solution assumed we would be using the version of Lua shipped with the binary distribution. Now that we support pointing to other Luas, we should configure according to them.

> Do we need to report the host cpu? I'm not sure, I don't see a use for that.

I don't see either.

> Do we need to make the bitness of the interpreter available? I certainly need that for the cmake backend.

Could you derive that from the `target_cpu`? (ie, make the cmake backend know that "x86" means "32 bit" and "x86_64" means "64 bit". Yes I know there are other processors, but there aren't _that_ many architectures around... adding an extra `or` to an `if` somewhere when a new arch pops up sounds simpler than adding more detection code to be maintained and more configuration variables to be kept in sync.)

**Comment by ignacio** [comment]
On Mon, Jun 22, 2015 at 3:12 PM, Hisham Muhammad <notifications@github.com>
wrote:
>
>  Could you derive that from the target_cpu? (ie, make the cmake backend
> know that "x86" means "32 bit" and "x86_64" means "64 bit". Yes I know
> there are other processors, but there aren't *that* many architectures
> around... adding an extra or to an if somewhere when a new arch pops up
> sounds simpler than adding more detection code to be maintained and more
> configuration variables to be kept in sync.)
>
Yes, that's what I'm doing in cmake now but it felt clunky. Having to
duplicate the logic that the installer already has.

**Comment by hishamhm** [comment]
In that case I think the simplest approach is to check if the processor string contains "64" in luarocks/cfg.lua and set something like `cfg.bitness`: this should catch x86_64/amd64, ppc64, arm64/aarch64, sparc64...

(Quick research: 
https://en.wikipedia.org/wiki/Uname
http://lists.freebsd.org/pipermail/freebsd-arm/2015-February/010214.html
https://github.com/MLton/mlton/pull/7 )

**Comment by ignacio** [comment]
Good. Do you have any thoughts on how to retrieve the bitness from the lua binary? file + grep seems to work fine for shared libraries. It seems that for .a files it is necessary to do what is [suggested here](http://stackoverflow.com/questions/5665228/in-linux-determine-if-a-a-library-archive-32-bit-or-64-bit), but it seems "fragile".

FWIW, here's the output of two libs, first compiled as 32 bits, the other as 64 bits:
~~~~
vagrant@packer-debian-6:~/lua/lua-5.1.5/src
➯ objdump -f /home/vagrant/lua/lua-5.2.4/src/liblua.a | grep ^architecture | head -1
architecture: i386:x86-64, flags 0x00000011:
vagrant@packer-debian-6:~/lua/lua-5.1.5/src
➯ objdump -f /home/vagrant/lua/lua-5.1.5/src/liblua.a | grep ^architecture | head -1
architecture: i386, flags 0x00000011:
~~~~

**Comment by hishamhm** [comment]
> Do you have any thoughts on how to retrieve the bitness from the lua binary?

You're thinking of implementing this in the Unix `configure` script? Well, you could run `file` on the lua binary too:

```lua
hisham@pointer ~]file `which lua`
/Programs/Lua/5.3.0/bin/lua: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, stripped
```

but I've seen boxes where `file` isn't installed by default. But I'm not really sure if we should go out of our way to support cross-compilation. This opens a whole can of worms — just keeping everything configurable from config.lua should be enough for those who know what they're doing, doesn't it?

**Comment by ignacio** [comment]
Well, it is a mess, right? To be strict, it should be whatever you supply in the --with-lua-lib flag (which can be a .so or a .a , IIRC).
So, it's fine. If the user uses a custom Lua install, it is expected she edits the config file.

We'll have to detect that only on Windows. Luckily, there is pe-parser which deals with that stuff and works fine with .dlls.

The status would be:
Linux and friends. Nothing to be done.

Windows:
Detect the target_cpu from lua.dll. Build the platform string using x86 or x86_64.

Both:
Deprecate 'processor'. Add target_cpu (or whatever the final name is).

**Comment by Tieske** [comment]
> Detect the target_cpu from lua.dll. Build the platform string using x86 or x86_64

pe-parser uses the following table;

```lua
  Machine = {
    ["0"] = "IMAGE_FILE_MACHINE_UNKNOWN",
    ["1d3"] = "IMAGE_FILE_MACHINE_AM33",
    ["8664"] = "IMAGE_FILE_MACHINE_AMD64",
    ["1c0"] = "IMAGE_FILE_MACHINE_ARM",
    ["1c4"] = "IMAGE_FILE_MACHINE_ARMNT",
    ["aa64"] = "IMAGE_FILE_MACHINE_ARM64",
    ["ebc"] = "IMAGE_FILE_MACHINE_EBC",
    ["14c"] = "IMAGE_FILE_MACHINE_I386",
    ["200"] = "IMAGE_FILE_MACHINE_IA64",
    ["9041"] = "IMAGE_FILE_MACHINE_M32R",
    ["266"] = "IMAGE_FILE_MACHINE_MIPS16",
    ["366"] = "IMAGE_FILE_MACHINE_MIPSFPU",
    ["466"] = "IMAGE_FILE_MACHINE_MIPSFPU16",
    ["1f0"] = "IMAGE_FILE_MACHINE_POWERPC",
    ["1f1"] = "IMAGE_FILE_MACHINE_POWERPCFP",
    ["166"] = "IMAGE_FILE_MACHINE_R4000",
    ["1a2"] = "IMAGE_FILE_MACHINE_SH3",
    ["1a3"] = "IMAGE_FILE_MACHINE_SH3DSP",
    ["1a6"] = "IMAGE_FILE_MACHINE_SH4",
    ["1a8"] = "IMAGE_FILE_MACHINE_SH5",
    ["1c2"] = "IMAGE_FILE_MACHINE_THUMB",
    ["169"] = "IMAGE_FILE_MACHINE_WCEMIPSV2",
  },
````

value `IMAGE_FILE_MACHINE_I386` results in `x86`, all others in `x86_64` (that logic is in the installer iirc)

**Comment by ignacio** [comment]
Yes, the change needed in the installer would be to use the .dll instead of the .exe when determining that info.

**Comment by Tieske** [comment]
Cannot we assume them to be identical? In what case would one have a 32bit exe, next to a 64bit dll?

Anyhow; then we need to parse 2 files (using pe-parser) then;

1. `.exe` to find the runtime (if not found, it will proceed with dependencies, hence also the dll)
2. `.dll` for bitness

or maybe start with the `.dll`, if no runtime is found, also parse the `.exe`. That would be the logical order.

**Comment by hishamhm** [comment]
> Cannot we assume them to be identical? In what case would one have a 32bit exe, next to a 64bit dll?

It's safe to assume things would be quite broken in this scenario.

**Comment by ignacio** [comment]
Weren't we working under the assumption that the interpreter and the
runtime could be different?
​

**Comment by Tieske** [comment]
What I meant was multiple Lua installations / file sets. I think that any single installation / file set mixing 32 and 64 and/or runtimes is "quite broken" as @hishamhm said.

So the scenario I meant is mainly that LuaRocks itself runs on one set (say 32 bit / MSVCRT / MinGW), but compiles for a different set (64 bit / MSVCRT10 / VS2008 for example).

When installing the installer will find a Lua installation (or bring its own), detect runtime and bitness. The `/MW` command line switch determines MinGW (or else MS toolchain by default). This is the common scenario.

For advanced use, once installed, one could update `config.lua` and name a different compiler, dll to link against, runtime to use and/or bitness (or just compiler and .dll, and dynamically detect runtime and bitness from the dll).

once done, if you need multiple distributions, write a script to build them. Run it, copy in a different `config.lua` and run it again. This will build the same set for different architectures/distributions.

**Comment by ignacio** [comment]
Ah! Sorry, I misunderstood you, Thijs. Yes, this simplifies things a lot. Cross compiling, if needed, should be done by means of tweaking the config file.

**Comment by Tieske** [comment]
if you want dynamic testing of runtime and bitness, using the dll. Then the `cfg` module would get a dependency on `pe-parser` (which is currently only used by the installer, and removed thereafter). Do we want to change this, or leave it an install time check?

Todo list;
Linux and friends:

1. Nothing to be done.

Windows:

1. Detect the target_cpu from lua.dll. Build the platform string using x86 or x86_64.
2. _Optional: detect at runtime instead of install-time_

Both:

1. Deprecate 'processor'. Add target_cpu (or whatever the final name is).
2. _Make possible to overrule setting from `site_config.lua`_

**Comment by ignacio** [comment]
I'd leave it as an install check.

**Comment by Tieske** [comment]
> Deprecate 'processor'. Add target_cpu (or whatever the final name is)

'processor' is only available in the global environment for config files, not in the resulting `cfg` table. So when adding `target_cpu` we add it to both tables? and in the config file environment, also a copy named `processor` for backward compatibility.

> Make possible to overrule setting from site_config.lua

The site_config file is available as a sub-table from `cfg`. Why is that? Shoudln't the config files (all of them) be linked through `__index`? 
Currently the `cfg` has an `__index` method that looks values up in `defaults`. So should it be that the user accesses `cfg`, if not found, its metatable looks in `site_config` and if not found there, its metatable looks in `defaults`?
That would provide a stepped approach that allows overriding defaults, or system settings on a per user basis.

**Comment by hishamhm** [comment]
A more philosophical comment:

site_config.lua is supposed to be a lower level setting. There's a
bootstrapping issue there: site_config defines the platform, which is used
to find the user's config file. Users shouldn't know/care about the
site_config settings, which should be correct according to the install site.

site_config is meant to direct which defaults are picked for the
configuration. The user should be then able to override the configuration,
not site_config.

Also, I can't check now cause I'm on my phone, but site_config (module or
table) shouldn't be used anywhere else in LuaRocks other than the initial
setup inside luarocks.cfg.

**Comment by Tieske** [comment]
Did a quick search on `site_config` and it indeed only popped up in `cfg.lua`. In that case; shouldn't the table be removed from the final `cfg` module table?

**Comment by hishamhm** [comment]
Yes, it can be a local.

**Comment by Tieske** [comment]
See PR #393 fixed naming, exposed `target_cpu` with backward compat to `processor`

remains; configuring targets from `config.lua`

**Comment by ignacio** [comment]
So far, so good. Thank you.

**Comment by ignacio** [comment]
Seems that this can be closed, right?
