### ISSUE TITLE
Using "--extension" flag crashes luarocks

### ISSUE THREAD

**Issue by xiaq** [keplerproject/luarocks#391]
Calling any subcommand with `--extensions` results in an error:

```
$ luarocks help --extensions
/usr/bin/lua: /usr/local/share/lua/5.2/luarocks/command_line.lua:117: attempt to call a nil value (field 'load_extensions')
stack traceback:
        /usr/local/share/lua/5.2/luarocks/command_line.lua:117: in function 'luarocks.command_line.run_command'
        /usr/local/bin/luarocks:33: in main chunk
        [C]: in ?
```

where `type_check.load_extensions()` used to exist during some timespan but no longer does. Looks like some code rot here.

**Comment by hishamhm** [comment]
Indeed: https://github.com/keplerproject/luarocks/commit/f0d66aeacd60e6df926a55ecb9a08e6f802f9242

I replaced the explicit enabling of extensions with the `_version` field in type checking tables. Use the `rockspec_format` variable in the rockspec to enable extensions.  I'll remove the `--extensions` flag.
