### ISSUE TITLE
Update pe-parser to allow installing with Visual Studio 2015

### ISSUE THREAD

**Issue by ignacio** [keplerproject/luarocks#401]
The name of the C runtime has changed in Visual Studio 2015. There's an issue for pe-parser [here](https://github.com/Tieske/pe-parser/issues/4) and once that is sorted out, we should update the version used internally.

**Comment by Tieske** [comment]
I updated the pe-parser module to version 0.4. Can you try whether that new version works if used with the LuaRocks install script?

**Comment by ignacio** [comment]
I manually copied pe-parser in my fork of LuaRocks:

https://ci.appveyor.com/project/ignacio/luarocks

All tests green.
