### ISSUE TITLE
had to replace git: to http: in git.lua to work behind proxy

### ISSUE THREAD

**Issue by antimercy** [keplerproject/luarocks#408]
I am behind http proxy of the college. I spend my last 3 hours searching for why I was not able to install nngraph. I then looked at the output of luarocks --verbose , which showed me that at one point it's calling git clone "git://" blah blah , so then I had to go down to the git.lua and wrote a simple string replacement function over the variable containing the url , rockspec.source.url and just replaced it with rockspec.source.url:gsub("git:","http:")

Now, I want to know , why I had to suffer so much :P . Isn't there a simple way to do that. I searched a lot online about it, but I don't think it's clearly explained anywhere about this particular problem.

**Comment by motoko-11** [comment]
Same problem again , look at it please , again it's trying to use git:// :(

luarocks install cltorch
Installing https://raw.githubusercontent.com/torch/rocks/master/cltorch-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/cltorch-scm-1.rockspec... switching to 'build' mode
Cloning into 'cltorch'...
remote: Counting objects: 114, done.
remote: Compressing objects: 100% (108/108), done.
remote: Total 114 (delta 12), reused 39 (delta 1), pack-reused 0
Receiving objects: 100% (114/114), 140.66 KiB | 88.00 KiB/s, done.
Resolving deltas: 100% (12/12), done.
Checking connectivity... done.
git clone --recursive git://github.com/hughperkins/cltorch.git && cd cltorch && cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_PREFIX_PATH="/home/lokendra/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/lokendra/torch/install/lib/luarocks/rocks/cltorch/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install

Cloning into 'cltorch'...

**Comment by daurnimator** [comment]
Try `git+https://`...

**Comment by motoko-11** [comment]
Can you please explain ? I kind of wasn't able to follow where did you mean I should place "git+http://" . If you mean in source code, then I don't know where ?

**Comment by daurnimator** [comment]
> Can you please explain ? I kind of wasn't able to follow where did you mean I should place "git+http://" . If you mean in source code, then I don't know where ?

Try:
  - downloading the rockspec
  - swaping the source url in it from `git://` to `git+http://`
  - installing the local rockspec

**Comment by cfedk** [comment]
For other people's reference: http://stackoverflow.com/a/30467172/1813418

**Comment by mpeterv** [comment]
This isn't really a problem in luarocks, rockspec authors simply need to use "git+http(s)://" instead of "git://" whenever possible. Rockspecs generated with "write-rockspec" already do that if "origin" remote uses http(s), which is common for github repos.
