### ISSUE TITLE
Shell completion

### ISSUE THREAD

**Issue by stormc** [keplerproject/luarocks#412]
I would like to see shell completion for luarocks given its many options and commands that are hard to remember when using luarocks on an occasional basis, besides the convenience of shell completion.
I could go for a zsh completion and issue a pull request... What do you think? Should shell completion be maintained within luarocks or should it be offloaded to the respective shells?

**Comment by hishamhm** [comment]
> Should shell completion be maintained within luarocks or should it be offloaded to the respective shells?

This should be handled by shells or third-party projects. Consider yourself encouraged to submit a patch to zsh! They have code for lots of package managers in their tree (see here: https://github.com/zsh-users/zsh/tree/master/Completion/Unix/Command — note however that this is just a Github mirror and for contributing to zsh one should contact the developers at zsh.org)
