### ISSUE TITLE
I cound't able to use luarocks with lua 5.3

### ISSUE THREAD

**Issue by quiloos39** [keplerproject/luarocks#414]
I am running Ubuntu Server 15.04 on VM , I used these commands to install lua and luarocks

sudo apt-get install unzip
sudo apt-get install gcc
wget http://www.lua.org/ftp/lua-5.3.1.tar.gz
tar zxf lua-5.3.1.tar.gz
cd lua-5.3.1
sudo make solaris test
sudo make solaris install
reboot
wget http://luarocks.org/releases/luarocks-2.2.1.tar.gz
tar zxpf luarocks-2.2.1.tar.gz
cd luarocks-2.2.1
./configure; sudo make bootstrap
sudo luarocks install luasocket

lua -lsocket -- It errors.
<img width="724" alt="screen shot 2015-07-24 at 3 36 57 pm" src="https://cloud.githubusercontent.com/assets/10371011/8884426/392f3332-325f-11e5-97b1-b59ac48a84aa.png">
<img width="720" alt="screen shot 2015-07-24 at 3 32 52 pm" src="https://cloud.githubusercontent.com/assets/10371011/8884433/4420240e-325f-11e5-8382-8e2f5352411a.png">
<img width="719" alt="screen shot 2015-07-24 at 3 33 23 pm" src="https://cloud.githubusercontent.com/assets/10371011/8884444/5668c468-325f-11e5-8cda-ec60e7b70a3d.png">

**Comment by siffiejoe** [comment]
Use `make linux` for building Lua on Linux instead of `make solaris`.

**Comment by quiloos39** [comment]
It didn't work. I also getting this problem. when i remove lua 

make uninstall lua it still searching for lua how to remove variable or unset it ? 

<img width="713" alt="screen shot 2015-07-25 at 3 27 00 am" src="https://cloud.githubusercontent.com/assets/10371011/8887039/0b4180b0-327d-11e5-9b06-deffe7383ec4.png">

**Comment by siffiejoe** [comment]
Typing `hash -r` (or starting a new shell) will make bash forget that there was a `lua` in `/usr/local/bin`.

What do you mean by "It didn't work"? What's the error message? Do you have all required development packages installed (e.g. `libreadline-dev`)?

**Comment by quiloos39** [comment]
I check `libreadline-dev` it's installed. I used make Lunix install to install Lua and I am pretty sure i installed `luasocket`.

When i do lua -lsocket it errors me here.
<img width="723" alt="screen shot 2015-07-25 at 3 58 31 pm" src="https://cloud.githubusercontent.com/assets/10371011/8889518/0b272e40-32e6-11e5-8d76-d2dc94328aaa.png">

**Comment by daurnimator** [comment]
What lua headers do you have installed?
Please paste the output of:

    grep "LUA_VERSION" $(find /usr/ -name lua.h)

**Comment by siffiejoe** [comment]
@daurnimator: `lua_gettop` is a function in all Lua versions since 5.0 at least, so it can't be a header version issue. The Lua API just isn't available for the extension module, which means that the `lua` executable used wasn't built with `make linux`. (Another hint for that is that readline isn't working.)

Possible reasons I can think of:
*   a missing `make clean` before `make linux`
*   a missing sudo before `make install`

**Comment by quiloos39** [comment]
I promise i will learn every single detail about unix and lua library but dont make me suffer from lua 5.1 :^(

**Comment by hishamhm** [comment]
@quiloos39 type `which lua` in your terminal. Does it show `/usr/local/bin/lua`?

**Comment by quiloos39** [comment]
Yes

**Comment by siffiejoe** [comment]
Then type `ldd /usr/local/bin/lua` and show us the output please.

**Comment by siffiejoe** [comment]
Copy and paste of the text will do. No need for a screenshot ...

**Comment by quiloos39** [comment]
![screenshot 3](https://cloud.githubusercontent.com/assets/10371011/9099981/780807ae-3bde-11e5-97d3-e7d049f4bf3f.png)


Sorry i cant copy paste through Vm.

**Comment by daurnimator** [comment]
Did you use `make linux`? the lack of `io.popen` suggests not.

**Comment by quiloos39** [comment]
I use generic

![screenshot 5](https://cloud.githubusercontent.com/assets/10371011/9100090/87044d2a-3bdf-11e5-87f4-e8437f58e376.png)

**Comment by daurnimator** [comment]
> I use generic

Use `make linux`

**Comment by siffiejoe** [comment]
And as mentioned before, you need libreadline-dev installed for `make linux` to succeed:

```
sudo apt-get install libreadline-dev
```

**Comment by quiloos39** [comment]
I cant believe it worked i don't know what i did wrong. Probably libreadline-dev i am pretty sure i downloaded before but it seems it fixed my problem some how thanks all for helping.

I don't to topics here so i will ask here last time. I installed luasocket successfully but when i install luasec its erroring me.

![screenshot 7](https://cloud.githubusercontent.com/assets/10371011/9101240/0cfbddaa-3bed-11e5-8176-0b4ebb558cc6.png)

**Comment by daurnimator** [comment]
> when i install luasec its erroring me.

As it says in the error message, you need openssl/ssh.h.
On ubuntu, it's in the 'libssl-dev' deb.

**Comment by quiloos39** [comment]
So what i suppose do in this case ?

**Comment by daurnimator** [comment]
> So what i suppose do in this case ?

Install libssl-dev (`sudo apt install libssl-dev`) then install luasec (`sudo luarocks install luasec`)

**Comment by quiloos39** [comment]
Thanks for all @siffiejoe I apologize to you i didn't understand at begging.
