### ISSUE TITLE
luarocks compiling rocks to lib instead of lib64

### ISSUE THREAD

**Issue by malkavi** [keplerproject/luarocks#416]
I'm using this file to create a rpm file for OpenSuse:
https://build.opensuse.org/package/view_file/home:malkavi/luarocks/lua-luarocks.spec?expand=1

But when I install a rock, It's compiled and installed to /usr/lib/lua/5.2/ instead of /usr/lib64/lua/5.2/
Can I change something in the make commands to fix this?

The 32bit version of the package seems to work correctly for 32bit systems.

**Comment by hishamhm** [comment]
Hi!

Try to produce an /etc/luarocks/config.lua file containing the following:

```
lib_modules_path="/lib64/lua/"..lua_version
```

Please test this and let me know if it fixes the issue! Thanks!

**Comment by malkavi** [comment]
Thanks!! Now It works.
I have fixed the spec file. Now I add the line to the config file and the .so are installed to lib64 correctly for 64bit system and to lib for 32bit.

**Comment by axilleas** [comment]
Thanks for this issue :)
For reference, on CentOS 7 the config resides in `/etc/luarocks/config-5.1.lua`.

I added it to the documentation as I saw it was missing, https://github.com/keplerproject/luarocks/wiki/Config-file-format#Locations

**Comment by hishamhm** [comment]
@rrthomas, do you need to configure `lib_modules_path` explicitly when dealing with the multiarch subdir on Debian systems? When you originally asked for the feature to have LR look for the multiarch dir to find external dependencies, we added this to `configure`:

```bash
if [ "$LUAROCKS_UNAME_S" = Linux ]
then
   GCC_ARCH=`gcc -print-multiarch 2>/dev/null`
   if [ -n "$GCC_ARCH" -a -d "/usr/lib/$GCC_ARCH" ]
   then
      MULTIARCH_SUBDIR="lib/$GCC_ARCH"
   elif [ -d "/usr/lib64" ]
   then
      # Useful for Fedora systems
      MULTIARCH_SUBDIR="lib64"
   fi
fi
```

...but now we're using the multiarch subdir for external deps only, and not for installing rocks. 

In other words, is the `package.cpath` for the Lua interpreter on Debian 64-bit set up to look for C modules in `/usr/lib/$GCC_ARCH/lua/5.x` or `/usr/lib/lua/5.x`?

Thanks!

**Comment by hishamhm** [comment]
@axilleas Thanks for documenting! I'll try to make this automatic in the next release.

**Comment by rrthomas** [comment]
@hishamhm, both: the Debian Lua `package.cpath` default is e.g. for Lua 5.1 on amd64, `./?.so;/usr/local/lib/lua/5.1/?.so;/usr/lib/x86_64-linux-gnu/lua/5.1/?.so;/usr/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so`

**Comment by hishamhm** [comment]
@rrthomas Thanks! Should we set `lib_modules_path` in `luarocks.cfg` according to `$MULTIARCH_SUBDIR`, then?

**Comment by rrthomas** [comment]
@hishamhm, that would seem a good idea. I currently have the following `config.lua`:

    local arch = processor .. "-linux-gnu"
    
    external_deps_patterns = {
      bin = {"?.exe", "?.bat"},
      lib = {"lib?.a", "lib?.so", arch.."/lib?.a", arch.."/lib?.so"},
      include = {"?.h"},
    }
    
    rocks_trees = {
      {
        root = home.."/.local",
        lib_dir = home.."/.local/lib/"..arch.."/lua/"..lua_version,
        bin_dir = home.."/.local/bin/"..arch,
      }
    }

Some of this is for my personal `~/.local` tree (though again, that's standard-compliant); the rest is for system multi-arch.
