### ISSUE TITLE
I cant install tekui

### ISSUE THREAD

**Issue by quiloos39** [keplerproject/luarocks#420]
The command that i use

<img width="852" alt="screen shot 2015-09-11 at 03 53 51" src="https://cloud.githubusercontent.com/assets/10371011/9804666/c9a3dd1a-5838-11e5-8842-b2b379269327.png">

The error
<img width="920" alt="screen shot 2015-09-11 at 03 54 08" src="https://cloud.githubusercontent.com/assets/10371011/9804667/c9c34a56-5838-11e5-981e-6d6d0e525250.png">

I have installed freetype on brew but i don't know does it make difference
<img width="385" alt="screen shot 2015-09-11 at 03 54 43" src="https://cloud.githubusercontent.com/assets/10371011/9804673/de1367fc-5838-11e5-8c63-6c34f1a223c3.png">

These are error that i get 

X11 is located at /opt/X11
freetype i installed from brew is /usr/local/opt/freetype

**Comment by mpeterv** [comment]
Assuming `ft2build.h` is in `/usr/local/opt/freetype/include/ft2build.h`, passing `FREETYPE_DIR=/usr/local/opt/freetype` to Luarocks (as suggested in the error message) should work. Did you try it? You can also upgrade to at least Luarocks 2.3.0 to get better messages with lists of location Luarocks checked when looking for the header.

**Comment by quiloos39** [comment]
Wew. Anyway i figured it out along time ago thanks for replying atleast.
