### ISSUE TITLE
LR command 'show' only lists one installed rock

### ISSUE THREAD

**Issue by Tieske** [keplerproject/luarocks#423]
If multiple versions of the same rock are installed, then `sudo luarocks show rockname` will only display one entry.

I don't know what the desired behaviour is. My guess; show all installed rocks, and add a command line option to specify a specific version to show. Alternatively allow the name to contain a version, eg. `luarocks show copas-1.2` (same as namingscheme for rockspecs)

**Comment by mpeterv** [comment]
IMHO displaying all versions at the same time produces too much output, perhaps it should instead list all installed versions in the end if there are more than one? E.g.

```
--- the usual luarocks show <rock> output ---
Other installed versions:
   0.4.0
   0.2.1
```

And `luarocks show` already accepts version as the second optional argument, so that you can select which one you want.

**Comment by hishamhm** [comment]
I use `luarocks list copas` when I want to list all versions; my main use-case for `show` is to check the list of modules of a rock, and in this case I usually want the latest...

**Comment by mpeterv** [comment]
Right, I forgot that 'list' can take rock name. Then IMO current behavior is perfectly fine.

**Comment by mpeterv** [comment]
Right, I forgot that 'list' can take rock name. Then IMO current behavior is perfectly fine.
