### ISSUE TITLE
Certain rockspecs create blank files

### ISSUE THREAD

**Issue by Alloyed** [keplerproject/luarocks#425]
Sorry for the less-than-informative title but I'm not really sure what's going on here.
I'm maintaining a few rockspecs, which, on installation, leave behind empty files instead.
The two rockspecs in question:
- https://github.com/Alloyed/loverocks-repo/blob/master/bump-3.1.4-1.rockspec
- https://github.com/Alloyed/loverocks-repo/blob/master/tween-2.0.0-1.rockspec

They both install a single lua module using the 'builtin' build type.

After install:

```
$ ls -l ~/.luarocks/share/lua/5.1/{bump.lua,tween.lua}
-rwxr-xr-x 1 kyle kyle 0 Sep 15 23:16 /home/kyle/.luarocks/share/lua/5.1/bump.lua
-rwxr-xr-x 1 kyle kyle 0 Sep 15 23:16 /home/kyle/.luarocks/share/lua/5.1/tween.lua
```

Other files, such as the rockspec and the manifest seem to install fine:

```
$ ls -l ~/.luarocks/lib/luarocks/rocks-5.1/{tween/2.0.0-1,bump/3.1.4-1}
/home/kyle/.luarocks/lib/luarocks/rocks-5.1/bump/3.1.4-1:
total 8
-rw-r--r-- 1 kyle kyle 494 Sep 15 23:16 bump-3.1.4-1.rockspec
-rw-r--r-- 1 kyle kyle 159 Sep 15 23:16 rock_manifest

/home/kyle/.luarocks/lib/luarocks/rocks-5.1/tween/2.0.0-1:
total 8
-rw-r--r-- 1 kyle kyle 161 Sep 15 23:16 rock_manifest
-rw-r--r-- 1 kyle kyle 541 Sep 15 23:16 tween-2.0.0-1.rockspec
```

Tested on Arch Linux, using lua 5.1 and luarocks 2.2.2

**Comment by ignacio** [comment]
Adding a 'dir' entry in the rockspec fixed it for me.

For instance, for _bump_ I added _dir_ to the rockspec, like this:

~~~lua
source = {
   url = "git://github.com/kikito/bump.lua",
   dir = "bump.lua",
   tag = "3.1.4"
}
~~~~

and it worked fine. Haven't tested with the other rock, but I'm pretty sure
it is the same thing.
​

**Comment by ignacio** [comment]
Hi. Did the suggested fixes work for you?

**Comment by Alloyed** [comment]
Yes, they did (sorry for the late reply)
I don't really understand the behavior of `dir` here, though. Should I be adding it to all my git-sourced rockspecs or is this just a workaround for a bug?

**Comment by hishamhm** [comment]
Yes, it's a workaround. I'm looking at a permanent solution.

**Comment by ignacio** [comment]
Maybe something similar to what we did here?

https://github.com/keplerproject/luarocks/pull/404 fixes

**Comment by hishamhm** [comment]
My initial plan for a solution was this:

```diff
diff --git a/src/luarocks/fetch.lua b/src/luarocks/fetch.lua
index e92aedd..e8c3e84 100644
--- a/src/luarocks/fetch.lua
+++ b/src/luarocks/fetch.lua
@@ -247,7 +247,7 @@ function fetch.load_local_rockspec(filename, quick)
    local base = fetch.url_to_base_dir(filebase)
    rockspec.source.dir = rockspec.source.dir
                       or rockspec.source.module
-                      or ((filebase:match("%.lua$") or filebase:match("%.c$")) and ".")
+                      or ((fetch.is_basic_protocol(protocol) and (filebase:match("%.lua$") or filebase:match("%.c$"))) and ".")
                       or base
    if rockspec.dependencies then
       for i = 1, #rockspec.dependencies do
```

Only assume that files ending in `.lua` and `.c` represent a single file when they're being fetched via HTTP(S) or FTP (ie, allow SCM repos ending with `.lua`)

However, looking at the repository, this would break three rockspecs: cassowary, jmespath and lodash. The authors of these specs realized that they could write "cassowary.lua/cassowary.lua" in the build section and it would work.

A number of authors, however, also discovered that adding `.git` to the URL works around the problem: docopt, mo, pegasus, require, semver, tree, video_streaming, xlsxwriter.

So, what I'll do is to put this in the luarocks-3 branch:

```diff
diff --git a/src/luarocks/fetch.lua b/src/luarocks/fetch.lua
index e92aedd..5ae0582 100644
--- a/src/luarocks/fetch.lua
+++ b/src/luarocks/fetch.lua
@@ -247,7 +247,10 @@ function fetch.load_local_rockspec(filename, quick)
    local base = fetch.url_to_base_dir(filebase)
    rockspec.source.dir = rockspec.source.dir
                       or rockspec.source.module
-                      or ((filebase:match("%.lua$") or filebase:match("%.c$")) and ".")
+                      or ( (filebase:match("%.lua$") or filebase:match("%.c$"))
+                           and (deps.format_is_at_least(rockspec, "3.0")
+                                and (fetch.is_basic_protocol(protocol) and "." or base)
+                                or  ".") )
                       or base
    if rockspec.dependencies then
       for i = 1, #rockspec.dependencies do
```

(it feels good to be able to add these incompatible fixes somewhere!)
