### ISSUE TITLE
documentation : mediawiki format/rendering issue

### ISSUE THREAD

**Issue by tst2005** [keplerproject/luarocks#430]
On https://github.com/keplerproject/luarocks/wiki/Rockspec-format
In the "Dependency information" section, in the "dependencies (array of strings)" paragraph.
We are not able to read the end of paragraph correctly.

I read
```
[...] RubyGems ("~> 2" means ">= 2, 2.4" means ">= 2.4, 
```
But the source code is
```
[...] RubyGems ("~> 2" means ">= 2, < 3"; "~> 2.4" means ">= 2.4, < 2.5"). No operator means an implicit == (i.e., "lfs 1.0" is the same as "lfs == 1.0"). "lua" is an special dependency name; it matches not a rock, but the version of Lua in use. Supports [[Platform overrides|per-platform overrides]].
```

**Comment by mpeterv** [comment]
Looks like `<` before numbers needs to be escaped or it is interpreted as a tag start. Fixed.
