### ISSUE TITLE
cmake builder ignores install_pass

### ISSUE THREAD

**Issue by isage** [keplerproject/luarocks#431]
Looking at code it's more of a feature request, but still.

**Comment by ignacio** [comment]
Can you provide an example CMakelists.txt file so we can test the feature?

**Comment by isage** [comment]
https://github.com/isage/lua-imagick/blob/master/CMakeLists.txt for example

**Comment by ignacio** [comment]
That should work fine with current LuaRocks version (I mean, if you install from latest sources).

[This module](https://github.com/xpol/lua-rapidjson/blob/master/CMakeLists.txt) is also using CMake and it is installing fine.

**Comment by isage** [comment]
Eh, this feature request is not about installing, it's about **not** installing, if build.install_pass is set to 'false'.
https://github.com/keplerproject/luarocks/blob/master/src/luarocks/build/cmake.lua#L60
In current code install step is always run with cmake builder.

**Comment by ignacio** [comment]
Ok. *Now* I get it :smile: 

@hishamhm should we add the whole "make" flags? Like build_pass, install_pass and so on?
