### ISSUE TITLE
The path should, perhaps, respect the tree

### ISSUE THREAD

**Issue by garthk** [keplerproject/luarocks#435]
We can specify `--tree=$TREE` for `luarocks list`, `luarocks install`, and `luarocks make` to manage a tree of rocks anywhere on my filesystem. `eval $(luarocks path)` won't help us _use_ them, however.

Prepending `$TREE/share/lua/$LV` to `LUA_PATH` and `$TREE/lib/lua/$LV` to `LUA_CPATH` is possible but tricky. It's a few minutes to figure the paths; more to be confident `export LUA_PATH=${TREE}/share/lua/${LV}\;${LUA_PATH}` won't accidentally expand single-letter `.lua` files along the original `LUA_PATH`.

We can hardcode `LUA_PATH` and `LUA_CPATH` to `$TREE/…` before running `luarocks path`, but that appends the tree. We'd need it prepended to ensure `luarocks install` followed by usage won't be stuffed up by an older version of the rock installed globally.

For bonus points, we should also prepend `$TREE` to the list of "Rocks trees in use" in the output of`luarocks help`.

**Comment by garthk** [comment]
Expecting this might turn out to be a `WONTFIX` on the grounds that most users lock `LUA_PATH` and `LUA_CPATH` to the tree they have in mind.

**Comment by mpeterv** [comment]
Implemented in #543
