### ISSUE TITLE
Use luajit to launch command line script

### ISSUE THREAD

**Issue by MisterDA** [keplerproject/luarocks#438]
Hi !
I'm writing a [rock](https://luarocks.org/modules/rucikir/love-release) ([Github](https://github.com/MisterDA/love-release/tree/luarocks)). It goes recursively through the file tree and compiles lua files into luajit bytecode. Luajit overrides `loadfile` and `string.dump` functions to compile files into its bytecode and not into standard Lua bytecode.

My executable is installed this way (in the rockspec) :
```lua
build = {
  type = "none",
  install = {
    bin = {
      ["love-release"] = "main.lua",
    },
  },
}
```

And the generated file is this :

```sh
#!/bin/sh

exec '/usr/bin/lua5.1' -e 'package.path="/home/antonin/.luarocks/share/lua/5.1/?.lua;/home/antonin/.luarocks/share/lua/5.1/?/init.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;"..package.path; package.cpath="/home/antonin/.luarocks/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/?.so;"..package.cpath' -e 'local k,l,_=pcall(require,"luarocks.loader") _=k and l.add_context("love-release","git-0")' '/usr/local/lib/luarocks/rocks/love-release/git-0/bin/love-release' "$@"
```

Is there an easy way to tell luarocks to use luajit to start this file ? By this I mean little or no actions from the end-user, like having to recompile luarocks or add a [wrapper](http://lua-users.org/wiki/LuaRocksConfig). With a custom Makefile perhaps ?
If there's already a (documented) way to do it and I'm just missing it, I'm sorry.
If there's no way to do this, I'll use `io.popen(...)` to call luajit. sadness.

**Comment by MisterDA** [comment]
@Alloyed answered me [here](https://github.com/MisterDA/love-release/issues/25#issuecomment-149019215) : 
> You can't actually specifically depend on luajit for your script yet, for some reason the piece of code that would allow that is commented out:
https://github.com/Alloyed/luarocks/commit/dfce4837addfe258566b6e48dd28a9e7c72bbf62
you can just use the same check the luarocks would've used to see if the user happened to use luajit, though
```
if package.loaded.jit then do_luajit_stuff() else do_lua_stuff() end
```
Thank you !

**Comment by hishamhm** [comment]
> for some reason the piece of code that would allow that is commented out:

@MisterDA because we try to be very strict about backwards compatibility in rockspecs. Every rockspec written for LuaRocks 1.0 - 2.x should run the same in all releases, so introducing this auto-dependency would result in rockspecs that only work in 2.y onwards (for some arbitrary value of y).

Note that the other auto-dependencies such as bit32 and luabitop can be simulated in earlier LuaRocks releases by loading extra packages from the repository, so there is no compatibility breakage.

**Comment by MisterDA** [comment]
Thank you for your work and this answer.
I'll wait for LuaRocks 3.0, to hopefully break backwards compatibilty and multi-plateform portability. I'll be able to use luajit and manpages for my scripts :)
