### ISSUE TITLE
Compile error lua5.1.dll -> lua5.1.lib

### ISSUE THREAD

**Issue by robertlzj** [keplerproject/luarocks#454]
Used in Lua For Windows, windows 7 64bit, Lua5.1 32bit.
Should set `variables.LUALIB` in `config.lua` from `lua5.1.dll` (assigned automatically by default install) to `lua5.1.lib` (or other name at other place, this one is copied from 'lib' folder to main folder) manually, otherwise report [Linker Tools Error LNK1107](https://msdn.microsoft.com/en-us/library/0h6ctxtk.aspx) when building (link).

**Comment by Tieske** [comment]
what did you install? Lua For Windows does come with its own LuaRocks installation iirc. So if the setting is wrong, then please check with them.

If the LuaRocks installer failed, then what Lua version are you using? the one from the "Lua for Windows" project, or something else?

If you run the LuaRocks installer, what does it display before it actually installs? (a wrap up of what the installer found, and how it will install LuaRocks)

**Comment by robertlzj** [comment]
Sorry, I didn't notice if Lua For Windows comes with its own LuaRocks. I only find an empty folder `Lua\5.1\lua\luarocks`, I think it's put by LuaRocks.

Install LuaRocks is fine. I mean error occurs when install and buld (complie) new rocks, as a result of wrong `variables` settings above.

BTW. How can I update packages in Lua For Windows from LuaRocks? Or, I have to reinstall another one owned by LuaRocks?
Also, I have some questions about using LuaRocks, where should I put them? Thanks.

**Comment by hishamhm** [comment]
> Install LuaRocks is fine. 

Great to hear! :)

> BTW. How can I update packages in Lua For Windows from LuaRocks? 

Not sure if Lua for Windows provides that option, I don't think so.

> Or, I have to reinstall another one owned by LuaRocks?

Well, this is always an option!

> Also, I have some questions about using LuaRocks, where should I put them? Thanks.

We have a mailing list at https://lists.sourceforge.net/lists/listinfo/luarocks-developers for this purpose.

**Comment by robertlzj** [comment]
Thanks !!

**Comment by Tieske** [comment]
Can this be closed? or is there something left?

**Comment by robertlzj** [comment]
Sorry, Thank you!
