### ISSUE TITLE
Error: Failed loading socket library

### ISSUE THREAD

**Issue by idevz** [keplerproject/luarocks#457]
when I run this under cmd to upload my package,I got an error.
cmd:```luarocks upload vanilla-0.1.0.rc2-1.rockspec --api-key=xxxxxx```
I got this
```
LuaSec is not available; using plain HTTP. Install 'luasec' to enable HTTPS.
Sending vanilla-0.1.0.rc2-1.rockspec ...

Error: Failed loading socket library!
```
why? this works well oldtimes.

**Comment by ignacio** [comment]
That is because the luarocks repository now needs to be accesed using https. You should install LuaSec.

**Comment by idevz** [comment]
hi @ignacio when i run ```luarocks list socket``` i got this
```
Installed rocks:
----------------

luasocket
   3.0rc1-2 (installed) - /usr/local/luarocks-2.2.2/lib/luarocks/rocks
```

**Comment by ignacio** [comment]
Ok, I'm sorry, I got confused. You can still upload rockspecs using plain http.
I just tested that and it worked for me (I also don't have LuaSec installed, just the same version of LuaSocket as you do).

Could you post the output of `luarocks upload vanilla-0.1.0.rc2-1.rockspec --api-key=xxxxxx --verbose`. (Note the --verbose flag).

I'm not sure how you get the `Failed loading socket library` error. What is the output of 

`lua -e"print(require('socket.http'))"` ?

**Comment by idevz** [comment]
@ignacio thank you every much, I got the same info when I run cmd ```luarocks upload vanilla-0.1.0.rc2-1.rockspec --api-key=xxxxxx```  Whatever I add  the ``` --verbose flag``` or not.
but Under your advice ```lua -e"print(require('socket.http'))"``` I found out My problem is my ```socket.http``` is not in my ```package.path``` and ```package.cpath```.
Thank you again:)

**Comment by ignacio** [comment]
You're welcome !
