### ISSUE TITLE
the windows /? commandline switch is broken

### ISSUE THREAD

**Issue by Tieske** [keplerproject/luarocks#468]

**Comment by Tieske** [comment]
Most odd, when I call `install /?` the installer receives `/l` (lowercase L) instead of `/?`.

(win7, 64bit)

anyone else seeing this?

**Comment by hishamhm** [comment]
I was going to look at the release of LR 2.3.0 later today... holding it until this one is confirmed. If this needs to be fixed, I'll pack a 2.3.0-rc2.

**Comment by ignacio** [comment]
I'm on vacation, so cannot confirm, but I installed rc1 with no problem and
used the /? flag.

**Comment by Tieske** [comment]
Seems to be local to my system
````
C:\Users\Thijs>lua /?
lua: cannot open /l: Permission denied

C:\Users\Thijs>lua "/?"
lua: cannot open /?: Invalid argument

C:\Users\Thijs>
````
the command shell seems to translate the /? into /l. Have no clue though what's happening

**Comment by Tieske** [comment]
sorry for the noise, just wanted to make sure the release was not broken.

**Comment by hishamhm** [comment]
Perhaps you have a file called `l` in the root directory, and `?` is being expanded to it?

**Comment by ignacio** [comment]
Hey @Tieske have you found what was wrong in your setup?

**Comment by Tieske** [comment]
Nope, never found it. Now the system died on me, and the current laptop I'm using doesn't have the issue.
