### ISSUE TITLE
luarocks install loadcaffe: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by leo150** [keplerproject/luarocks#475]
I'm trying to install [loadcaffe](https://github.com/szagoruyko/loadcaffe) on OS X 10.10.5:

    $ brew info protobuf
    protobuf: stable 2.6.1 (bottled), devel 3.0.0-beta-1-bzl-fix
    ...
    $ luarocks install loadcaffe
    Installing
    ...
    [ 33%] Running C++ protocol buffer compiler on caffe.proto
    Scanning dependencies of target loadcaffe
    [ 66%] Building CXX object CMakeFiles/loadcaffe.dir/loadcaffe.cpp.o
    [100%] Building CXX object CMakeFiles/loadcaffe.dir/caffe.pb.cc.o
    Linking CXX shared module libloadcaffe.so
    Undefined symbols for architecture x86_64:
    "google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(
    ...

[Full log (pastebin)](http://pastebin.com/XHm1BYHn)

I guess [here (SO)](http://stackoverflow.com/a/20483829/1136218) is small workaround but it's my first day with Lua so I don't know how to configure makefile of luarocks. (Should I?)
I would appreciate any help

**Comment by daurnimator** [comment]
The loadcaffe rockspec directly runs cmake itself: it just runs exactly what you see here: https://github.com/szagoruyko/loadcaffe/blob/master/loadcaffe-1.0-0.rockspec#L25

Instead, it should use the cmake build backend that luarocks comes with.

**Comment by hishamhm** [comment]
Perhaps this should be posted to https://github.com/szagoruyko/loadcaffe/issues instead?
