### ISSUE TITLE
Any one-line command to publish a rock in current directory?

### ISSUE THREAD

**Issue by xpol** [keplerproject/luarocks#484]
When write atom packages there is `apm publsh`:

>Usage: apm publish [<newversion> | major | minor | patch | build]
>       apm publish --tag <tagname>
>       apm publish --rename <new-name>

 it does:

1. update the version in the package.json
2. git commit changes to package.json
3. tag the new version in git (same vesrsion as in step 1).
4. push to github
5. update package info in the central repostory (atom.io/packages)

So I wonder if we have equal command? or alternatives?

*(I just forget how to publish a rock...)*

**Comment by daurnimator** [comment]
> update the version in the package.json

`luarocks new_version` does this.

> 2. git commit changes to package.json
> 3. tag the new version in git (same vesrsion as in step 1).
> 4. push to github

luarocks makes no assumption about the version control system in use; I don't think I'd want it to.

> (I just forget how to publish a rock...)

`luarocks upload path/to/my.rockspec`

Are these commands not clear from `luarocks help`?

**Comment by xpol** [comment]
Does luarocks support adding custom plugins?
If it does, I'd like to add such command my self.

**Comment by ignacio** [comment]
Plugins are something that is being considered in the LR3 branch.

**Comment by xpol** [comment]
Great!

**Comment by Tieske** [comment]
@xpol can this be closed?
