### ISSUE TITLE
Windows installer unable to find luajit.exe via /BIN option

### ISSUE THREAD

**Issue by stepelu** [keplerproject/luarocks#487]
Luarocks 2.3.0 installer (`install.bat`) is unable to find LuaJIT executable via the /BIN option.

The full command I used is:
```
install.bat /P Z:/sp/Dropbox/Windows/x86/luarocks /TREE C:/ste/x86/luarockstree /BIN Z:/sp/Dropbox/Windows/x86/luajit/src
```

I tried renaming `luajit.exe` to `lua.exe` with no changes. 
The executable is definitely there, as putting `Z:/sp/Dropbox/Windows/x86/luajit/src/luajit.exe` in Windows Explorer lunches LuaJIT.

How can I debug this issue?

System is Windows x64, Visual Studio 2015.

**Comment by stepelu** [comment]
The installer's output (after requesting and being guaranteed admin rights is):

```
LuaRocks 2.2.x installer.


========================
== Checking system... ==
========================


Admin priviledges available for installing
Looking for Lua interpreter
    checking C:\ProgramData\Oracle\Java\javapath
Lua executable lua.exe, luajit.exe, lua51.exe or lua5.1.exe not found in Z:/sp/D
ropbox/Windows/x86/luajit/src

Failed installing LuaRocks. Run with /? for help.
Press any key to close this window...
```

**Comment by ignacio** [comment]
It seems you're still using LuaRocks 2.2.x. Please check with 2.3.0

Can we try using blackslashes in the paths instead? (slashes work on Windows, until they don't :smiley: )

```
install.bat /P Z:\sp\Dropbox\Windows\x86\luarocks /TREE C:\ste\x86\luarockstree /BIN Z:\sp\Dropbox\Windows\x86\luajit\src
```

Also, could you provide us with the full output of the install command, and also the Windows version?

**Comment by Tieske** [comment]
what strikes me is `/BIN Z:/sp/Dropbox/Windows/x86/luajit/src` as an option but the installer only checks `C:\ProgramData\Oracle\Java\javapath` which is weird. It should check the /BIN command location, or alternatively is checks the system path by default.

The path you provide is to a `/src` path, are you sure the executable is in there?

maybe also drop your system path value here.

**Comment by stepelu** [comment]
Oups, yes indeed that was the old 2.2.2 version.

However, the results 2.3 are identical:

Install attempt (now with backslashes, notice the luajit check):
```
C:\Users\sp\Downloads\luarocks-2.3.0-win32>Z:\sp\Dropbox\Windows\x86\luajit\src\
luajit.exe -e"print('There!')"
There!

C:\Users\sp\Downloads\luarocks-2.3.0-win32>install.bat /P Z:\sp\Dropbox\Windows\
x86\luarocks /TREE C:\ste\x86\luarockstree /BIN Z:\sp\Dropbox\Windows\x86\luajit
\src

C:\Users\sp\Downloads\luarocks-2.3.0-win32>rem=rem --[[
LuaRocks 2.3.x installer.


========================
== Checking system... ==
========================


Need admin privileges, now elevating a new process to continue installing...
Now exiting unprivileged installer
```

Spawns admin console:
```
LuaRocks 2.3.x installer.


========================
== Checking system... ==
========================


Admin privileges available for installing
Looking for Lua interpreter
    checking C:\ProgramData\Oracle\Java\javapath
Lua executable lua.exe, luajit.exe, lua51.exe or lua5.1.exe not found in Z:\sp\D
ropbox\Windows\x86\luajit\src

Failed installing LuaRocks. Run with /? for help.
Press any key to close this window...
```

Here is my env:
```
C:\Users\sp\Downloads\luarocks-2.3.0-win32>SET
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\sp\AppData\Roaming
asl.log=Destination=file
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=WINDOWS7-VM
ComSpec=C:\Windows\system32\cmd.exe
FP_NO_HOST_CHECK=NO
HOMEDRIVE=C:
HOMEPATH=\Users\sp
LOCALAPPDATA=C:\Users\sp\AppData\Local
LOGONSERVER=\\WINDOWS7-VM
NUMBER_OF_PROCESSORS=2
OS=Windows_NT
Path=C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windo
ws\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x
86)\Git\cmd;Z:\sp\Dropbox\Prj\scilua\head;Z:\sp\Dropbox\Prj\scilua\head\bin;C:\P
rogram Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program File
s (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\ProgramData\Oracle\Java\
javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\Syst
em32\WindowsPowerShell\v1.0\;C:\Users\sp\adb;Z:\sp\Dropbox\Bin;Z:\sp\Dropbox\Prj
\scilua\head;Z:\sp\Dropbox\Prj\scilua\head\bin;C:\Program Files (x86)\CMake\bin
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=3d04
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\sp\AppData\Local\Temp
TMP=C:\Users\sp\AppData\Local\Temp
USERDOMAIN=WINDOWS7-VM
USERNAME=sp
USERPROFILE=C:\Users\sp
VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools
\
windir=C:\Windows
windows_tracing_flags=3
windows_tracing_logfile=C:\BVTBin\Tests\installpackage\csilogfile.log
```

How can I obtain additional logging/debugging info? Thanks.

**Comment by ignacio** [comment]
When the installer uses the /BIN flag, it says it will check directories in the path but actually checks what is supplied. That is a bit confusing and probably should be cleaned up in future releases.

So that's why it says it is checking `C:\ProgramData\Oracle\Java\javapath` and stops. It actually checks 
this folder: `Z:\sp\Dropbox\Windows\x86\luajit\src`

@stepelu  Can you edit `install.bat` and uncomment [this line](https://github.com/keplerproject/luarocks/blob/master/install.bat#L85) ?

**Comment by stepelu** [comment]
Commenting out install.bat@L85 + print(status, type(status)):

```
C:\Users\sp\Downloads\luarocks-2.3.0-win32>rem=rem --[[
LuaRocks 2.3.x installer.


========================
== Checking system... ==
========================


net session >NUL 2>&1
2       number
PowerShell /? >NUL 2>&1
0       number
Need admin privileges, now elevating a new process to continue installing...
PowerShell -Command (New-Object -com 'Shell.Application').ShellExecute('C:\Users
\sp\AppData\Local\Temp\LuaRocks_Installer.bat', '', '', 'runas')

0       number
Now exiting unprivileged installer

C:\Users\sp\Downloads\luarocks-2.3.0-win32>
```

```
LuaRocks 2.3.x installer.


========================
== Checking system... ==
========================


net session >NUL 2>&1
0       number
Admin privileges available for installing
Looking for Lua interpreter
    checking C:\ProgramData\Oracle\Java\javapath
.\win32\tools\test -e "C:\ProgramData\Oracle\Java\javapath"
0       number
.\win32\tools\test -e "Z:\sp\Dropbox\Windows\x86\luajit\src\lua5.1.exe"
1       number
.\win32\tools\test -e "Z:\sp\Dropbox\Windows\x86\luajit\src\lua51.exe"
1       number
.\win32\tools\test -e "Z:\sp\Dropbox\Windows\x86\luajit\src\lua.exe"
1       number
.\win32\tools\test -e "Z:\sp\Dropbox\Windows\x86\luajit\src\luajit.exe"
1       number
Lua executable lua.exe, luajit.exe, lua51.exe or lua5.1.exe not found in Z:\sp\D
ropbox\Windows\x86\luajit\src

Failed installing LuaRocks. Run with /? for help.
Press any key to close this window...
```

```
C:\Users\sp\Downloads\luarocks-2.3.0-win32>.\win32\tools\test -e "Z:\sp\Dropbox\
Windows\x86\luajit\src\luajit.exe"

C:\Users\sp\Downloads\luarocks-2.3.0-win32>echo %ERRORLEVEL%
0
```

Maybe the spawned console executes from a different dir?

**Comment by ignacio** [comment]
Uhm, I'm at a bit of a loss here :smile: It seems like an issue with permissions, although I would have expected that running from an elevated shell wouldn't have that problem.

I would try the following this:
1) Can you try running `.\win32\tools\test -e "Z:\sp\Dropbox\Windows\x86\luajit\src\luajit.exe"` and checking ERRORLEVEL but running from an elevated command prompt?

2) Is the corresponding _lua51.dll_ file in the same place as _luajit.exe_ ? If not, try copying it there.


If all this also fails, can you provide a trace using [Process Monitor](https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx) ?

**Comment by stepelu** [comment]
Running as administrator, same issue:
```
C:\Users\sp\Downloads\luarocks-2.3.0-win32>install.bat /P Z:\sp\Dropbox\Windows\x86\luarocks /TREE C:\ste\x86\luarockstree /BIN Z:\sp\Dropbox\Windows\x86\luajit\src

C:\Users\sp\Downloads\luarocks-2.3.0-win32>rem=rem --[[
LuaRocks 2.3.x installer.


========================
== Checking system... ==
========================


net session >NUL 2>&1
0       number
Admin privileges available for installing
Looking for Lua interpreter
    checking C:\ProgramData\Oracle\Java\javapath
.\win32\tools\test -e "C:\ProgramData\Oracle\Java\javapath"
0       number
.\win32\tools\test -e "Z:\sp\Dropbox\Windows\x86\luajit\src\lua5.1.exe"
1       number
.\win32\tools\test -e "Z:\sp\Dropbox\Windows\x86\luajit\src\lua51.exe"
1       number
.\win32\tools\test -e "Z:\sp\Dropbox\Windows\x86\luajit\src\lua.exe"
1       number
.\win32\tools\test -e "Z:\sp\Dropbox\Windows\x86\luajit\src\luajit.exe"
1       number
Lua executable lua.exe, luajit.exe, lua51.exe or lua5.1.exe not found in Z:\sp\Dropbox\Windows\x86\luajit\src

Failed installing LuaRocks. Run with /? for help.

C:\Users\sp\Downloads\luarocks-2.3.0-win32>
```

I have done as suggested with process monitor.
I'd rather not make the file public, can you please provide an e-mail address to send the collected events to?

**Comment by stepelu** [comment]
(and yes, `lua51.dll` is there)

**Comment by ignacio** [comment]
If you're ok with it, you can send it to me and I'll take a look. My email address (gmail) is on my profile.

**Comment by ignacio** [comment]
Well, this is puzzling. The trace you provided shows `test.exe` being launched but it does not show the call to `QueryOpen Z:\sp\Dropbox\Windows\x86\luajit\src\luajit.exe`. A trace I captured on my machine does show that call.

I'm starting to wonder if this may have something to do with the location of _luajit.exe_. I see that you are running on a VM and that your Z drive may be a shared folder.
Let's try the following: copy your LuaJIT installation to a folder on your VM instead of a shared one and let's try again.

**Comment by stepelu** [comment]
Indeed, using a local folder make it work without issues. 
Strange, as I didn't have issues with the shared folders up to now, has `test.exe` been modified recently?

Anyway, is there any workaround that would allow me to trick `install.bat` to use the shared folder dir for `/BIN`, `/LIB`, `/INC` ?

**Comment by ignacio** [comment]
On a side note, @Tieske @hishamhm why are we using `test` in the installer? Wouldn't `io.open` do for testing existence of files?

**Comment by ignacio** [comment]
Last change regarding tools used on Windows was two years ago.

Can you test if this works? Change https://github.com/keplerproject/luarocks/blob/master/install.bat#L91 for `local cmd = [[if exist "]]..filename..[[" (exit /b 0) else (exit /b 1)]]`

**Comment by stepelu** [comment]
No it didn't, and neither did a check based on `io.open(...)`. 
As the latter definitely works with my Lua(JIT) interpreter I did some testing and have been able to determine that the issue only appears with the elevated prompt....and further investigation yielded:

http://superuser.com/a/245738

Really sorry for the noise, and thanks for the help, I had no idea such a clever feature was present in Windows 7!

**Comment by ignacio** [comment]
No problem at all. Thank you for investigating the issue and posting the solution here. I had no idea of those "subtleties".
