### ISSUE TITLE
Attempt to call a nil value

### ISSUE THREAD

**Issue by laserswald** [keplerproject/luarocks#500]
Got an error while trying to install luaposix. 

**Traceback:**

/usr/share/lua/5.3/luarocks/fs/lua.lua:738: attempt to call a nil value (field 'sumhexa')
stack traceback:
	/usr/share/lua/5.3/luarocks/fs/lua.lua:738: in function 'luarocks.fs.lua.get_md5'
	/usr/share/lua/5.3/luarocks/manif.lua:77: in function 'luarocks.manif.make_rock_manifest'
	/usr/share/lua/5.3/luarocks/build.lua:316: in function 'luarocks.build.build_rockspec'
	/usr/share/lua/5.3/luarocks/build.lua:369: in function 'luarocks.build.build_rock'
	(...tail calls...)
	/usr/share/lua/5.3/luarocks/build.lua:412: in function 'luarocks.build.run'
	(...tail calls...)
	[C]: in function 'xpcall'
	/usr/share/lua/5.3/luarocks/command_line.lua:207: in function 'luarocks.command_line.run_command'
	/usr/bin/luarocks:33: in main chunk
	[C]: in ?

**Comment by ignacio** [comment]
IIRC, this was fixed recently. See #495
LR breaks after lmd5 module is installed.

You can either apply this fix to your LuaRocks installation, temporarily uninstall lmd5 or add 
`fs_use_modules = false` to your `config.lua` file.

**Comment by laserswald** [comment]
Cool. Thanks.
