### ISSUE TITLE
I am having problem with installing libraries

### ISSUE THREAD

**Issue by quiloos39** [keplerproject/luarocks#501]
So here is my problem it says cl is not command and i am not sure how to fix it

i followed these steps and i added for path windows and luarocks

http://lua-users.org/wiki/BuildingLuaInWindowsForNewbies

<img src = "http://i.imgur.com/3lp6XWS.png" height = 300px width = 300px/>

Here i added path
<img src = "http://i.imgur.com/WzDLLk8.png" />

Lua and luarocks is working.
<img src = "http://i.imgur.com/V4qtPMm.png" />

But the problem is :
<img src = "http://i.imgur.com/Da8C31R.png"/>

So how can i fix it ?

**Comment by Tieske** [comment]
What compiler do you have installed? the `cl` command is for the Microsoft toolchain.

If you have MS toolchain, then try again from the VS command shell (it sets up all the paths such that the tooling can be found, including the `cl` command)

If you have the gcc toolchain (as part of TDM, or MinGW, etc) then you should install LuaRocks with the `/MW` commandline switch, to tell it to use the gcc toolchain, and not the MS toolchain.

hth

**Comment by quiloos39** [comment]
I have MinGW and i have installed gcc but not sure how to install cl

**Comment by Tieske** [comment]
in that case you need to reinstall luarocks and specify the `/MW` command switch, to tell it to use MinGW/gcc combo.

**Comment by Tieske** [comment]
did you succeed? can we close this?

**Comment by quiloos39** [comment]
Yes thanks.

**Comment by vintproykt** [comment]
Is there a way to fix this without MinGW/gcc?

**Comment by hishamhm** [comment]
@vintproykt without Mingw, you need Visual Studio. Then the solution is to use the VS Command Prompt, which has the compiler path properly set in its environment.
