### ISSUE TITLE
How to upgrade Luarocks in Linux Mint?

### ISSUE THREAD

**Issue by felipedaragon** [keplerproject/luarocks#505]
I tried both from apt-get and by downloading and compiling it and got some weird results. They are detailed at https://github.com/sailorproject/sailor/issues/89

**Comment by hishamhm** [comment]
Looks like you have both the old and new versions installed, and they're probably mixed up.

Remove the old LuaRocks 2.0.8 and install the latest release cleanly in `/usr/local`. Make sure you don't have any leftovers in `/usr/bin`, `/usr/lib/luarocks` and `/usr/share/lua`.

**Comment by felipedaragon** [comment]
Done! But now after make install, and when trying to run luarocks, I'm getting:

```bash: /usr/bin/luarocks: No such file or directory```

**Comment by felipedaragon** [comment]
./configure is returning:

Lua interpreter found: /usr/bin/lua...
Lua version detected: 5.1
lua found in $PATH: /usr/bin
Checking Lua includes... lua.h found in /usr/include/lua5.1/lua.h (Debian/Ubuntu)
wget found at /usr/bin
md5sum found at /usr/bin
Configuring for system... Linux
Configuring for architecture... i686
Existing installation detected.
Using previously configured rocks dir: /usr/local/lib/luarocks/rocks
Writing configuration...

Installation prefix: /usr/local
LuaRocks configuration directory: /usr/local/etc/luarocks
Using Lua from: /usr

Done configuring.
- Type 'make build' and 'make install':
  to install to /usr/local as usual.
- Type 'make bootstrap':
  to install LuaRocks in /usr/local as a rock.

**Comment by hishamhm** [comment]
And what did you do after `./configure`?

**Comment by hishamhm** [comment]
(This setup will install `luarocks` in `/usr/local/bin`, not `/usr/bin`. Maybe your shell has the outdated path cached? Try typing `rehash`).

**Comment by felipedaragon** [comment]
No rehash available! :P After ./configure I made the build, and then install with sudo like explained at https://github.com/keplerproject/luarocks/wiki/Installation-instructions-for-Unix

**Comment by hishamhm** [comment]
Then you should have `/usr/local/bin/luarocks` now.

**Comment by hishamhm** [comment]
(Apparently `hash -r` is the equivalent of `rehash` in Bash.)

**Comment by felipedaragon** [comment]
Weird. I closed the terminal and opened another and now it locates the luarocks command :)

**Comment by felipedaragon** [comment]
And you are right, it is under /usr/local/bin/luarocks. How can I see it's version?

**Comment by felipedaragon** [comment]
luarocks --version is returning:
/usr/local/bin/luarocks scm
LuaRocks main command-line interface

**Comment by felipedaragon** [comment]
Thanks! It looks like I sucessfully installed Sailor using the latest luarocks (though I will not have time to fully test right now). 

Updating manifest for /usr/local/lib/luarocks/rocks
sailor 0.5-4 is now built and installed in /usr/local (license: MIT)
