### ISSUE TITLE
Failed fetching manifest?

### ISSUE THREAD

**Issue by bigtunacan** [keplerproject/luarocks#507]
Setup luarocks and tried installing lapis `luarocks install lapis` this produces errors regarding failed fetching manifest.

Warning: Failed searching manifest: Failed fetching manifest for https://luarocks.org - Failed downloading https://luarocks.org/manifest - /Users/jseeley/.cache/luarocks/https___luarocks.org/manifest
mkdir: /Users/jseeley/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moonrocks-mirror_master_: Permission denied
mkdir: /Users/jseeley/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moonrocks-mirror_master_: Permission denied
mkdir: /Users/jseeley/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moonrocks-mirror_master_: Permission denied
Warning: Failed searching manifest: Failed creating temporary cache directory /Users/jseeley/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moonrocks-mirror_master_
mkdir: /Users/jseeley/.cache/luarocks/http___luafr.org_moonrocks_: Permission denied
mkdir: /Users/jseeley/.cache/luarocks/http___luafr.org_moonrocks_: Permission denied
mkdir: /Users/jseeley/.cache/luarocks/http___luafr.org_moonrocks_: Permission denied
Warning: Failed searching manifest: Failed creating temporary cache directory /Users/jseeley/.cache/luarocks/http___luafr.org_moonrocks_
mkdir: /Users/jseeley/.cache/luarocks/http___luarocks.logiceditor.com_rocks: Permission denied
mkdir: /Users/jseeley/.cache/luarocks/http___luarocks.logiceditor.com_rocks: Permission denied
mkdir: /Users/jseeley/.cache/luarocks/http___luarocks.logiceditor.com_rocks: Permission denied
Warning: Failed searching manifest: Failed creating temporary cache directory /Users/jseeley/.cache/luarocks/http___luarocks.logiceditor.com_rocks

**Comment by hishamhm** [comment]
looks like a permissions problem. Apparently you ran `luarocks install` as root (or sudo) but with environment variables set to your regular user.

Fix your system like this:

```
sudo chown -R jseeley /Users/jseeley/.cache/luarocks
```

Hope this helps!

**Comment by bigtunacan** [comment]
@hishamhm I updated the permissions as you have suggested here and then reran `luarocks install lapis`

This now results in the following error output

    Warning: falling back to curl - install luasec to get native HTTPS support
    Error: No results matching query were found.

**Comment by siffiejoe** [comment]
Lapis is only available for Lua 5.1. Do you maybe use a different version?

**Comment by bigtunacan** [comment]
@siffiejoe Thanks; this was the issue.  I was on Lua 5.2; after down grading I was able to get Lapis installed and working.

**Comment by sangeeth-ytel** [comment]
i installed lua5.1.exe on windows 7  from url : https://github.com/rjpcomputing/luaforwindows/releases   
i see luarocks also installed successfully . but when i run luarocks install <modulename> i get 

C:\Windows\system32>luarocks install ldoc
Warning: Failed searching manifest: Failed loading manifest: Failed fetching man
ifest for http://luarocks.org/repositories/rocks

Error: No results matching query were found.




can anyone help me

**Comment by hishamhm** [comment]
@sangeeth-ytel run again adding the `--verbose` flag; this should give you more information on what's going wrong.

**Comment by sangeeth-ytel** [comment]
the output with --verbose is the same 

C:\Windows\system32>luarocks install ldoc --verbose
Warning: Failed searching manifest: Failed loading manifest: Failed fetching man
ifest for http://luarocks.org/repositories/rocks

Error: No results matching query were found.

C:\Windows\system32>

**Comment by sangeeth-ytel** [comment]
can anyone help / guide me  how to create lua documentation (ldoc) on windows  7

**Comment by Tieske** [comment]
@sangeeth-ytel have you tried https://github.com/Tieske/luawinmulti ?
