### ISSUE TITLE
luarocks 3.0 wish list

### ISSUE THREAD

**Issue by xpol** [keplerproject/luarocks#508]
I have some whished features for luarocks 3.0:

1. unified rockspec name, rahter than `foo-x.y.z-1.rockspec`, how about just `rockspec` or `rockfile`, ( this goes further than #489 ) like npm's `package.json`
2. luarocks as a project package manager, like npm, read project depends form `rockfile` or `rockspec` and install them project locally in to some directory like `.rocks/<platform>/...`
3. support build static library (as #262 ) and install to project locally.
4. support corss compile for iOS and Android, this would great for develop corss platform games/apps for iOS and Android platforms.

**Comment by hishamhm** [comment]
Please post this as a discussion in the luarocks-developers mailing list, and not as a bug in the bugtracker. Thank you!
