### ISSUE TITLE
require"luarocks.install".run("name") not working

### ISSUE THREAD

**Issue by raingloom** [keplerproject/luarocks#513]
According to the docs, this should work. But it doesn't and I don't know why.
`lua -e require"luarocks.install".run"lpeg"`
```
lua: /usr/share/lua/5.3/luarocks/path.lua:31: assertion failed!
stack traceback:
	[C]: in function 'assert'
	/usr/share/lua/5.3/luarocks/path.lua:31: in function 'luarocks.path.root_dir'
	/usr/share/lua/5.3/luarocks/fs/lua.lua:826: in function 'luarocks.fs.check_command_permissions'
	/usr/share/lua/5.3/luarocks/install.lua:167: in function 'luarocks.install.run'
	(command line):1: in main chunk
	[C]: in ?
```
Running with Lua 5.3 on Arch Linux, LuaRocks installed from the distro's repositories.

**Comment by hishamhm** [comment]
Which docs? LuaRocks does not have a public API for user consumption like this. The docs in the comments are for the internal implementation.

In particular, LR has internal global state that needs to be set up by the launcher script before functions like this can work.

**Comment by raingloom** [comment]
[These docs on Luaforge](http://luarocks.luaforge.net/luadoc/modules/luarocks.install.html)

I guess I misinterpreted them then. However, it would make sense to include such functionality, wouldn't it? For example, apps with a bundled, self-conatined, LuaRocks setup could auto-fetch their dependencies.

Of course the command could be ran with os.execute or io.popen, but it would be nice (and imho more within the philosophy of Lua) to do installations without explicit system calls.
