### ISSUE TITLE
valua installation error

### ISSUE THREAD

**Issue by ounos** [keplerproject/luarocks#517]
Trying to install valua (_luarocks install valua_) returns an error:

> cp: cannot stat ‘valua.lua’: No such file or directory
> Error: Failed copying valua.lua

ubuntu 14.04, luarocks 2.0.8

**Comment by ignacio** [comment]
I remember this being reported a while ago [here](https://github.com/sailorproject/sailor/issues/88). Your LuaRocks version is way too old. Please install 2.3.0 from sources.

**Comment by ounos** [comment]
Yes, I think so. I am using the default ubuntu 14.04 lts package though.
