### ISSUE TITLE
"luarocks make" should pick latest rockspec automatically

### ISSUE THREAD

**Issue by mpeterv** [keplerproject/luarocks#518]
Currently `luarocks make` picks the rockspec automatically if it's the only one in current directory. It should also look in `rockspec/` and `rockspecs/` directories, and pick latest rockspec if there are several. That would make working with projects that like to store all rockspecs in repo easier.

**Comment by hishamhm** [comment]
I wonder if this is too magical, but yeah, I know where you got this idea from. :)

OTOH, I fully support the notion that LuaRocks is here to add all the layers of magic that Lua itself misses. ;)

**Comment by Tieske** [comment]
What if there are regular versions and an SCM version?

**Comment by siffiejoe** [comment]
IMHO it should pick the SCM one. It is always valid no matter whether you use a released zip package, the HEAD of a cloned git repository, or even a specific check-out or tag in the repository.

**Comment by mpeterv** [comment]
IIRC version comparison algorithm luarocks uses considers scm versions newer when comparing to regular versions, so it should just work.

**Comment by hishamhm** [comment]
> IIRC version comparison algorithm luarocks uses considers scm versions newer when comparing to regular versions, so it should just work.

correct
