### ISSUE TITLE
Improve error messages for rocks not found

### ISSUE THREAD

**Issue by Tieske** [keplerproject/luarocks#520]
See #519

Basically, installing `lapis` on Lua 5.2, simply says it cannot be found. It might be better that the error message displayed the constraints within it was not found. eg.

Lapis not found within constraints; Lua 5.2

Maybe someone else has a better idea, anyway a distinction in errormessage for 'not found' versus 'constraints not met'

**Comment by siffiejoe** [comment]
I think the `lua` dependency is special in that there are separate manifests for each Lua version. And in the Lua 5.2 manifest there *isn't* a `lapis`. To get the necessary information we'd have to include packages (at least the latest version) that don't have a 5.2 compatible rock.

**Comment by hishamhm** [comment]
What @siffiejoe said is correct. With the existing manifest, there's no way to know the difference between "the rock doesn't exist" and "the rock doesn't exist for your Lua version"...

**Comment by ignacio** [comment]
It is not an ideal solution, and we know that people don't read, but, could we see if we can get away with adding a message, directing users to LuaRocks site when a search has been made and no results were found? Maybe a special page or some docs, stating why does some rock that is known to exist does not appear as a result when searching.

**Comment by Tieske** [comment]
We know we're looking for 5.2. So can we add a message listing the constraints we looked for? And additionally add a message like; 

"Please check the package name and dependencies, or look it up on luarocks.org."

**Comment by mpeterv** [comment]
The constraints don't mention 'lua' explicitly. Constraints, when searching a version of some rock, include only restrictions for the rock itself, but not for its dependencies or other installed or provided rocks. So just printing constraints doesn't help.

**Comment by mpeterv** [comment]
But I think it should be possible to look through other manifests when the appropriate one doesn't contain the rock, and print supported Lua versions.

A similar, more rare case is when the rock exists for installed Lua version but no versions match constraints. The message should say that existing versions don't match constraints instead of "no results".

**Comment by Tieske** [comment]
don't know the code, my thought simply was; if we're searching the 5.2 manifest, then we know we're doing 5.2. No?

**Comment by ignacio** [comment]
I would go with @Tieske and just add a message pointing users to LuaRocks. For instance, my LR is 2.3.0 + Lua 5.1. `base2base` is a module for 5.3 only. I'd show:

```
luarocks search base2base

No compatible rocks found, or the rock does not exist.
Please check the rock's name or make sure the rock exists and is compatible with Lua 5.1 by visiting:
https://luarocks.org/search?q=base2base
```

Or something like that.

Other manifests could be looked up, I haven't looked at the code in detail, but I see cases where an [unversioned manifest](https://github.com/keplerproject/luarocks/blob/master/src/luarocks/manif.lua#L117) can be used and wrong results could be returned (granted, that should not happen with the main repository).

**Comment by hishamhm** [comment]
@ignacio's message is really good. It does give me a tiny bit of a `Bad command or filename` vibe (which I always found to be a confusing error message), but the explanation you added in the following lines more than makes up for it, and the URL is a great touch (especially nowadays that they are clickable in modern terminals).

**Comment by Tieske** [comment]
:+1:
