### ISSUE TITLE
Can not install "lab" package

### ISSUE THREAD

**Issue by Windyfbin** [keplerproject/luarocks#529]
Hi. I'm trying to install package using luarocks
$ luarocks install lab
However, I get
Error: No results matching query were found.
Plz help solve it. 
Thanks

**Comment by siffiejoe** [comment]
Are you sure that `lab` is in the default repository? A quick search on https://luarocks.org/ doesn't find anything relevant ...
Maybe you need to select another repository/manifest using the `--server` command line flag?

**Comment by Windyfbin** [comment]
i'm a newbie, so i just do follow this
http://torch5.sourceforge.net/manual/newbieTutorial.html
i want to install "lab" package which contains a wide variety of commands for manipulating Tensors.

**Comment by ignacio** [comment]
It seems that those instructions are outdated. Torch support is here: http://torch.ch/support.html

**Comment by Windyfbin** [comment]
Many thanks !. In torch 7. We have "Mathematical operations" package instead of "lab"
