### ISSUE TITLE
Placing luarocks.bat in $prefix\bin on Windows?

### ISSUE THREAD

**Issue by Lekensteyn** [keplerproject/luarocks#530]
The mpeterv/hererocks project makes it easy to install different Lua versions and LuaRocks at once. On Linux and OS X the lua and luarocks executables are installed to `$prefix/bin`. On Windows however (using `install.bat`), the situation is different.

LuaRocks can only be installed in a clean directory (the installer gives two options for existing directories: wipe it or abort). Furthermore, `luarocks.bat` does not end up in the Lua bindir (`$prefix\bin`), but in the LuaRocks directory.

In https://github.com/mpeterv/hererocks/pull/16#issuecomment-202352275, @mpeterv noted that the luarocks.bat scripts can be relocated (for example, to `$prefix\bin`). Is this something that can be relied on?

**Comment by ignacio** [comment]
I think it could be said so, yes. Everything in `luarocks.bat` uses full paths.

On the other hand, I don't think it will change its location soon. There was an extensive discussion about the current layout (see #257, #265, maybe others as well).

Also, I think that [luawinmulti](https://github.com/Tieske/luawinmulti) is relevant to what you're trying to achieve. Also, look at [lua-appveyor-example](https://github.com/ignacio/lua-appveyor-example) for some example installation gymnastics :smile:

**Comment by Lekensteyn** [comment]
Ok, thanks for the confirmation.

Actually the goal is not just installing Lua on Windows, but to make HereRocks install Lua on Windows. HereRocks already works with Linux and OS X (reducing the need to learn and install different tools). With this information we can be sure that moving/copying the .bat file stays supported :-)
