### ISSUE TITLE
bin-scripts not packed by pack command

### ISSUE THREAD

**Issue by Tieske** [keplerproject/luarocks#532]
currently installing `pe-parser` fails. The rock lacks the bin script. 

I tried recreating the rock, but it consistently fails to pack the bin scripts as well, rendering the rock created useless, as it fails to install when it cannot find the bin script

**Comment by mpeterv** [comment]
pe-parser-0.5.0-1.rockspec uses https://github.com/Tieske/pe-parser/archive/version_0.5.tar.gz which was created in 2013 and lacks bin directory (https://github.com/Tieske/pe-parser/releases).

**Comment by mpeterv** [comment]
@Tieske can this be closed? Does it work for you if you point the rockspec to a tarball containing bin/?

**Comment by mpeterv** [comment]
@Tieske ping...
