### ISSUE TITLE
Incorrect MSVC setup command for VS 2012 x64

### ISSUE THREAD

**Issue by mpeterv** [keplerproject/luarocks#534]
As you can see here: https://ci.appveyor.com/project/ignacio/lua-appveyor-example/build/0.0.1.203-test/job/snkhgm22rgwksmar#L527 vcvarsall.bat for VS 2012 fails when argument is `amd64`.

The build still passes because a script executed same vcvarsall.bat passing `x86_amd64` instead beforehand. That appears to be working for other VS versions, too. I think that `amd64` should be replaced by `x86_amd64` in install.bat, or the latter should be used as fallback if amd64 fails.

**Comment by ignacio** [comment]
@xpol did a lot of research on this matter so he could comment on this, but iirc, `x86_amd64` is used for cross compiling (see #443)

The VS 2012 installation on appveyor does not have what is needed. I think that they omitted to install x64 support. I don't have a working VS2012 install so I cannot test (I uninstalled it) but it left a lot of files on my drive :) So, part of the contents of `vcvarsall.bat` are:

```
@echo off
if "%1" == "" goto x86
if not "%2" == "" goto usage

if /i %1 == x86       goto x86
if /i %1 == amd64     goto amd64
if /i %1 == x64       goto amd64
if /i %1 == arm       goto arm
if /i %1 == x86_arm   goto x86_arm
if /i %1 == x86_amd64 goto x86_amd64
goto usage

:x86
if not exist "%~dp0bin\vcvars32.bat" goto missing
call "%~dp0bin\vcvars32.bat"
goto :SetVisualStudioVersion

:amd64
if not exist "%~dp0bin\amd64\vcvars64.bat" goto missing
call "%~dp0bin\amd64\vcvars64.bat"
goto :SetVisualStudioVersion
````

I should fix lua-appveyor-example, but I don't think this is an issue with LuaRocks.

**Comment by mpeterv** [comment]
Well, x64 support is there, or the build would fail, it's just implemented by 32bit compiler. It's kind of cross-compiling because compiler and compiled programs have different bitness, but not really because compiled program have same architecture as host (and as lua binary). I think that LuaRocks should support this:

* Need to build x86 rocks because Lua is x86 -> pass "x86" or ""
* Need to build x64 rocks because Lua is x64 ->
  - If there is x64 compiler targeting x64 pass "amd64"
  - If there is x86 compiler targeting x64 pass "x86_amd64"

**Comment by ignacio** [comment]
Yes, indeed. However, I think that wanting to cross compile (the third option on your list) is a very particular case that can currently be handled by using the /MSVC flag when installing LuaRocks, so the user is responsible for setting up the environment using the right flags.
So, yes, LuaRocks supports it.

However... I'm under the assumption that if you installed Visual Studio on a 64bit machine, you'd also installed the 64 bit compiler. Maybe that's not the case, and it would be easier for new users to just use x86 and x86_amd64 (ie, always use the 32 bit compiler and change the target). I really don't know :)

**Comment by mpeterv** [comment]
I don't know either and don't have a Windows installation to test it =( It's possible that having only x86 compiler targeting x64 is just a rare situation that only happens on appveyor.

**Comment by mpeterv** [comment]
I've got an x64 notebook with Windows 10 and installed Visual Studio 12 Express. Indeed, there are no x64 tools, just x86 and x86_amd64, so luarocks install is broken if Lua is x64. I've built Lua with bleeding edge version of hererocks that uses VSINSTALL\bin\amd64\vcvars64.bat and VSINSTALL\bin\x86_amd64\vcvarsx86_amd64.bat, whichever exists.

**Comment by xpol** [comment]
MS doc says there is `vcvarsall.bat` for VS2012 and `x86_amd64` is for cross compiling.
See: https://msdn.microsoft.com/en-us/library/x4d2c09s(v=vs.100).aspx

Does LuaRocks support that a **x64 Lua** installed on a **x86** Windows, which never get running on the x86 machine?

If yes, I think we should x64 cross compiler support for MSVC setup command.

**Comment by mpeterv** [comment]
@xpol we've discussed this above with @ignacio, the problem is with x64 Lua on an x64 machine. Common editions of Visual Studio 2012 don't provide an x64 compiler (amd64), in which case it's necessary to use an x86 compiler targeting x64 (x86_amd64), which runs using WOW64 on x64 Windows.

**Comment by xpol** [comment]
OK, I got it.
So we need to support cross compiling if native compiler is not installed but cross compiler targeting are installed.

```Lua
    local vcvars_bats = {
      x86 = {
        "bin\\vcvars32.bat", -- prefers native compiler
        "bin\\amd64_x86\\vcvarsamd64_x86.bat"
      },
      x86_64 = {
        "bin\\amd64\\vcvars64.bat", -- prefers native compiler
        "bin\\x86_amd64\\vcvarsx86_amd64.bat"
      }
    }
    assert(vcvars_bats[vars.UNAME_M], "vars.UNAME_M: only x86 and x86_64 are supported")
    for _, bat in ipairs(vcvars_bats[vars.UNAME_M]) do
    	local full_path = vcdir .. bat
      if exists(full_path) then
        return ('call "%s"'):format(full_path)
      end
    end
```

I'll make a PR when I have tested it.
