### ISSUE TITLE
#include <lua.h> vs #include "lua.h"

### ISSUE THREAD

**Issue by daurnimator** [keplerproject/luarocks#536]
Should C modules use `#include <lua.h>` or `#include "lua.h"`?
`LUA_INCDIR` seems to exist to enable the latter.

**Comment by siffiejoe** [comment]
If your module brings its own `lua.h`, then it's easier to use the latter. Otherwise it doesn't matter. `LUA_INCDIR` is needed for both if Lua's header files are installed in a non-standard location (or if you have multiple Lua installations in standard locations).

**Comment by daurnimator** [comment]
> If your module brings its own lua.h, then it's easier to use the latter. 

Why would a lua module *ever* bring it's own lua.h?

> Otherwise it doesn't matter. LUA_INCDIR is needed for both if Lua's header files are installed in a non-standard location (or if you have multiple Lua installations in standard locations).

Actually I had an issue where my LUA_INCDIR was /usr/include, but I *didn't* want to include the /usr/include directory for other reasons..... from there I started wondering.

**Comment by siffiejoe** [comment]
> Why would a lua module ever bring it's own lua.h?

I maintain two rocks that bundle some of Lua's source and header files (not `lua.h`, though):
https://github.com/siffiejoe/lua-getsize
https://github.com/siffiejoe/lua-lbci

> Actually I had an issue where my LUA_INCDIR was /usr/include, but I didn't want to include the /usr/include directory for other reasons..... from there I started wondering.

Why? Somehow the compiler needs to find the Lua include files, and `/usr/include` probably is in your compiler's default search path anyway.

**Comment by daurnimator** [comment]
> Why? Somehow the compiler needs to find the Lua include files, and /usr/include probably is in your compiler's default search path anyway.

I was messing with musl. It has it's own system headers in /usr/lib/musl/include

**Comment by siffiejoe** [comment]
So you basically need a way to put additional include directories *before* the Lua include directory?! Right now that's not possible with the `builtin` build mode, but of course easy with the `make` based build mode.

**Comment by hishamhm** [comment]
```
       -Idir
           Add the directory dir to the head of the list of directories to be
           searched for header files.  This can be used to override a system
           header file, substituting your own version, since these directories
           are searched before the system header file directories.  However,
           you should not use this option to add directories that contain
           vendor-supplied system header files (use -isystem for that).  If
           you use more than one -I option, the directories are scanned in
           left-to-right order; the standard system directories come after.
```

If `-I/usr/include` causes problems for you just set `LUA_INCDIR` to something else.

**Comment by daurnimator** [comment]
that was only what caused me to investigate.

The actual issue I asked here was whether lua C modules should prefer `<lua.h>` or `"lua.h"`. I'd like to be consistent across my modules (and have something to refer to when sending pull requests etc).

**Comment by hishamhm** [comment]
In any case, this is not a LuaRocks bug, so the issue tracker is not the right place for this discussion. Try lua-l maybe?
