### ISSUE TITLE
How to access installed data in build.copy_directories?

### ISSUE THREAD

**Issue by vadi2** [keplerproject/luarocks#540]
I've scoured all through documentation, and I haven't found a way to access rock data installed via build.copy_directories in my code.

**Comment by vadi2** [comment]
Some background - my code needs to load some JSON data before it can work, and I've gotten it to install on the system as part of the copy_directories directive. All other ones don't seem correct as they only deal with code, not data.

**Comment by siffiejoe** [comment]
See https://github.com/hishamhm/datafile.

**Comment by daurnimator** [comment]
Related: https://github.com/keplerproject/luarocks/issues/305

**Comment by vadi2** [comment]
Thank you, datafile worked great.
