### ISSUE TITLE
wget fails when installing a rock through a firewall

### ISSUE THREAD

**Issue by wdwickar** [keplerproject/luarocks#542]
I'm trying to install distlearn.  I've set my proxy variables as noted, testing them out with direct **wget** commands.  It appears that something in the luarocks execution sequence doesn't properly export the proxy shell variables: with the straightforward command
```
sudo luarocks install autograd
```
I get the error
```
Missing dependencies for autograd:
totem 

Using https://raw.githubusercontent.com/torch/rocks/master/totem-0-0.rockspec... switching to 'build' mode
Cloning into 'torch-totem'...
fatal: unable to connect to github.com:
github.com[0: 192.30.252.123]: errno=Connection timed out


Error: Failed installing dependency: https://raw.githubusercontent.com/torch/rocks/master/totem-0-0.rockspec - Failed cloning git repository.
```

I've tried downloading the repos (autograd, thrift, dataset, ipc) with **git clone**, and I now get:
```
$ luarocks install distlearn
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/torch/rocks/master - Failed downloading https://raw.githubusercontent.com/torch/rocks/master/manifest - /home/hadoop/.cache/luarocks/https___raw.githubusercontent.com_torch_rocks_master/manifest
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master - Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/manifest - /home/hadoop/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moonrocks-mirror_master/manifest
```
... and ...
```
$ luarocks install distlearn
Installing https://raw.githubusercontent.com/torch/rocks/master/distlearn-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/distlearn-scm-1.rockspec... switching to 'build' mode

Missing dependencies for distlearn:
ipc 
regress 

Using https://raw.githubusercontent.com/torch/rocks/master/ipc-scm-1.rockspec... switching to 'build' mode

Missing dependencies for ipc:
regress 

Using https://raw.githubusercontent.com/torch/rocks/master/regress-scm-1.rockspec... switching to 'build' mode
Cloning into 'regress'...
fatal: unable to connect to github.com:
github.com[0: 192.30.252.131]: errno=Connection timed out


Error: Failed installing dependency: https://raw.githubusercontent.com/torch/rocks/master/ipc-scm-1.rockspec - Failed installing dependency: https://raw.githubusercontent.com/torch/rocks/master/regress-scm-1.rockspec - Failed cloning git repository.
```

Am I diving down the wrong rabbit hole?
What do I need to fix?  Is there more diagnostic information I need to get?

BTW, I'm happily running AlexNet on torch; now I want to use some of the distlearn facilities to expand on the model.

**Comment by wdwickar** [comment]
It appears that luarocks has a hidden assumption that the standard git protocol suffices.  Since I'm behind a firewall, I need to reconfigure the applicable proxies, but luarocks doesn't seem to have such a facility.
I finally gave up and consulted my local Powers That Be.  One of them knew to reconfigure git to use HTTPS instead:

`sudo git config --global url."https://".insteadOf git://`

**Comment by hishamhm** [comment]
Indeed, we don't try to auto-configure every SCM tool backend. Perhaps this information could be added to the documentation page in the wiki?

https://github.com/keplerproject/luarocks/wiki/LuaRocks-through-a-proxy

**Comment by daurnimator** [comment]
`git` (like most programs) supports environmental variables such as `http_proxy` and `NO_PROXY`. I'm surprised they're not passed through?

**Comment by ignacio** [comment]
They should be. That was added recently.

**Comment by hishamhm** [comment]
I think the issue here, more than making https go through the proxy, was to tell git to switch from its own transport protocol to https. It seems specific enough to me so that it can be dealt via documentation rather than implementation (we can't make all git accesses go through https, since not all Git servers in the world support that).

**Comment by hishamhm** [comment]
I added @wdwickar's solution to the wiki link above, so I believe this can be closed.

**Comment by wdwickar** [comment]
The solution is from @threevi; I'm just the one who tripped over the problem and characterized it.
