### ISSUE TITLE
[ubuntu] torch/install/share/lua/5.1/trepl/init.lua:384: module 'dpnn' not found

### ISSUE THREAD

**Issue by psakamoori** [keplerproject/luarocks#547]
I am trying to run "openface" module as explained http://cmusatyalab.github.io/openface/demo-3-classifier/ 

Installed luarocks, luajit as explained in http://torch.ch/docs/getting-started.html#_

Seeing below error : "No LuaRocks module found for dpnn"

psakhamo@ironmaiden:~/torch/openface$ ./batch-represent/main.lua -outDir data/mydataset/raw/feature -data data/mydataset/raw/align
/home/psakhamo/torch/install/bin/luajit: /home/psakhamo/torch/install/share/lua/5.1/trepl/init.lua:384: module 'dpnn' not found:No LuaRocks module found for dpnn
        no field package.preload['dpnn']
        no file '/home/psakhamo/.luarocks/share/lua/5.1/dpnn.lua'
        no file '/home/psakhamo/.luarocks/share/lua/5.1/dpnn/init.lua'
        no file '/home/psakhamo/torch/install/share/lua/5.1/dpnn.lua'
        no file '/home/psakhamo/torch/install/share/lua/5.1/dpnn/init.lua'
        no file './dpnn.lua'
        no file '/home/psakhamo/torch/install/share/luajit-2.1.0-beta1/dpnn.lua'
        no file '/usr/local/share/lua/5.1/dpnn.lua'
        no file '/usr/local/share/lua/5.1/dpnn/init.lua'
        no file '/home/psakhamo/.luarocks/lib/lua/5.1/dpnn.so'
        no file '/home/psakhamo/torch/install/lib/lua/5.1/dpnn.so'
        no file '/home/psakhamo/torch/install/lib/dpnn.so'
        no file './dpnn.so'
        no file '/usr/local/lib/lua/5.1/dpnn.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'error'
        /home/psakhamo/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
        ./batch-represent/main.lua:12: in main chunk
        [C]: in function 'dofile'
        ...hamo/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

When I run this "luarocks list", I see "dpnn"

Installed rocks:
----------------
argcheck
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
csvigo
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
cudnn
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
cunn
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
cunnx
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
cutorch
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
cwrap
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
dok
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
dpnn
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
env
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
fftw3
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
gnuplot
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
graph
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
graphicsmagick
   1.scm-0 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
image
   1.1.alpha-0 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
lua-cjson
   2.1devel-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
luaffi
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
luafilesystem
   1.6.3-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
moses
   1.4.0-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
nn
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
nngraph
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
nnx
   0.1-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
optim
   1.0.5-0 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
paths
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
penlight
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
qtlua
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
qttorch
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
signal
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
sundown
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
sys
   1.1-0 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
threads
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
torch
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
trepl
   scm-1 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks
xlua
   1.0-0 (installed) - /home/psakhamo/torch/install/lib/luarocks/rocks

Also, I see "dpnn" folder under

torch/install/lib/luarocks/rocks$ ls
argcheck  cudnn  cunnx    cwrap  dpnn  fftw3    graph           image      luaffi         manifest  nn       nnx    paths     qtlua    signal   sys      torch  xlua
csvigo    cunn   cutorch  dok    env   gnuplot  graphicsmagick  lua-cjson  luafilesystem  moses     nngraph  optim  penlight  qttorch  sundown  threads  trepl

My $PATH looks like below
/home/psakhamo/torch/install/bin:/home/psakhamo/torch/install/bin:/home/psakhamo/bin:/home/psakhamo/torch/install/bin:/home/psakhamo/torch/install/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/cuda-7.0/bin:/home/psakhamo/torch/install/lib:/home/psakhamo/torch/install/lib/luarocks/rocks:/usr/local/lib:

Is there anything I am doing wrong here...Can some one help here

**Comment by mpeterv** [comment]
What does `luarocks show dpnn` print?

**Comment by psakamoori** [comment]
psakhamo@ironmaiden:~/torch$ luarocks show dpnn

dpnn scm-1 - deep extensions to nn Modules and Criterions

sharedClone, type, outside, updateGradParameters, Serial, Inception, etc.

License:        BSD
Homepage:       https://github.com/Element-Research/dpnn
Installed in:   /home/psakhamo/torch/install

Modules:
        libluajit (/home/psakhamo/torch/install/lib/lua/5.1/libluajit.so)

Depends on:
        xlua
        moses
        torch
        sys
        nn
        cwrap
        luaffi
        paths
        nnx

**Comment by siffiejoe** [comment]
That:

> Modules:
> libluajit (/home/psakhamo/torch/install/lib/lua/5.1/libluajit.so)

doesn't look right. It seems that the build system of dpnn is broken. Since dpnn is implemented as a collection of Lua modules, you would expect something like:

> Modules:
> dpnn (/home/psakhamo/torch/install/share/lua/5.1/dpnn/init.lua)
> dpnn.Module (/home/psakhamo/torch/install/share/lua/5.1/dpnn/Module.lua)
> dpnn.Container (/home/psakhamo/torch/install/share/lua/5.1/dpnn/Container.lua)
> dpnn.Sequential (/home/psakhamo/torch/install/share/lua/5.1/dpnn/Sequential.lua)
> -- etc.

**Comment by psakamoori** [comment]
I see, thank you for looking into.

As shown I dnt see "dpnn" inside "torch/install/lua/5.1"

psakhamo@ironmaiden:~/torch/install/lib/lua/5.1$ ls
cjson.so  ffi.so  libcsvigo.so  libcutorch.so  libjpeg.so    libnnx.so    libpng.so  libqtcore.so  libqtide.so  libqttorch.so     libqtwidget.so  libsundown.so  libTHCUNN.so  libthreads.so  readline.so
ffi       lfs.so  libcunnx.so   libimage.so    libluajit.so  libpaths.so  libppm.so  libqtgui.so   libqtsvg.so  libqtuiloader.so  libsignal.so    libsys.so      libTHNN.so    libtorch.so    treplutils.so

Then I followed below steps.
psakhamo@ironmaiden:~/torch$ luarocks make rocks/dpnn-scm-1.rockspec
cmake -E make_directory build;
cd build;
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/psakhamo/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1";
make

-- Found readline library
-- LuaJIT Target: x64
-- LuaJIT target x64
-- Configuring done
-- Generating done
-- Build files have been written to: /home/psakhamo/torch/build
[  3%] Built target minilua
[ 26%] Built target buildvm
[ 61%] Built target libluajit
[100%] Built target luajit
cd build && make install
[  3%] Built target minilua
[ 26%] Built target buildvm
[ 61%] Built target libluajit
[100%] Built target luajit
Install the project...
-- Install configuration: "Release"
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/include/luaconf.h
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/include/lua.h
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/include/lauxlib.h
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/include/lualib.h
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/include/lua.hpp
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/include/luajit.h
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/lib/libluajit.so
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/bin/luajit
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/jit/bc.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/jit/v.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/jit/dump.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/jit/dis_x86.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/jit/dis_x64.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/jit/dis_arm.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/jit/dis_ppc.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/jit/dis_mips.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/jit/dis_mipsel.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/jit/bcsave.lua
-- Up-to-date: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/jit/bc.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/jit/p.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/jit/zone.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/jit/vmdef.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/manif.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/refresh_cache.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/admin_remove.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/lint.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/cache.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/install.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/config_cmd.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/pack.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/upload.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/manif_core.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/write_rockspec.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/require.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/search.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/add.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/build/builtin.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/build/command.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/build/make.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/build/cmake.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/fs.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/index.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/loader.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/repos.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/path_cmd.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/download.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/dir.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/cfg.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/purge.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/command_line.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/fetch/hg.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/fetch/svn.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/fetch/git_file.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/fetch/git_https.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/fetch/hg_http.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/fetch/hg_https.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/fetch/git_http.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/fetch/cvs.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/fetch/git.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/fetch/sscm.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/fetch/hg_ssh.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/validate.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/path.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/tools/patch.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/tools/tar.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/tools/zip.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/build.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/upload/api.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/upload/multipart.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/util.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/deps.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/show.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/persist.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/make_manifest.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/make.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/list.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/fetch.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/new_version.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/unpack.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/fs/win32/tools.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/fs/unix.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/fs/lua.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/fs/win32.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/fs/unix/tools.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/remove.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/help.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/type_check.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/doc.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/share/lua/5.1/luarocks/site_config.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/etc/luarocks/config.lua
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/bin/luarocks
-- Installing: /home/psakhamo/torch/install/lib/luarocks/rocks/dpnn/scm-1/bin/luarocks-admin
Updating manifest for /home/psakhamo/torch/install/lib/luarocks/rocks
dpnn scm-1 is now built and installed in /home/psakhamo/torch/install/ (license: BSD)

Still , see the issue.
Really, I could not get to bottom of this one. I faced simillar issue with "cvsigo.so" package (could able to fix that with luarocks make "cvs....rockspec".
But not for this one.

Am I doing some thing fundamentally wrong here...How to fix this? 

Thank you for your help

**Comment by siffiejoe** [comment]
It seems that the rockspec is picking up the Torch `CMakeLists.txt` file instead of the one for dpnn.

**Comment by psakamoori** [comment]
Thanks siffiejoe.
It fixed the issue..Thank you

**Comment by rremani** [comment]
Hi guys,
I am able to install dpnn but getting an error while calling the library. Below is the message I got while installing:
root@570ccca0a1d2:/digits/dpnn# **luarocks make rocks/dpnn-scm-1.rockspec** 
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/usr/local/torch/install/" -DCMAKE_INSTALL_PREFIX="/usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1" && make
   
-- The C compiler identification is GNU 4.9.4
-- The CXX compiler identification is GNU 4.9.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /usr/local/torch/install
-- Configuring done
-- Generating done
-- Build files have been written to: /digits/dpnn/build
cd build && make install
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/SpatialBinaryLogisticRegression.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/BinaryClassReward.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/BinaryLogisticRegression.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/OneHot.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/FireModule.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/NCECriterion.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/SpatialRegionDropout.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/CAddTensorTable.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Constant.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/ModuleCriterion.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Convert.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/VRClassReward.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Serial.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/SpatialMaxPooling.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Collapse.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/LookupTable.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/ReinforceBernoulli.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/ReverseTable.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Module.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/ReinforceCategorical.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Inception.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Kmeans.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/init.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/BatchNormalization.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Sequential.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/SpatialConvolutionMM.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/ReinforceNormal.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Clip.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/PrintSize.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/ReinforceGamma.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Criterion.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/SpatialBinaryConvolution.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/SpatialBatchNormalization.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/ZipTable.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/ParallelTable.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/WhiteNoise.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/SpatialFeatNormalization.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/CategoricalEntropy.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/ArgMax.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/SpatialUniformCrop.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/SpatialConvolution.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/SpatialGlimpse.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/NCEModule.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/ZipTableOneToMany.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Dictionary.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Reinforce.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Container.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/TotalDropout.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/SimpleColorTransform.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/PCAColorTransform.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/test.lua
Updating manifest for /usr/local/torch/install/lib/luarocks/rocks
dpnn scm-1 is now built and installed in /usr/local/torch/install/ (license: BSD)



Now I get the below error while I call it:
root@570ccca0a1d2:/digits/dpnn# th
 
  ______             __   |  Torch7 
 /_  __/__  ________/ /   |  Scientific computing for Lua. 
  / / / _ \/ __/ __/ _ \  |  Type ? for help 
 /_/  \___/_/  \__/_//_/  |  https://github.com/torch 
                          |  http://torch.ch 
	
th> **require 'dpnn'**
/usr/local/torch/install/share/lua/5.1/trepl/init.lua:384: /usr/local/torch/install/share/lua/5.1/trepl/init.lua:384: /usr/local/torch/install/share/lua/5.1/torch/init.lua:102: bad argument #2 (invalid parent class name nn.Decorator)
stack traceback:
	[C]: in function 'error'
	/usr/local/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	[string "_RESULT={require 'dpnn'}"]:1: in main chunk
	[C]: in function 'xpcall'
	/usr/local/torch/install/share/lua/5.1/trepl/init.lua:652: in function 'repl'
	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00406670	
                                                                      [0.0344s]	
th>

**Comment by sdiptapaul** [comment]
If you install torch using http://torch.ch/docs/getting-started.html 

Then do again -
luarocks install torch
luarocks install nn
luarocks install dpnn
dpnn should work. I had same problem and resolved now.

**Comment by sdiptapaul** [comment]
also do
luarocks install torchx
and then
th>dpnn.test()
should pass all tests

**Comment by tjan90** [comment]
> If you install torch using http://torch.ch/docs/getting-started.html
> 
> Then do again -
> luarocks install torch
> luarocks install nn
> luarocks install dpnn
> dpnn should work. I had same problem and resolved now.

i tried this but nn and dpnn comaand was not found
