### ISSUE TITLE
Could not find lua.

### ISSUE THREAD

**Issue by codeliger** [keplerproject/luarocks#557]
LuaRocks 2.3.x installer.

========================
== Checking system... ==
========================

Admin privileges available for installing
Looking for Lua interpreter
    checking C:\Program Files (x86)\Intel\iCLS Client
    checking C:\Program Files\Intel\iCLS Client
    checking C:\Windows\system32
    checking C:\Windows
    checking C:\Windows\System32\Wbem
    checking C:\Windows\System32\WindowsPowerShell\v1.0
    checking C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
    checking C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
    checking C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
    checking C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
    checking C:\php-7.0.6-Win32-VC14-x64
    checking C:\Program Files\nodejs
    checking C:\server C:\server\bin\mariadb
    checking C:\Program Files (x86)\Microsoft VS Code
    checking C:\Users\Benjamin Tiessen\AppData\Roaming\npm
    checking c:\lua5.1.2
    checking c:\lua
    checking c:\kepler\1.1
Could not find Lua. See /? for options for specifying the location of Lua, or installing a bundled copy of Lua 5.1.

Failed installing LuaRocks. Run with /? for help.
Press any key to close this window...

**Comment by codeliger** [comment]
I am running luarocks from this directory C:\luarocks-2.3.0-win32 with the default file/folder structure

**Comment by ignacio** [comment]
Hi Ben. How do you invoke the install script? With which flags?

**Comment by codeliger** [comment]
@ignacio I tried double clicking the .bat file assuming that was the "default configuration" since there was no specification how to invoke the mentioned "default configuration".

**Comment by ignacio** [comment]
To install the bundled Lua copy (note that it is Lua 5.1) you need to run `install /L`. Installing the bundled Lua copy is not the default option, so you have to state that explicitly with the `/L` flag.

**Comment by codeliger** [comment]
```
============================
== LuaRocks is installed! ==
============================


You may want to add the following elements to your paths;
Lua interpreter;
  PATH     :   C:\Program Files (x86)\LuaRocks
  PATHEXT  :   .LUA
LuaRocks;
  PATH     :   C:\Program Files (x86)\LuaRocks
  LUA_PATH :   C:\Program Files (x86)\LuaRocks\lua\?.lua;C:\Program Files (x86)\LuaRocks\lua\?\init.lua
Local user rocktree (Note: %APPDATA% is user dependent);
  PATH     :   %APPDATA%\LuaRocks\bin
  LUA_PATH :   %APPDATA%\LuaRocks\share\lua\5.1\?.lua;%APPDATA%\LuaRocks\share\lua\5.1\?\init.lua
  LUA_CPATH:   %APPDATA%\LuaRocks\lib\lua\5.1\?.dll
System rocktree
  PATH     :   C:\Program Files (x86)\LuaRocks\systree\bin
  LUA_PATH :   C:\Program Files (x86)\LuaRocks\systree\share\lua\5.1\?.lua;C:\Program Files (x86)\LuaRocks\systree\share\lua\5.1\?\init.lua
  LUA_CPATH:   C:\Program Files (x86)\LuaRocks\systree\lib\lua\5.1\?.dll

Thanks

Note that the %APPDATA% element in the paths above is user specific and it MUST be replaced by its actual value.
For the current user that value is: C:\Users\Benjamin Tiessen\AppData\Roaming.
```

**Comment by Seeniea** [comment]
Thanks **ignacio**
