### ISSUE TITLE
Cannot uninstall LuaRocks

### ISSUE THREAD

**Issue by karai17** [keplerproject/luarocks#566]
A while ago I accidentally installed LuaRocks to the default location, which has caused me more trouble than I'd like to admit. I want to reinstall it globally which is simple enough, but I cannot seem to uninstall LuaRocks from the local location. There is no `make uninstall` option and I don't exactly know what to do at this point.

**Comment by hishamhm** [comment]
You mean from `/usr/local`?

Do this:

```shell
rm /usr/local/bin/luarocks*
rm -rf /usr/local/share/lua/5-*/luarocks
rm -rf /usr/local/etc/luarocks*
```

**Comment by karai17** [comment]
Thanks. It would be nice to have a make uninstall option, but doing this manually works.
