### ISSUE TITLE
/usr/bin/env lua and --lua-suffix=XXX

### ISSUE THREAD

**Issue by alnsn** [keplerproject/luarocks#568]
The `cleanup_bins` target in `./Makefile` sets the first line to `#!/usr/bin/env lua` even when a build is configured to use a custom lua suffix. It should instead set it to `#!/usr/bin/env luaXXX` where `XXX` is a requested suffix.

Code reference: https://github.com/keplerproject/luarocks/blob/master/Makefile#L119

**Comment by mpeterv** [comment]
`cleanup_bins` is used for `make clean`, not for building or installing. It's purpose is to _remove_ custom suffix from the scripts so that it can be reconfigured. When building, `build_bins` target does use correct path and suffix.
