### ISSUE TITLE
Error: Directory LuaTerminal not found inside archive LuaTerminal.git

### ISSUE THREAD

**Issue by aryajur** [keplerproject/luarocks#570]
LuaTerminal is a simple rockspec with just a Lua module. The rockspec is as follows:

    package = "LuaTerminal"
    version = "1.16.06.16-2"
    source = {
	url = "https://github.com/aryajur/LuaTerminal.git",
	tag = "1.16.06"
    }
    description = {
    .......
    }
    dependencies = {
	"lua >= 5.2",
	"luasocket",
    }
    build = {
	type = "builtin",
	modules = {
		LuaTerminal = "src/LuaTerminal.lua"
	}
    }

It seems LuaRocks is having some trouble with the uppercase letter in the module name.

**Comment by mpeterv** [comment]
The problem is that `source.url` starts with `https://`, so that LuaRocks thinks it points to a file that can be downloaded over https. If you are using `git`, url should start with `git://` (or `git+https://` to use git over https).

**Comment by aryajur** [comment]
Thanks!
