### ISSUE TITLE
Interact with multiple rocks at the same time

### ISSUE THREAD

**Issue by karai17** [keplerproject/luarocks#573]
```
luarocks install luasocket luafilesystem moonscript lapis

luarocks upgrade luasocket luafilesystem moonscript lapis

luarocks remove luasocket luafilesystem moonscript lapis
```

The above would be very handy additions, allowing you to queue up a bunch of packages at once instead of needing to install them one at a time.

Example: A project I have has several dependencies and I would like to be able to tell people to simply copy/paste a line to install them all.

https://github.com/karai17/lapis-chan#other-stuff

**Comment by hishamhm** [comment]
This is not the first time we get this feature request. Unfortunately, this can't be added without breaking compatibility, because the second argument after the rock name is interpreted as being the version number.

**Comment by karai17** [comment]
What about comma delimiting?

**Comment by hishamhm** [comment]
It seems to me that the correct solution for your problem would be for you to write a rockspec for your project and specify your dependencies in it. Also, it would allow you to specify supported version ranges for your dependencies, which is missing from the instructions. (How do you know an incompatible version of any of these modules won't be released tomorrow, breaking your current build instructions?)

**Comment by karai17** [comment]
Problem is my project relies on more than just a few Lua modules, as noted
in my readme. Seems like only a half-measure to write a rockspec. Not to
mention my project wouldn't exactly run if it were installed via LuaRocks,
it needs to be installed in a web serving directory, or at leas tin a
directory that you can modify (config files, among others).

LuaRocks is supposed to be a package manager, and thus is should probably
take on some of these standard features that other package managers have.
Perhaps instead of having a second argument for version, a worthwhile
breaking change could be to append versions to the package name:

`luarocks install moonscript` installs the latest version

`luarocks install moonscript-1.3.0-1` installs the version desired


---
Landon Manning
lmanning17@gmail.com

**Comment by hishamhm** [comment]
> LuaRocks is supposed to be a package manager

Nice.

**Comment by mpeterv** [comment]
@karai17 if your project has to be installed in a complicated way it's better to use something like a requirement file, which can be simulated using an empty rockspec, see #266.

**Comment by karai17** [comment]
@hishamhm am I wrong in this?

@mpeterv I'll look into this.
