### ISSUE TITLE
luasec

### ISSUE THREAD

**Issue by zhongzho** [keplerproject/luarocks#575]
Hi all, 

luarocks install cutorch
Warning: falling back to curl - install luasec to get native HTTPS support

Error: No results matching query were found.

How to ensure it searches for cutorch using HTTPS support. I tried installing luasec, but it is also problematic. Any ideas? 

Cheers, 
Zhong

**Comment by hishamhm** [comment]
Hi!

>  I tried installing luasec, but it is also problematic.

What do you mean by problematic? Did it fail to install? You may need to pass it OPENSSL_LIBDIR= and OPENSSL_INCDIR= with the location of OpenSSL libraries and headers.

**Comment by hishamhm** [comment]
> How to ensure it searches for cutorch using HTTPS support.

Also, don't worry: when falling back to Curl it _is_ using HTTPS. Just not via a Lua module.

**Comment by zhongzho** [comment]
Thank you! Yes, it fails to install.

I am installing everything without sudo to my home directory. And I will try to pass OPENSSL_LIBDIR and try again. Thank you!
