### ISSUE TITLE
error executing git.lua

### ISSUE THREAD

**Issue by aryajur** [keplerproject/luarocks#576]
Using https://rocks.moonscript.org/pgmoon-1.4.0-1.src.rock... switching to 'build' mode

Missing dependencies for pgmoon:
luabitop

Using https://rocks.moonscript.org/luabitop-1.0.2-3.rockspec... switching to 'build' mode
sh: 1: git: not found

Error: LuaRocks 2.2.0 bug (please report at luarocks-developers@lists.sourceforge.net).
/usr/share/lua/5.1/luarocks/fetch/git.lua:19: attempt to index local 'version_string' (a nil value)
stack traceback:
        /usr/share/lua/5.1/luarocks/fetch/git.lua:19: in function 'git_can_clone_by_tag'
        /usr/share/lua/5.1/luarocks/fetch/git.lua:63: in function </usr/share/lua/5.1/luarocks/fetch/git.lua:33>
        (tail call): ?
        /usr/share/lua/5.1/luarocks/build.lua:197: in function </usr/share/lua/5.1/luarocks/build.lua:162>
        (tail call): ?
        /usr/share/lua/5.1/luarocks/build.lua:398: in function </usr/share/lua/5.1/luarocks/build.lua:386>
        (tail call): ?
        /usr/share/lua/5.1/luarocks/deps.lua:487: in function 'fulfill_dependencies'
        /usr/share/lua/5.1/luarocks/build.lua:178: in function 'build_rockspec'
        /usr/share/lua/5.1/luarocks/build.lua:356: in function </usr/share/lua/5.1/luarocks/build.lua:345>
        ...
        /usr/share/lua/5.1/luarocks/build.lua:356: in function </usr/share/lua/5.1/luarocks/build.lua:345>
        (tail call): ?
        /usr/share/lua/5.1/luarocks/build.lua:398: in function </usr/share/lua/5.1/luarocks/build.lua:386>
        (tail call): ?
        (tail call): ?
        (tail call): ?
        [C]: in function 'xpcall'
        /usr/share/lua/5.1/luarocks/command_line.lua:208: in function 'run_command'
        /usr/bin/luarocks:33: in main chunk
        [C]: ?

**Comment by ignacio** [comment]
Hi! Later LuaRocks releases checks that the needed utilities are available. In this case, this particular module needs git to be installed so the sources can be retrieved.

Maybe a better rockspec can be submitted? One that points to a proper LuaBitop release?

Anyway, I think this can be closed.
