### ISSUE TITLE
Running tests locally shouldn't require global Lua installation

### ISSUE THREAD

**Issue by mpeterv** [keplerproject/luarocks#582]
Currently if travis option isn't passed the new tests look for lua in `/usr/local/bin` and `/usr/bin` and then fail if there is nothing there. I think it would be better to infer path to lua executable from global `arg` and use that. This way it's easy to test luarocks with different Lua versions installed with hererocks or luaver.

**Comment by robooo** [comment]
with busted command you get something like '/usr/local/lib/luarocks/rocks-5.2/busted/2.0.rc12-1/bin/busted' in arg[0]

**Comment by hishamhm** [comment]
perhaps a solution would be to require("luarocks.site_config") and try to build the path using LUA_BINDIR and LUA_INTERPRETER?

**Comment by hishamhm** [comment]
or instead, `require("luarocks.cfg")` and use `cfg.variables.LUA_BINDIR` and `cfg.lua_interpreter` (because cfg sets defaults when site_config is missing)

**Comment by mpeterv** [comment]
@robooo Lua interpreter puts all elements in original argv into `arg`, so that `arg[0]` is path to executed script (busted in this case), before that go various options like `-e` and `-l` and the value for the smallest existing negative key is path to lua interpreter.

@hishamhm yes, that's probably better, I'll try it.

**Comment by robooo** [comment]
@mpeterv Could I use something like on line 
https://github.com/keplerproject/luarocks/blob/master/test/test_environment.lua#L442
but with .variables.LUA_BINDIR?

**Comment by mpeterv** [comment]
@robooo but that command uses `test_env.testing_paths.lua`, so we can't use it to build `test_env.testing_paths.lua`.

Also, help for the test suite says that Lua has to be in PATH but is it actually necessary if test environment seemingly uses absolute paths when calling it? I'd like to run the tests with Lua not in PATH, e.g. `~/lua51/bin/busted`, `~/lua52/bin/busted`, etc.

**Comment by mpeterv** [comment]
@hishamhm seems to work: https://github.com/keplerproject/luarocks/pull/583/commits/a05ba7ce42ae4e42f80b5cacdd8770ae5e6cc04b
