### ISSUE TITLE
tests: Use busted 'helper' script

### ISSUE THREAD

**Issue by daurnimator** [keplerproject/luarocks#586]
Instead of requiring test_env in every script, use busted's helper script facility.

example usage:
https://github.com/daurnimator/lua-http/blob/master/.busted#L5
https://github.com/daurnimator/lua-http/blob/master/spec/helper.lua

**Comment by hishamhm** [comment]
@robooo, check this out!

**Comment by mpeterv** [comment]
@daurnimator we already use test_env module as helper, mainly to make it easier to pass options to it using -Xhelper. Do you suggest setting all its fields as globals?

**Comment by daurnimator** [comment]
> @daurnimator we already use test_env module as helper, mainly to make it easier to pass options to it using -Xhelper. Do you suggest setting all its fields as globals?

Yeah. The idea is to set globals so that the boilerplate in specs is reduced.

**Comment by hishamhm** [comment]
I don't mind a bit of `require` boilerplate, if it makes it clearer to see where stuff in a file comes from.

**Comment by hishamhm** [comment]
Let's close this and leave things as is for a while. If boilerplate gets too unwieldy, we'll revisit this in a later time.
