### ISSUE TITLE
Don't Work Install luasql-odbc

### ISSUE THREAD

**Issue by joneireis** [keplerproject/luarocks#599]
`$ sudo  luarocks install --server=http://luarocks.org/dev luasql-odbc
Warning: falling back to wget - install luasec to get native HTTPS support
Installing http://luarocks.org/dev/luasql-odbc-cvs-1.rockspec...
Using http://luarocks.org/dev/luasql-odbc-cvs-1.rockspec... switching to 'build' mode
Cloning into 'luasql'...
remote: Counting objects: 114, done.
remote: Compressing objects: 100% (87/87), done.
remote: Total 114 (delta 40), reused 51 (delta 13), pack-reused 0
Receiving objects: 100% (114/114), 92.81 KiB | 0 bytes/s, done.
Resolving deltas: 100% (40/40), done.
Checking connectivity... done.
usage: make { mysql | sqlite3 | odbc | postgres | firebird | sqlite | oci8 }
mkdir -p /usr/local/lib/luarocks/rocks/luasql-odbc/cvs-1/lib/luasql
cp src/*.so /usr/local/lib/luarocks/rocks/luasql-odbc/cvs-1/lib/luasql
cp: impossível obter estado de 'src/*.so': Arquivo ou diretório não encontrado
Makefile:31: recipe for target 'install' failed
make: *** [install] Error 1

Error: Build error: Failed installing.
`

**Comment by hishamhm** [comment]
Sorry about the late feedback. Please report the error to the maintainers of the luasql-odbc rock instead. Thanks!
