### ISSUE TITLE
luarocks make --pack-binary-rock repacks all dependencies

### ISSUE THREAD

**Issue by vladfedin** [keplerproject/luarocks#60]
If we need to make dozens of rocks using --pack-binary-rock luarocks packs every dependency for each rock.
Can we use rocks already installed in system to make rocks with --pack-binary-rock

**Comment by ignacio** [comment]
Maybe --pack-binary-rock could set automatically --deps-mode=none 

~~~~
d:\trunk_git>luarocks build --pack-binary-rock --deps-mode=none redis-lua
Warning: skipping dependency checks.
Updating manifest for C:\Users\Ignacio\AppData\Local\Temp/luarocks_luarocks-build-pack-redis-lua-2371/lib/luarocks/rocks
No existing manifest. Attempting to rebuild...
Missing dependency for redis-lua 2.0.4-1: luasocket
Missing dependency for redis-lua 2.0.4-1: luasocket
redis-lua 2.0.4-1 is now built and installed in C:\Users\Ignacio\AppData\Local\Temp/luarocks_luarocks-build-pack-redis-lua-2371 (license: MIT/X11) 
~~~~

**Comment by hishamhm** [comment]
> So the ability to point to some alternative place where all expected depencencies are installed seems 
> absolutely awesome. 

This can surely be done via configuration file.

> Maybe --pack-binary-rock could set automatically --deps-mode=none 

Don't know if this is good as a default behavior. Those who need it in custom environments as above can use the flag as you described, but as a default I'd prefer if LuaRocks actually went through the dependencies to make sure they're usable, as a sort of additional Q/A when one is packing a binary rock for redistribution.

Given we have a few alternatives already supported, can we close this one?

**Comment by ignacio** [comment]
Sure.
