### ISSUE TITLE
Outdated search results?

### ISSUE THREAD

**Issue by AKST** [keplerproject/luarocks#601]
> Heads up, I posted this in the mailing list but my email is still awaiting approval

------------

Hi all, I just setup luarocks & I was trying to install `lovelocks`, and according to package page on the luarocks site, it should be at version `0.0.8` yet searching the package through luarocks gives me this really old version (as shown below)...

```
~ λ luarocks search loverocks

Search results:
===============


Rockspecs and source rocks:
---------------------------

loverocks
   0.0.2-1 (rockspec) - https://luarocks.org
   0.0.2-1 (src) - https://luarocks.org
   0.0.1-1 (rockspec) - https://luarocks.org
   0.0.1-1 (src) - https://luarocks.org
```

And when I go to install it it doesn’t work. What’s going on here? This is my first time using luarocks so am I making a newbie error or something?

Cheers, Angus

**Comment by mpeterv** [comment]
Hi Angus, search results list rocks compatible with your Lua version. loverocks 0.0.1 and 0.0.2 are compatible with all Lua versions (or at least that's what's stated in their rockspecs), but later versions are for Lua 5.1. You must be using Lua 5.2 or 5.3.

**Comment by AKST** [comment]
Okay that makes sense I guess, what do you suggest is the best way for me to deal with this? Other than contacting the dev of lovelocks (& asking if he's able to increase the the lua version constraint), would I need to reinstall luarocks with the older version of lua, or am I able to to specify the lua version as 5.1, as the project is probably using with a version of lua wrapped with love itself.

**Comment by mpeterv** [comment]
You could download the rockspec for the latest loverocks release manually and edit the constraint on Lua version by hand. But it may be easier to make another luarocks installation using Lua 5.1. If I understand it correctly, Love uses Lua 5.1 internally, so if your luarocks uses Lua 5.2/5.3 you may install versions of packages that won't work with it.

**Comment by AKST** [comment]
Thanks the issue has been resolved, I'm closing this now.
