### ISSUE TITLE
Feature request: install.bat could autodetect /LV

### ISSUE THREAD

**Issue by hishamhm** [keplerproject/luarocks#602]
While looking at [this log](https://ci.appveyor.com/project/robooo/luarocks/build/2.2.1.304-test/job/9a7dx0uoywxt9ytf) it seems that install.bat succeeded finding a Lua executable (`/LUA` was given), but then it proceeded to try to find a Lua 5.1 library, when the Lua executable found was actually Lua 5.2. The installer could run the Lua executable after finding it (something like `lua -e 'print((_VERSION:gsub("Lua ","")))'`) to extract its version, and use it to auto-detect the version when `/LV` is not given (and possibly, to check that it is consistent, when `/LV` is given).

**Comment by mpeterv** [comment]
For other systems `./configure` already does that, right? Should be easy to replicate.
