### ISSUE TITLE
dpnn module required error

### ISSUE THREAD

**Issue by gonzalolc** [keplerproject/luarocks#615]
Hello

I'm running the text-classification example in NVIDIA DIGITS.
I already did luarocks install dpnn
and I get the following error:

ERROR: /usr/share/lua/5.1/trepl/init.lua:384: .../share/digits/digits/jobs/20160919-102150-25c4/model.lua:1: dpnn module required: luarocks install dpnn

My luarocks list:
luarocks list
Warning: Failed loading manifest for /home/gonzalo/.luarocks/lib/luarocks/rocks: /home/gonzalo/.luarocks/lib/luarocks/rocks/manifest: No such file or directory
Installed rocks:

argcheck
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

cudnn
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

cunn
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

cutorch
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

cwrap
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

dok
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

dpnn
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

env
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

gnuplot
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

graph
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

hdf5
0-0 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

image
1.1.alpha-0 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

lightningmdb
0.9.18.2-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

lpeg
1.0.0-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

lua-cjson
2.1devel-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

lua-pb
scm-0 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

luaffi
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

luafilesystem
1.6.3-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

moses
1.4.0-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

nccl
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

nn
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

nngraph
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

nnx
0.1-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

optim
1.0.5-0 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

paths
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

penlight
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

qtlua
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

qttorch
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

struct
1.4-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

sundown
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

sys
1.1-0 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

tds
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

threads
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

torch
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

totem
0-0 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

trepl
scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

xlua
1.0-0 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

I have changed the permissions of /usr/share/lua and /home/gonzalo/torch where the luarocks modules are installed to allow access to them.

How can I solve this?

**Comment by mpeterv** [comment]
What's output of `luarocks show dpnn`? What's output of `luajit -l dpnn`?

**Comment by gonzalolc** [comment]
for some reason it was searching the dpnn package under /usr/lib/luarocks and as I din't sudo when installing dpnn, it installed in ~/torch... directory
I just sudo luarocks install dpnn and it started working
