### ISSUE TITLE
attempt to yield across C-call boundary error when running in openresty luajit

### ISSUE THREAD

**Issue by mikz** [keplerproject/luarocks#620]
Luarocks version: 2.4.0
Works just fine with 2.3.0 and lower.

This is reproducible failure: https://travis-ci.org/3scale/apicast/builds/163398140

Steps to reproduce:

* get openresty
* compile luarocks in similar way: https://github.com/3scale/s2i-openresty/blob/9f3d4535b2810b3f2539c5c9d54dca178c71d48f/Dockerfile#L29-L36
* [`require 'luarocks.loader'`](https://github.com/3scale/docker-gateway/blob/5c6bc54e7d8430f22a2070015109fa1c43a45636/bin/busted)
* see `attempt to yield across C-call boundary` error

That happens because require in luajit is quite special and not much work can happen inside that require.

**Comment by mpeterv** [comment]
Can't reproduce. I'm running Ubuntu 16.04. I have nginx installed from apt-get (1.10.0). I used this to install openresty:

```
wget https://openresty.org/download/openresty-1.11.2.1.tar.gz
tar -xzvf openresty-1.11.2.1.tar.gz
cd openresty-1.11.2.1
./configure
make
make install
```

I used this to install luarocks:

```
wget https://github.com/keplerproject/luarocks/archive/v2.4.0.tar.gz -O luarocks-2.4.0.tar.gz
tar -xzvf luarocks-2.4.0.tar.gz
cd luarocks-2.4.0
./configure --prefix=/opt/luarocks-prefix --sysconfdir=/opt/luarocks-prefix/luarocks --force-config \
    --with-lua=/usr/local/openresty/luajit --lua-suffix=jit \
    --with-lua-include=/usr/local/openresty/luajit/include/luajit-2.1 --with-lua-version=5.1
make build
make install
```

Finally, the test:

```
eval `/opt/luarocks-prefix/bin/luarocks path`
/usr/local/openresty/luajit/bin/luajit -e "require [[luarocks.loader]]"
```

...completed successfully.

**Comment by mikz** [comment]
Could you try to reproduce with https://github.com/3scale/apicast/blob/v2/bin/busted ?

It uses `resty` instead of plain luajit. That runs in context of running nginx instance.

We were able to reproduce it on macOS machines too.

**Comment by mpeterv** [comment]
Running that script using resty does fail with `attempt to yield across C-call boundary`. It happens not when `require "luarocks.loader"`is called but when `require "busted.runner" is. It doesn't fail when using luajit directly, indeed.

**Comment by mpeterv** [comment]
Introduced in 6dc745a when luarocks loader started calling an utility function `util.sortedpairs` which uses coroutines.

**Comment by hishamhm** [comment]
@mikz Releasing 2.4.1 now. Please reopen if bug persists!
