### ISSUE TITLE
Install rocks to relevant path

### ISSUE THREAD

**Issue by moteus** [keplerproject/luarocks#632]
When I try install rockspecs to some path I got error. E.g.
```
c:\Temp>luarocks install eventemitter --tree=.\mytree
Installing https://luarocks.org/eventemitter-0.1.1-1.src.rock
c:\luarocks\x86\LuaRocks\tools\cp: cannot create regular file `.\\mytree\\lib\\luarocks\\rocks\\eventemitter\\0.1.1-1\\eventemitter-0.1.1-1.rockspec': No such file or directory
No existing manifest. Attempting to rebuild...

LuaRocks scm internal bug (please report at https://github.com/keplerproject/luarocks/issues):
c:\luarocks\x86\LuaRocks\lua\luarocks\fs\win32\tools.lua:95: assertion failed!

Error: Cannot access repository at ./mytree/lib/luarocks/rocks
```
But this command works without any error:
```
c:\Temp>luarocks install eventemitter --tree=mytree
Installing https://luarocks.org/eventemitter-0.1.1-1.src.rock
No existing manifest. Attempting to rebuild...
eventemitter 0.1.1-1 is now installed in c:/Temp/mytree (license: MIT/X11)
```
Absolute path also works
```
c:\Temp>luarocks install eventemitter --tree=c:\temp\mytree
Installing https://luarocks.org/eventemitter-0.1.1-1.src.rock
No existing manifest. Attempting to rebuild...
eventemitter 0.1.1-1 is now installed in c:/temp/mytree (license: MIT/X11)
```

**Comment by mpeterv** [comment]
The problem is that on Windows to determine if a path is absolute it's matched against `^[%.a-zA-Z]?:?[\\/]` for some reason. That matches all sorts of things like `.\mytree` and `a/b`, and the Luarocks thinking the path is absolute uses it from various temporary directories and doesn't create the tree correctly.

**Comment by moteus** [comment]
I think absolute paths may be like `C:\some\path`, `\some\path`
I do not think LuaRocks should handle UNC path though :)

**Comment by hishamhm** [comment]
Ouch, that pattern is seriously broken. I just went down Github's memory lane and turns out that pattern dates to the initial import of LuaForge's CVS in 2009. I'm on the go right now but it should be a matter of fixing the pattern.

**Comment by hishamhm** [comment]
I tried to reproduce this here:
https://github.com/keplerproject/luarocks/commit/55a9fd26a89c8f60c0ff69f153c75e300bd23b79
but did not get a failure:
https://ci.appveyor.com/project/hishamhm/luarocks/build/2.2.1.483-test/job/i8336x2hca2vcwid#L1504

Will try again with a backslash.

**Comment by moteus** [comment]
Make sure that folder does not exists before install.

**Comment by hishamhm** [comment]
@moteus Got it! Thanks!

https://ci.appveyor.com/project/hishamhm/luarocks/build/job/p28jesahxd3klmvi
