### ISSUE TITLE
What version of git does luarocks require?

### ISSUE THREAD

**Issue by hartzell** [keplerproject/luarocks#634]
I recently took a trip down a rabbit hole while trying to use [Spack](https://github.com/llnl/spack) to install Lmod, which requires lua and the luafilesystem rock.  It exploded and left this bit in the log file.

```
[hartzelg@spack spack]$ cat /tmp/hartzelg/spack-stage/spack-stage-P6RM_H/luafilesystem-v_1_6_3/spack-build.out
==> '/rss/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/lua-5.3.2-wkvqiqfuvioalijgr7kbrufkg4xxqkvv/bin/luarocks' '--tree=/rss/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/lua-luafilesystem-1_6_3-c2okue422sjfik3xncvoq3wu3plugekz' 'install' '/rss/spack/var/spack/stage/lua-luafilesystem-1_6_3-c2okue422sjfik3xncvoq3wu3plugekz/luafilesystem-v_1_6_3/rockspecs/luafilesystem-1.6.3-1.rockspec'
Using /rss/spack/var/spack/stage/lua-luafilesystem-1_6_3-c2okue422sjfik3xncvoq3wu3plugekz/luafilesystem-v_1_6_3/rockspecs/luafilesystem-1.6.3-1.rockspec... switching to 'build' mode
Cloning into 'luafilesystem'...
error: unable to find 0a82aae451c5c95ceacb5fcb235f4d1ea964f5f5
fatal: object of unexpected type
fatal: index-pack failed

Error: Failed cloning git repository.
```

After running around a bit, I figured out that this was happening under the covers

    os.execute:     cd '/tmp/luarocks_luafilesystem-1.6.3-1-997' && 'git' 'clone' '--branch=v_1_6_3' '--depth=1' 'git://github.com/keplerproject/luafilesystem' 'luafilesystem'

and that if I removed the `--depth=1` then I could run the command successfully by hand.

That system is CentOS 7 w/ `/usr/bin/git` at version 1.8.3.1.  

I upgraded git (using Spack) to 2.9.3 and luarocks started working again.

I'm wondering if this is a known issue?  I'm surprised that I haven't stumbled on this before...

Do you have a minimum version of git that luarocks requires?

Thanks,

**Comment by mpeterv** [comment]
I remember using git 1.7.9 with luarocks, it was OK. Strange. So `git clone --branch=v_1_6_3 --depth=1 git://github.com/keplerproject/luafilesystem' 'luafilesystem` consistenyl errors out like that for you?

**Comment by mpeterv** [comment]
I've built git 1.8.3.1 from source and the command runs fine.

**Comment by hartzell** [comment]
And I just stood up a new instance with my configuration and **it** also runs fine.

It's still hooked up to the same persistent filesystem so I'm not sure what's going on, but I'm going to assume that it was an occurrence of Problem Exists Between Keyboard and Chair and apologize for the wild goose chase.

> Sorry for the wild :chicken: chase!

Thank you for following up on it.  If it happens again and I can nail it down better, I'll follow up.
