### ISSUE TITLE
LUALIB is not available on non-Windows systems.

### ISSUE THREAD

**Issue by xpol** [keplerproject/luarocks#636]
LUALIB is not available on non-Windows systems (macOS and Linux etc...).

So if my rockspec worte:

```lua
build = {
  type = "cmake",
  variables = {
    CMAKE_INSTALL_PREFIX = "$(PREFIX)",
    LUA_INCLUDE_DIR = "$(LUA_INCDIR)",
    LUA_LIBRARIES = "$(LUA_LIBDIR)/$(LUALIB)"
  }
}
```

and releated CMakeLists.txt:

```cmake
target_link_libraries(target ${LUA_LIBRARIES})
```

On windows `$(LUALIB)` is the library name for Lua (see [here](https://github.com/keplerproject/luarocks/blob/master/install.bat#L1015)), so `LUA_LIBRARIES` would point to correct .lib file.

On other system, `$(LUALIB)` is not defined, `LUA_LIBRARIES` would evaluate to `$(LUA_LIBDIR)/` that is a directory, it would cause `target_link_libraries` raise warnings...

IMHO, it would be nice that `$(LUALIB)` available on all system so that make easy the write a rockspec.

**Comment by hishamhm** [comment]
On Oct 28, 2016 12:11 AM, "xpol" <notifications@github.com> wrote:
>
> LUALIB is not available on non-Windows systems (macOS and Linux etc...).
>
> So if my rockspec worte:
>
> build = { type = "cmake", variables = { CMAKE_INSTALL_PREFIX =
"$(PREFIX)", LUA_INCLUDE_DIR = "$(LUA_INCDIR)", LUA_LIBRARIES =
"$(LUA_LIBDIR)/$(LUALIB)" } }
>
> and releated CMakeLists.txt:
>
> target_link_libraries(target ${LUA_LIBRARIES})
>
> On windows $(LUALIB) is the library name for Lua (see here), so
LUA_LIBRARIES would point to correct .lib file.
>
> On other system, $(LUALIB) is not defined, LUA_LIBRARIES would evaluate
to $(LUA_LIBDIR)/ that is a directory, it would cause target_link_libraries
raise warnings...
>
> IMHO, it would be nice that $(LUALIB) available on all system so that
make easy the write a rockspec.

But on Unix platforms you shouldn't link to the Lua library explicitly.
Perhaps your CMakefile shouldn't be using LUA_LIBRARIES on these platforms?

**Comment by xpol** [comment]
Thank you for your information!

I'll to change may CMakeLists.txt.
