### ISSUE TITLE
Recieved an error when installing styler

### ISSUE THREAD

**Issue by avaicode** [keplerproject/luarocks#639]
Following is what's reported.
I just typed the command `sudo luarocks install styler`
>
Error: LuaRocks 2.4.1 bug (please report at https://github.com/keplerproject/luarocks/issues).
/usr/local/share/lua/5.3/luarocks/fs/lua.lua:508: attempt to call a nil value (method 'files')
stack traceback:
	/usr/local/share/lua/5.3/luarocks/fs/lua.lua:508: in function 'luarocks.fs.unzip'
	/usr/local/share/lua/5.3/luarocks/manif.lua:153: in function 'luarocks.manif.load_manifest'
	/usr/local/share/lua/5.3/luarocks/search.lua:181: in function 'luarocks.search.manifest_search'
	/usr/local/share/lua/5.3/luarocks/search.lua:215: in function 'luarocks.search.search_repos'
	/usr/local/share/lua/5.3/luarocks/search.lua:307: in function 'luarocks.search.find_suitable_rock'
	/usr/local/share/lua/5.3/luarocks/install.lua:179: in function 'luarocks.install.command'
	(...tail calls...)
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.3/luarocks/command_line.lua:180: in function 'luarocks.command_line.run_command'
	/usr/local/lib/luarocks/rocks/luarocks/2.4.1-1/bin/luarocks:33: in main chunk
	[C]: in ?

**Comment by mpeterv** [comment]
Do you have luazip installed? What does `luarocks show luazip` print?

**Comment by mpeterv** [comment]
This is a bug in luazip, I've sent a PR fixing it: rjpcomputing/luazip#6. In the meantime removing luazip by running `luarocks remove luazip` should help.
